version: "3"

services:
  db_mssql:
    build: ./dockerFiles/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Football!
      MSSQL_PID: enterprise
    ports:
      - ${DATABASE_PORT_MSSQL:-1433}:1433

  db_mongo:
    image: mongo:4.2.20-rc0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: flm
    volumes:
      - ./dockerFiles/mongo:/docker-entrypoint-initdb.d
    ports:
      - ${DATABASE_PORT_MONGO:-27017}:27017

  transporter:
    build: ./transport
    depends_on:
      - db_mssql
      - db_mongo
