set nocount on;

insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (1, 'Qatar', 'Torrence', 'Storror', 'aan de', '12/2/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (2, 'Egypt', 'Hamid', 'Ansteys', null, '11/15/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (3, 'Republic of the Congo', 'Joaquin', 'Wrist', null, '2/28/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (4, 'Moldova', 'Rockwell', 'Martyntsev', null, '11/26/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (5, 'Haiti', 'Townie', 'Seamer', null, '4/9/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (6, 'Egypt', 'Hale', 'MacKibbon', null, '12/7/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (7, 'United States', 'Candy', 'Fidoe', 'uijt den', '12/16/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (8, 'Greece', 'Dagmar', 'McEllen', null, '2/11/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (9, 'Turkmenistan', 'Dulsea', 'Healy', null, '10/23/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (10, 'Brazil', 'Darwin', 'Pountain', null, '4/28/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (11, 'Mongolia', 'Ailis', 'Cowerd', null, '11/5/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (12, 'Brazil', 'Kalil', 'Corran', null, '3/21/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (13, 'Libya', 'Julie', 'Batman', null, '9/5/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (14, 'Indonesia', 'Jessie', 'Norcliff', null, '4/6/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (15, 'Georgia', 'Jakie', 'Marie', null, '8/17/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (16, 'Guinea-Bissau', 'Shem', 'Paddemore', null, '2/23/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (17, 'Papua New Guinea', 'Lotte', 'Blakeborough', null, '10/24/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (18, 'Paraguay', 'Des', 'Spain-Gower', null, '3/8/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (19, 'Botswana', 'Linda', 'Robet', null, '5/17/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (20, 'Slovenia', 'Edythe', 'Strutton', null, '5/30/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (21, 'Botswana', 'Pat', 'Rousel', null, '9/24/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (22, 'Germany', 'Torrence', 'Duffan', null, '8/27/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (23, 'Palestinian Territory', 'Norbert', 'Petrulis', null, '11/15/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (24, 'Macao', 'Harli', 'Sagg', null, '3/16/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (25, 'Pakistan', 'Marlin', 'Gregan', null, '4/24/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (26, 'Mongolia', 'Humbert', 'Arrighini', null, '7/28/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (27, 'Georgia', 'Carmel', 'Goring', null, '3/12/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (28, 'Nigeria', 'Vanya', 'Studart', 'uijt de', '1/11/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (29, 'Uganda', 'Lombard', 'Steffan', null, '2/2/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (30, 'Djibouti', 'Haze', 'Jilkes', null, '2/5/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (31, 'Portugal', 'Hershel', 'Cakebread', null, '5/2/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (32, 'Tokelau', 'Emmalee', 'Domange', null, '3/18/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (33, 'Peru', 'Robinet', 'Playfoot', null, '2/25/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (34, 'Armenia', 'Madelin', 'Blyth', null, '11/10/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (35, 'Czech Republic', 'Kelsey', 'Gobel', null, '5/24/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (36, 'Egypt', 'Carlyle', 'Whitley', null, '10/24/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (37, 'Kenya', 'Nilson', 'Graser', null, '9/30/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (38, 'Samoa', 'Andrej', 'Wolseley', null, '7/5/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (39, 'Malaysia', 'Kilian', 'Mignot', null, '12/14/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (40, 'Czech Republic', 'Micheil', 'Imlaw', null, '12/27/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (41, 'Sri Lanka', 'Ebony', 'Claybourn', null, '4/11/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (42, 'Kenya', 'Guillemette', 'Ferry', null, '1/21/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (43, 'Macedonia', 'Edwin', 'Etheridge', null, '2/19/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (44, 'Russia', 'Damian', 'Murfill', 'auf den', '10/8/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (45, 'Norway', 'Dominga', 'Fowell', null, '3/20/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (46, 'Sierra Leone', 'Arley', 'Olexa', null, '8/13/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (47, 'Israel', 'Devondra', 'Troker', null, '7/24/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (48, 'Sudan', 'Washington', 'Rowlands', 'de las', '11/21/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (49, 'Libya', 'Almira', 'Elphinstone', null, '6/26/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (50, 'Paraguay', 'Pegeen', 'Pelcheur', null, '5/17/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (51, 'Republic of the Congo', 'Kristine', 'Carefull', null, '11/11/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (52, 'Spain', 'Jenny', 'Safont', null, '8/30/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (53, 'Belgium', 'Nicholas', 'Frankcomb', null, '10/31/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (54, 'Turkmenistan', 'Cam', 'Antuk', null, '8/24/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (55, 'Italy', 'Warner', 'Pacquet', 'les', '5/4/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (56, 'Republic of the Congo', 'Dukie', 'Tapsfield', null, '5/31/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (57, 'Aland Islands', 'Bernete', 'Cereceres', null, '8/16/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (58, 'Finland', 'Thomas', 'Garlicke', null, '7/10/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (59, 'Moldova', 'Mella', 'Longfellow', null, '5/29/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (60, 'Paraguay', 'Herc', 'March', null, '5/24/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (61, 'American Samoa', 'Jean', 'Tipper', 'von t', '4/24/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (62, 'Australia', 'Lambert', 'Skedge', 'af', '4/9/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (63, 'Sri Lanka', 'Torey', 'Ottam', 'uit', '8/6/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (64, 'Kenya', 'Emanuel', 'Humbert', null, '10/6/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (65, 'Nigeria', 'Berkie', 'Halfacree', null, '7/10/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (66, 'Ireland', 'Donn', 'McAtamney', null, '11/5/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (67, 'Georgia', 'Daron', 'Ricardin', null, '1/19/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (68, 'Georgia', 'Alida', 'Padrick', null, '6/12/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (69, 'Finland', 'Bonnie', 'Trinder', null, '4/5/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (70, 'Morocco', 'Almeria', 'Shadfourth', null, '9/24/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (71, 'Papua New Guinea', 'Ardeen', 'Dungate', 'don', '6/1/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (72, 'Italy', 'Sher', 'Spacy', null, '11/15/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (73, 'Armenia', 'Orelee', 'Starmore', null, '4/17/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (74, 'Hungary', 'Jodi', 'Enrico', null, '7/1/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (75, 'Malta', 'Riki', 'Duffan', null, '10/5/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (76, 'Botswana', 'Crysta', 'Curgenven', null, '10/22/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (77, 'Libya', 'Merrielle', 'Ebbings', 'van van de', '5/21/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (78, 'Uzbekistan', 'Nicolette', 'Twinning', null, '12/29/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (79, 'Peru', 'Cass', 'Voase', null, '9/23/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (80, 'Zimbabwe', 'Ingamar', 'Lawling', null, '4/26/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (81, 'Afghanistan', 'Lynn', 'Stuckow', 'bij', '1/5/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (82, 'Sudan', 'Janna', 'Shenfish', null, '11/20/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (83, 'Bonaire, Saint Eustatius and Saba', 'Garrek', 'Rosendale', null, '7/5/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (84, 'Papua New Guinea', 'Gerald', 'Horsell', 'uit de', '11/3/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (85, 'Libya', 'Brunhilda', 'Harrald', 'aus dem', '4/27/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (86, 'Germany', 'Karena', 'Tunnoch', null, '11/24/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (87, 'Colombia', 'Melita', 'Smither', null, '10/13/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (88, 'Latvia', 'Bondie', 'Abendroth', null, '11/17/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (89, 'Montenegro', 'Darbee', 'De Bruyn', null, '9/12/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (90, 'Samoa', 'Delphinia', 'Haughin', null, '4/2/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (91, 'Micronesia', 'Mar', 'Bannister', null, '8/17/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (92, 'Tajikistan', 'Gilberto', 'Bruckner', null, '7/18/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (93, 'Lebanon', 'Juanita', 'Pattison', null, '1/2/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (94, 'Chad', 'Adria', 'Hoonahan', null, '4/19/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (95, 'Iran', 'Rozalin', 'Blackhurst', null, '10/8/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (96, 'Thailand', 'Louise', 'Heald', null, '5/13/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (97, 'Serbia', 'Lem', 'Shee', null, '2/17/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (98, 'Cameroon', 'Devonne', 'Ogdahl', null, '2/12/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (99, 'Thailand', 'Christos', 'Griffitt', null, '4/24/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (100, 'Afghanistan', 'Gavin', 'Hounson', null, '10/22/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (101, 'Canada', 'Billy', 'Sapey', null, '7/18/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (102, 'Paraguay', 'Errick', 'Hovel', null, '5/5/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (103, 'Libya', 'Myra', 'Davydzenko', null, '3/30/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (104, 'Bolivia', 'Bartel', 'Eric', null, '1/25/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (105, 'Peru', 'Alexa', 'Cloonan', null, '8/8/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (106, 'Greece', 'Barbie', 'Boreham', null, '11/6/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (107, 'Taiwan', 'Angus', 'Gowanson', null, '11/30/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (108, 'Senegal', 'Ferrell', 'Hubery', null, '1/5/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (109, 'Georgia', 'Jody', 'Dermot', null, '9/27/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (110, 'Czech Republic', 'Gwenneth', 'McKenney', null, '11/4/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (111, 'Lebanon', 'Zsazsa', 'Goodbarr', null, '4/2/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (112, 'Qatar', 'Carson', 'Nesbitt', 'las', '5/8/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (113, 'Brazil', 'Stevy', 'Diano', null, '2/12/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (114, 'Guinea-Bissau', 'Atalanta', 'Rubinovici', null, '3/16/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (115, 'Morocco', 'Bliss', 'Wickstead', null, '3/21/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (116, 'Sudan', 'Thain', 'Brammar', 'dos', '8/9/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (117, 'Afghanistan', 'Baxie', 'Germann', 'over', '7/19/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (118, 'Thailand', 'Rodger', 'Domelaw', null, '3/23/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (119, 'Yemen', 'Ogden', 'Frearson', 'voor ‘t', '7/2/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (120, 'Republic of the Congo', 'Tremain', 'Stouther', null, '4/23/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (121, 'Germany', 'Anett', 'Schade', null, '10/24/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (122, 'Vietnam', 'Duke', 'Vasilchikov', null, '8/2/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (123, 'Czech Republic', 'Forrester', 'Salery', null, '7/21/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (124, 'Zimbabwe', 'Auroora', 'Flanne', null, '7/4/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (125, 'Uzbekistan', 'Britt', 'Boshers', null, '10/17/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (126, 'Uruguay', 'Nadean', 'Lergan', null, '4/27/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (127, 'Macao', 'Feliks', 'Mellmoth', null, '5/7/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (128, 'Philippines', 'Bethany', 'Housiaux', null, '10/1/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (129, 'Sweden', 'Ulick', 'Dallewater', null, '8/17/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (130, 'Taiwan', 'Eduard', 'Franschini', null, '7/4/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (131, 'Lebanon', 'Archy', 'Daburn', null, '7/12/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (132, 'Croatia', 'Jeramey', 'Jennins', null, '10/22/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (133, 'Portugal', 'Abel', 'Gething', null, '4/24/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (134, 'Israel', 'Min', 'Dunlap', null, '3/16/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (135, 'Brazil', 'Goldi', 'Perview', 't', '5/10/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (136, 'Poland', 'Gustavo', 'Rodenburg', null, '12/29/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (137, 'Indonesia', 'Karissa', 'Jantet', null, '5/5/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (138, 'Bolivia', 'Lindi', 'Caulder', null, '2/27/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (139, 'El Salvador', 'Margaretta', 'Patty', null, '7/13/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (140, 'United States', 'Annabelle', 'Conrad', null, '8/7/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (141, 'South Korea', 'Sherwin', 'Perico', null, '8/3/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (142, 'Kazakhstan', 'Fred', 'Fairpool', null, '9/19/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (143, 'Honduras', 'Rossie', 'Prandi', null, '10/1/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (144, 'Uganda', 'Chrissy', 'Kenyam', 'a', '11/7/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (145, 'Tokelau', 'Peri', 'Gleeson', null, '1/22/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (146, 'Uzbekistan', 'Whitman', 'Wainer', 'van ‘t', '10/19/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (147, 'Malawi', 'Felita', 'Skerrett', null, '1/25/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (148, 'Chile', 'Prentiss', 'Larkcum', null, '11/27/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (149, 'Sudan', 'Farris', 'Wain', null, '7/28/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (150, 'Libya', 'Kelila', 'Krikorian', null, '12/30/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (151, 'Chad', 'Sonni', 'Gwin', null, '1/20/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (152, 'Israel', 'Gualterio', 'Attryde', null, '11/15/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (153, 'Macedonia', 'Sharla', 'Brookshaw', null, '9/1/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (154, 'Indonesia', 'Raul', 'Odd', 'te', '10/2/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (155, 'Japan', 'Kris', 'Dripp', null, '4/6/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (156, 'Myanmar', 'Demeter', 'Frend', null, '2/18/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (157, 'Slovenia', 'Arlene', 'Lewendon', null, '2/18/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (158, 'Bosnia and Herzegovina', 'Gustav', 'Noakes', null, '1/15/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (159, 'Macedonia', 'Aleksandr', 'Gaishson', null, '1/2/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (160, 'Ethiopia', 'Enrica', 'McCree', null, '3/25/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (161, 'Saint Vincent and the Grenadines', 'Winni', 'O''Gavin', null, '6/29/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (162, 'Yemen', 'Jeanine', 'Dow', null, '10/5/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (163, 'Haiti', 'Carissa', 'O''Hdirscoll', null, '9/13/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (164, 'Cuba', 'Sherwood', 'Mancer', null, '10/9/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (165, 'Latvia', 'Benji', 'Batalle', 'der', '1/10/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (166, 'Luxembourg', 'Ortensia', 'Mucklestone', null, '4/7/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (167, 'Syria', 'Cinnamon', 'Vittori', null, '10/9/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (168, 'Uruguay', 'Maddie', 'Ebbings', null, '2/25/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (169, 'Sudan', 'Carrol', 'Gandar', null, '2/5/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (170, 'Serbia', 'Milo', 'Burborough', 'ben', '3/9/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (171, 'Spain', 'Roxanne', 'Fussell', null, '8/11/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (172, 'Ireland', 'Mattias', 'Lednor', null, '3/24/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (173, 'Egypt', 'Kin', 'Eard', null, '8/9/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (174, 'Senegal', 'Ham', 'Liversage', 'dal’', '2/16/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (175, 'Russia', 'Shurlock', 'Sigward', null, '1/10/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (176, 'Japan', 'Elisha', 'Disbrow', null, '3/17/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (177, 'Chile', 'Doria', 'Jeaycock', null, '5/20/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (178, 'Laos', 'Pace', 'Swanston', null, '10/5/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (179, 'Israel', 'Catie', 'Andrzejak', null, '2/24/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (180, 'Pakistan', 'Symon', 'Ranvoise', null, '4/18/1999');
