set nocount on;
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (9, 'Macedonia', 'Mame', 'Feye', null, '5/16/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (99, 'Lebanon', 'Hinda', 'Husher', null, '4/25/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (98, 'Democratic Republic of the Congo', 'Felicia', 'Northen', null, '1/5/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (97, 'Tanzania', 'Philippe', 'Dumbar', null, '9/10/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (96, 'Aland Islands', 'Jaimie', 'Berrey', null, '11/7/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (95, 'Venezuela', 'Vera', 'Strafford', null, '6/5/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (94, 'Bulgaria', 'Trumann', 'Gooding', null, '11/12/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (93, 'Brazil', 'Arlinda', 'Ashleigh', null, '9/22/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (92, 'Kyrgyzstan', 'Dorella', 'Axten', null, '9/25/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (91, 'Colombia', 'Juieta', 'Carnachen', null, '10/26/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (90, 'Palestinian Territory', 'Libbey', 'Van Hove', null, '4/14/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (8, 'Slovenia', 'Whitman', 'Manass', null, '3/1/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (89, 'Macao', 'Sumner', 'Gabbot', null, '6/21/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (88, 'Ivory Coast', 'Hans', 'McGown', null, '5/19/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (87, 'South Korea', 'Nikolia', 'Ryce', null, '1/15/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (86, 'Guatemala', 'Forest', 'Domenichini', null, '11/15/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (85, 'Paraguay', 'Jada', 'Egiloff', null, '10/1/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (84, 'Mongolia', 'Webster', 'Rock', null, '1/1/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (83, 'China', 'Gusty', 'Cookman', null, '3/22/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (82, 'Macao', 'Cirstoforo', 'Spark', null, '10/2/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (81, 'Macao', 'Remington', 'MacCaughan', null, '11/26/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (80, 'Norway', 'Peirce', 'Hiddsley', null, '7/2/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (7, 'Libya', 'Efren', 'Newlands', null, '6/13/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (79, 'Aland Islands', 'Cam', 'Geffinger', 'in', '12/4/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (78, 'Germany', 'Honoria', 'Verrick', null, '9/30/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (77, 'France', 'Roanne', 'Lowdyane', 'du', '6/29/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (76, 'South Africa', 'Merline', 'Edward', null, '9/1/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (75, 'Russia', 'Marnia', 'Melmore', null, '3/5/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (74, 'Panama', 'Angelika', 'Saterthwait', 'le', '11/28/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (73, 'Taiwan', 'Nan', 'Freeburn', null, '7/17/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (72, 'Luxembourg', 'Trevor', 'Tansill', null, '5/29/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (71, 'Denmark', 'Lyndell', 'Avarne', null, '5/15/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (70, 'Jamaica', 'Chrisy', 'Spoole', null, '8/31/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (6, 'Macao', 'Alexia', 'Huyton', null, '6/5/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (69, 'Kenya', 'Margaret', 'O''Hogertie', null, '11/16/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (68, 'Nigeria', 'Donavon', 'Yakuntzov', null, '12/27/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (67, 'Venezuela', 'Adriane', 'Gwillym', 'dei', '4/28/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (66, 'Armenia', 'Lyndsey', 'Barnwell', null, '9/13/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (65, 'Saint Vincent and the Grenadines', 'Rena', 'Wharlton', null, '5/27/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (64, 'South Africa', 'Wenonah', 'Aylott', null, '3/8/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (63, 'Ireland', 'Jaynell', 'Statham', null, '2/26/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (62, 'Bonaire, Saint Eustatius and Saba', 'Darsie', 'Merkel', null, '10/30/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (61, 'Guinea-Bissau', 'Ambrosius', 'Sodeau', null, '5/16/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (60, 'Brazil', 'Celestine', 'Stewartson', 'de l', '1/21/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (5, 'Bosnia and Herzegovina', 'Elset', 'Kneale', null, '5/24/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (59, 'United States', 'Inez', 'Skelly', 'von ‘t', '1/15/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (58, 'Egypt', 'Adina', 'Harmant', null, '3/28/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (57, 'Jamaica', 'Lebbie', 'Gullane', null, '7/17/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (56, 'Morocco', 'Fionna', 'Ivanchov', 'aan t', '7/8/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (55, 'Estonia', 'Nerta', 'Prantoni', null, '7/28/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (54, 'Finland', 'Tamera', 'But', null, '3/6/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (53, 'Poland', 'Tansy', 'Millthorpe', null, '10/9/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (52, 'Malta', 'Willie', 'Bisterfeld', null, '8/20/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (51, 'Lebanon', 'Jamima', 'Duignan', null, '10/15/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (50, 'Afghanistan', 'Querida', 'Harrison', null, '7/22/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (4, 'Sri Lanka', 'Burton', 'Greenman', null, '11/30/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (49, 'Czech Republic', 'Denys', 'Cosslett', null, '11/8/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (48, 'Macedonia', 'Ulrica', 'Tieraney', null, '11/2/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (47, 'Djibouti', 'Inglis', 'Vass', null, '12/23/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (46, 'Russia', 'Sarita', 'Dakers', null, '6/2/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (45, 'Haiti', 'Chryste', 'Raynton', null, '4/13/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (44, 'China', 'Corrine', 'Carnall', null, '3/10/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (43, 'Albania', 'Tedmund', 'Janu', null, '9/5/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (42, 'Latvia', 'Serene', 'Whitwell', null, '8/3/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (41, 'Sweden', 'Ody', 'Castellucci', null, '7/2/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (40, 'South Africa', 'Starla', 'Cockshut', null, '4/21/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (3, 'Saint Vincent and the Grenadines', 'Leontyne', 'Gull', null, '8/1/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (39, 'Sri Lanka', 'Genny', 'Bransom', null, '5/26/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (38, 'Latvia', 'Diena', 'Reary', null, '5/30/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (37, 'Slovenia', 'Colene', 'Downey', null, '6/4/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (36, 'Slovenia', 'Barby', 'Tunaclift', null, '4/7/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (35, 'Morocco', 'Arvy', 'Glencros', 'im', '6/26/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (34, 'Chad', 'Denyse', 'Stearley', null, '1/22/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (33, 'Azerbaijan', 'Ciro', 'Donaldson', 'd’', '8/26/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (32, 'Finland', 'Hans', 'Teal', 'de las', '7/26/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (31, 'Tajikistan', 'Luther', 'Lewknor', null, '10/6/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (30, 'Jamaica', 'Noami', 'Hendriksen', null, '4/30/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (2, 'Iran', 'Casi', 'Prinnett', null, '6/28/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (29, 'Estonia', 'Glynn', 'Di Francecshi', null, '10/14/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (28, 'Slovenia', 'Chic', 'Straughan', null, '12/27/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (27, 'Aland Islands', 'Faydra', 'Hannent', null, '10/19/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (26, 'Thailand', 'Terri', 'Stearn', null, '12/13/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (25, 'Montenegro', 'Carline', 'Ostrich', null, '12/2/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (24, 'Tunisia', 'Laney', 'Mapother', null, '12/15/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (23, 'Italy', 'Maris', 'Cullity', null, '11/8/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (22, 'Sweden', 'Ebony', 'Gaddas', null, '2/23/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (21, 'Morocco', 'Emmey', 'Lenormand', null, '8/31/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (20, 'Indonesia', 'Spenser', 'Blatcher', null, '2/2/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (1, 'Moldova', 'Reid', 'Pape', 'ter', '4/17/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (19, 'El Salvador', 'Mag', 'Nancarrow', null, '9/3/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (18, 'Djibouti', 'Dacia', 'Bampkin', null, '9/19/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (17, 'Canada', 'Brucie', 'Halfacree', null, '2/18/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (16, 'Finland', 'Evangelin', 'Paquet', null, '3/4/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (15, 'Georgia', 'Berni', 'Wimpress', null, '3/3/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (153, 'Sudan', 'Cordelie', 'MacLure', null, '10/22/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (152, 'Uganda', 'Layton', 'Fido', 'uijt ten', '2/3/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (151, 'Serbia', 'Rasla', 'Angerstein', null, '8/26/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (150, 'Bangladesh', 'Ermentrude', 'Scrowton', null, '1/22/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (14, 'Afghanistan', 'Laurianne', 'Le Marchant', null, '6/1/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (149, 'Libya', 'Gael', 'Ugo', null, '1/4/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (148, 'Iran', 'Bastien', 'Bortol', null, '7/25/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (147, 'Uganda', 'Luce', 'Filintsev', null, '5/11/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (146, 'United States', 'Susan', 'Brocklebank', null, '1/24/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (145, 'South Africa', 'Curcio', 'Ovise', '‘t', '8/28/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (144, 'Argentina', 'Vincent', 'McDuffy', null, '5/29/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (143, 'Slovenia', 'Jamie', 'Rumke', null, '5/10/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (142, 'Afghanistan', 'Giffy', 'Hugle', null, '10/17/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (141, 'Moldova', 'Dotti', 'Van der Veldt', null, '4/16/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (140, 'Azerbaijan', 'Trey', 'Rawstorne', null, '6/27/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (13, 'Japan', 'Emmit', 'Husthwaite', null, '7/1/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (139, 'Venezuela', 'Lizette', 'Froude', null, '8/4/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (138, 'Italy', 'Codee', 'Wield', null, '7/2/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (137, 'Bulgaria', 'Loren', 'Alabone', null, '7/17/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (136, 'Kenya', 'Stanford', 'Benyon', null, '2/17/1994');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (135, 'Mali', 'Corey', 'Battill', null, '2/16/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (134, 'Sweden', 'Bari', 'Goor', null, '8/26/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (133, 'Canada', 'Hector', 'Lawling', null, '1/6/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (132, 'Australia', 'Dari', 'Pinxton', null, '9/14/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (131, 'Australia', 'Barri', 'Crocetto', null, '7/30/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (130, 'Honduras', 'Ban', 'Gritton', null, '6/11/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (12, 'Cuba', 'Norbie', 'Massen', null, '10/23/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (129, 'Pakistan', 'Dex', 'Playden', null, '2/27/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (128, 'Ghana', 'Maudie', 'Harpham', null, '12/1/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (127, 'United States', 'Jamesy', 'Curror', null, '10/22/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (126, 'Papua New Guinea', 'Sibley', 'Brands', null, '2/16/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (125, 'Malaysia', 'Dorey', 'Woodbridge', null, '9/15/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (124, 'Ukraine', 'Dylan', 'McNirlan', null, '12/1/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (123, 'Spain', 'Jolynn', 'Sowden', null, '10/29/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (122, 'Philippines', 'Mayor', 'Anthonsen', null, '9/30/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (121, 'Taiwan', 'Emmalee', 'Sheryne', null, '2/6/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (120, 'Laos', 'Rosemaria', 'Stuttard', '‘t', '6/3/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (11, 'Slovenia', 'Grazia', 'Dennis', null, '12/5/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (119, 'Norway', 'Benny', 'Stenson', null, '8/5/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (118, 'Pakistan', 'Lurleen', 'Revance', null, '8/25/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (117, 'Guatemala', 'Kellina', 'Bugge', null, '4/14/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (116, 'Malaysia', 'Humfried', 'Mulvagh', null, '12/3/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (115, 'Sudan', 'Tabbitha', 'Alyokhin', null, '6/26/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (114, 'Indonesia', 'Odetta', 'Acaster', null, '4/16/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (113, 'Samoa', 'Silvia', 'Legrand', null, '1/17/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (112, 'Latvia', 'Chadwick', 'Cotilard', null, '3/28/1990');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (111, 'Peru', 'Andris', 'Hollington', null, '10/31/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (110, 'Bolivia', 'Chip', 'Iffe', null, '11/24/1991');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (10, 'China', 'Kinsley', 'Spaule', null, '9/23/1997');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (109, 'South Korea', 'Hurleigh', 'Menloe', null, '4/13/1996');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (108, 'Mexico', 'Selie', 'Grendon', 'aan t', '12/8/1992');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (107, 'Ghana', 'Abdel', 'Collidge', null, '10/17/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (106, 'Vietnam', 'Xylina', 'Ianelli', null, '11/23/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (105, 'Uganda', 'Chrotoem', 'Milligan', null, '9/18/1993');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (104, 'Bonaire, Saint Eustatius and Saba', 'Yancy', 'Dallewater', null, '3/19/1999');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (103, 'Tunisia', 'Powell', 'Dadd', null, '11/2/1995');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (102, 'Tunisia', 'Fedora', 'Fewings', '‘s', '12/15/1998');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (101, 'Tunisia', 'Thebault', 'Antonov', null, '6/1/2000');
insert into PERSON (Person_id, Country_name, First_name, Last_name, Middle_name, Birth_date) values (100, 'Mali', 'Keane', 'Kirke', null, '1/12/1996');
