set nocount on;
insert into CITY (Country_name, City_name) values ('Zimbabwe', 'Odzi');
insert into CITY (Country_name, City_name) values ('Zimbabwe', 'Chipinge');
insert into CITY (Country_name, City_name) values ('Yemen', 'Māwiyah');
insert into CITY (Country_name, City_name) values ('Yemen', 'Kitāf');
insert into CITY (Country_name, City_name) values ('Yemen', 'Ad Dīs ash Sharqīyah');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Vĩnh Tường');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Thị Trấn Cao Phong');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Thị Trấn Cẩm Thủy');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Thành Phố Uông Bí');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Liên Chiểu');
insert into CITY (Country_name, City_name) values ('Vietnam', 'K Bang');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Tucaní');
insert into CITY (Country_name, City_name) values ('Venezuela', 'San Juan de Manapiare');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Pedraza La Vieja');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Maripa');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Cantaura');
insert into CITY (Country_name, City_name) values ('Uzbekistan', 'Qŭshkŭpir');
insert into CITY (Country_name, City_name) values ('Uzbekistan', 'Qŭrghontepa');
insert into CITY (Country_name, City_name) values ('Uzbekistan', 'Pop Shahri');
insert into CITY (Country_name, City_name) values ('Uzbekistan', 'Namangan');
insert into CITY (Country_name, City_name) values ('Uzbekistan', 'Kirgili');
insert into CITY (Country_name, City_name) values ('Uruguay', 'La Paloma');
insert into CITY (Country_name, City_name) values ('Uruguay', 'Barra de Carrasco');
insert into CITY (Country_name, City_name) values ('United States', 'Washington');
insert into CITY (Country_name, City_name) values ('United States', 'Virginia Beach');
insert into CITY (Country_name, City_name) values ('United States', 'Toledo');
insert into CITY (Country_name, City_name) values ('United States', 'Terre Haute');
insert into CITY (Country_name, City_name) values ('United States', 'San Jose');
insert into CITY (Country_name, City_name) values ('United States', 'San Antonio');
insert into CITY (Country_name, City_name) values ('United States', 'Reno');
insert into CITY (Country_name, City_name) values ('United States', 'Portland');
insert into CITY (Country_name, City_name) values ('United States', 'Mesquite');
insert into CITY (Country_name, City_name) values ('United States', 'Lynn');
insert into CITY (Country_name, City_name) values ('United States', 'Louisville');
insert into CITY (Country_name, City_name) values ('United States', 'Little Rock');
insert into CITY (Country_name, City_name) values ('United States', 'Jackson');
insert into CITY (Country_name, City_name) values ('United States', 'Detroit');
insert into CITY (Country_name, City_name) values ('United States', 'Cincinnati');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Zakupne');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Volochys’k');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Veselynove');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Velyka Bilozerka');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Tsarychanka');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Sambir');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Rozivka');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Kozova');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Kirovs’k');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Khartsyz’k');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Hulyaypole');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Horodnya');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Derhachi');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Chapayevka');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Batiovo');
insert into CITY (Country_name, City_name) values ('Uganda', 'Kyegegwa');
insert into CITY (Country_name, City_name) values ('Turkmenistan', 'Türkmenbaşy');
insert into CITY (Country_name, City_name) values ('Turkmenistan', 'Gazojak');
insert into CITY (Country_name, City_name) values ('Tunisia', 'Menzel Jemil');
insert into CITY (Country_name, City_name) values ('Tunisia', 'Douz');
insert into CITY (Country_name, City_name) values ('Tunisia', 'Bizerte');
insert into CITY (Country_name, City_name) values ('Tunisia', 'Al Metlaoui');
insert into CITY (Country_name, City_name) values ('Tunisia', 'Al ‘Āliyah');
insert into CITY (Country_name, City_name) values ('Tokelau', 'Fale old settlement');
insert into CITY (Country_name, City_name) values ('Togo', 'Badou');
insert into CITY (Country_name, City_name) values ('Thailand', 'Tha Tako');
insert into CITY (Country_name, City_name) values ('Thailand', 'Tha Mai');
insert into CITY (Country_name, City_name) values ('Thailand', 'Suphan Buri');
insert into CITY (Country_name, City_name) values ('Thailand', 'Sathing Phra');
insert into CITY (Country_name, City_name) values ('Thailand', 'Samut Songkhram');
insert into CITY (Country_name, City_name) values ('Thailand', 'Phra Pradaeng');
insert into CITY (Country_name, City_name) values ('Thailand', 'Na Yung');
insert into CITY (Country_name, City_name) values ('Thailand', 'Mae Lan');
insert into CITY (Country_name, City_name) values ('Thailand', 'Kaeng Khoi');
insert into CITY (Country_name, City_name) values ('Thailand', 'Damnoen Saduak');
insert into CITY (Country_name, City_name) values ('Thailand', 'Chatuchak');
insert into CITY (Country_name, City_name) values ('Thailand', 'Bueng Khong Long');
insert into CITY (Country_name, City_name) values ('Tanzania', 'Kisesa');
insert into CITY (Country_name, City_name) values ('Tanzania', 'Kintinku');
insert into CITY (Country_name, City_name) values ('Tajikistan', 'Proletar');
insert into CITY (Country_name, City_name) values ('Taiwan', 'Jincheng');
insert into CITY (Country_name, City_name) values ('Syria', 'Darkūsh');
insert into CITY (Country_name, City_name) values ('Sweden', 'Västerås');
insert into CITY (Country_name, City_name) values ('Sweden', 'Uppsala');
insert into CITY (Country_name, City_name) values ('Sweden', 'Trollhättan');
insert into CITY (Country_name, City_name) values ('Sweden', 'Svedala');
insert into CITY (Country_name, City_name) values ('Sweden', 'Stockholm');
insert into CITY (Country_name, City_name) values ('Sweden', 'Stenungsund');
insert into CITY (Country_name, City_name) values ('Sweden', 'Sölvesborg');
insert into CITY (Country_name, City_name) values ('Sweden', 'Partille');
insert into CITY (Country_name, City_name) values ('Sweden', 'Oxelösund');
insert into CITY (Country_name, City_name) values ('Sweden', 'Örebro');
insert into CITY (Country_name, City_name) values ('Sweden', 'Mörrum');
insert into CITY (Country_name, City_name) values ('Sweden', 'Lycksele');
insert into CITY (Country_name, City_name) values ('Sweden', 'Luleå');
insert into CITY (Country_name, City_name) values ('Sweden', 'Löddeköpinge');
insert into CITY (Country_name, City_name) values ('Sweden', 'Lidköping');
insert into CITY (Country_name, City_name) values ('Sweden', 'Kista');
insert into CITY (Country_name, City_name) values ('Sweden', 'Karlstad');
insert into CITY (Country_name, City_name) values ('Sweden', 'Jönköping');
insert into CITY (Country_name, City_name) values ('Sweden', 'Järfälla');
insert into CITY (Country_name, City_name) values ('Sweden', 'Herrljunga');
insert into CITY (Country_name, City_name) values ('Sweden', 'Grängesberg');
insert into CITY (Country_name, City_name) values ('Sweden', 'Göteborg');
insert into CITY (Country_name, City_name) values ('Sweden', 'Frösön');
insert into CITY (Country_name, City_name) values ('Sweden', 'Eskilstuna');
insert into CITY (Country_name, City_name) values ('Sweden', 'Ekerö');
insert into CITY (Country_name, City_name) values ('Sweden', 'Edsbyn');
insert into CITY (Country_name, City_name) values ('Sweden', 'Bandhagen');
insert into CITY (Country_name, City_name) values ('Sweden', 'Åmål');
insert into CITY (Country_name, City_name) values ('Sudan', 'Kassala');
insert into CITY (Country_name, City_name) values ('Sri Lanka', 'Batticaloa');
insert into CITY (Country_name, City_name) values ('Spain', 'Santander');
insert into CITY (Country_name, City_name) values ('Spain', 'Pamplona/Iruña');
insert into CITY (Country_name, City_name) values ('South Korea', 'Eisen');
insert into CITY (Country_name, City_name) values ('South Korea', 'Asan');
insert into CITY (Country_name, City_name) values ('South Africa', 'Wartburg');
insert into CITY (Country_name, City_name) values ('South Africa', 'Postmasburg');
insert into CITY (Country_name, City_name) values ('South Africa', 'Middelburg');
insert into CITY (Country_name, City_name) values ('South Africa', 'Lebowakgomo');
insert into CITY (Country_name, City_name) values ('South Africa', 'Izingolweni');
insert into CITY (Country_name, City_name) values ('South Africa', 'Frankfort');
insert into CITY (Country_name, City_name) values ('South Africa', 'eMbalenhle');
insert into CITY (Country_name, City_name) values ('Slovenia', 'Radlje ob Dravi');
insert into CITY (Country_name, City_name) values ('Slovenia', 'Moravče');
insert into CITY (Country_name, City_name) values ('Sierra Leone', 'Baiima');
insert into CITY (Country_name, City_name) values ('Serbia', 'Prislonica');
insert into CITY (Country_name, City_name) values ('Serbia', 'Pančevo');
insert into CITY (Country_name, City_name) values ('Serbia', 'Kula');
insert into CITY (Country_name, City_name) values ('Serbia', 'Kruševac');
insert into CITY (Country_name, City_name) values ('Serbia', 'Jermenovci');
insert into CITY (Country_name, City_name) values ('Serbia', 'Ćuprija');
insert into CITY (Country_name, City_name) values ('Senegal', 'Gandiaye');
insert into CITY (Country_name, City_name) values ('Samoa', 'Malie');
insert into CITY (Country_name, City_name) values ('Saint Vincent and the Grenadines', 'Georgetown');
insert into CITY (Country_name, City_name) values ('Russia', 'Zhukovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Zhigulevsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Zherdevka');
insert into CITY (Country_name, City_name) values ('Russia', 'Zheleznodorozhnyy');
insert into CITY (Country_name, City_name) values ('Russia', 'Zelenchukskaya');
insert into CITY (Country_name, City_name) values ('Russia', 'Zavolzh’ye');
insert into CITY (Country_name, City_name) values ('Russia', 'Zarya');
insert into CITY (Country_name, City_name) values ('Russia', 'Yazykovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Vostryakovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Vol’nyy Aul');
insert into CITY (Country_name, City_name) values ('Russia', 'Vilya');
insert into CITY (Country_name, City_name) values ('Russia', 'Verkhnyaya Toyma');
insert into CITY (Country_name, City_name) values ('Russia', 'Velikooktyabr’skiy');
insert into CITY (Country_name, City_name) values ('Russia', 'Ursk');
insert into CITY (Country_name, City_name) values ('Russia', 'Tver');
insert into CITY (Country_name, City_name) values ('Russia', 'Turka');
insert into CITY (Country_name, City_name) values ('Russia', 'Torzhok');
insert into CITY (Country_name, City_name) values ('Russia', 'Temizhbekskaya');
insert into CITY (Country_name, City_name) values ('Russia', 'Tbilisskaya');
insert into CITY (Country_name, City_name) values ('Russia', 'Tarusa');
insert into CITY (Country_name, City_name) values ('Russia', 'Tarbagatay');
insert into CITY (Country_name, City_name) values ('Russia', 'Suslonger');
insert into CITY (Country_name, City_name) values ('Russia', 'Sukhinichi');
insert into CITY (Country_name, City_name) values ('Russia', 'Strelka');
insert into CITY (Country_name, City_name) values ('Russia', 'Starominskaya');
insert into CITY (Country_name, City_name) values ('Russia', 'Spasskoye');
insert into CITY (Country_name, City_name) values ('Russia', 'Solikamsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Skopin');
insert into CITY (Country_name, City_name) values ('Russia', 'Sinyavino');
insert into CITY (Country_name, City_name) values ('Russia', 'Shestakovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Shchëkino');
insert into CITY (Country_name, City_name) values ('Russia', 'Severo-Zadonsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Sasykoli');
insert into CITY (Country_name, City_name) values ('Russia', 'Sabnova');
insert into CITY (Country_name, City_name) values ('Russia', 'Pryazha');
insert into CITY (Country_name, City_name) values ('Russia', 'Pridonskoy');
insert into CITY (Country_name, City_name) values ('Russia', 'Povenets');
insert into CITY (Country_name, City_name) values ('Russia', 'Pokrovka');
insert into CITY (Country_name, City_name) values ('Russia', 'Plavsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Parizh');
insert into CITY (Country_name, City_name) values ('Russia', 'Ostrogozhsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Orsha');
insert into CITY (Country_name, City_name) values ('Russia', 'Orlovskiy');
insert into CITY (Country_name, City_name) values ('Russia', 'Orekhovo-Zuyevo');
insert into CITY (Country_name, City_name) values ('Russia', 'Novopokrovka');
insert into CITY (Country_name, City_name) values ('Russia', 'Novopodrezkovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Novokuz’minki');
insert into CITY (Country_name, City_name) values ('Russia', 'Naurskaya');
insert into CITY (Country_name, City_name) values ('Russia', 'Moscow');
insert into CITY (Country_name, City_name) values ('Russia', 'Monino');
insert into CITY (Country_name, City_name) values ('Russia', 'Melenki');
insert into CITY (Country_name, City_name) values ('Russia', 'Manzherok');
insert into CITY (Country_name, City_name) values ('Russia', 'Luknovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Luchegorsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Ladushkin');
insert into CITY (Country_name, City_name) values ('Russia', 'Kuzovatovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Kraskino');
insert into CITY (Country_name, City_name) values ('Russia', 'Kostino');
insert into CITY (Country_name, City_name) values ('Russia', 'Kimil’tey');
insert into CITY (Country_name, City_name) values ('Russia', 'Kaliningrad');
insert into CITY (Country_name, City_name) values ('Russia', 'Kabakovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Iksha');
insert into CITY (Country_name, City_name) values ('Russia', 'Gur’yevsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Gornyy');
insert into CITY (Country_name, City_name) values ('Russia', 'Golovchino');
insert into CITY (Country_name, City_name) values ('Russia', 'Gereykhanovskoye');
insert into CITY (Country_name, City_name) values ('Russia', 'Chernogorsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Chagoda');
insert into CITY (Country_name, City_name) values ('Russia', 'Bureya');
insert into CITY (Country_name, City_name) values ('Russia', 'Bogandinskiy');
insert into CITY (Country_name, City_name) values ('Russia', 'Berëzovka');
insert into CITY (Country_name, City_name) values ('Russia', 'Arsen’yev');
insert into CITY (Country_name, City_name) values ('Republic of the Congo', 'Pointe-Noire');
insert into CITY (Country_name, City_name) values ('Qatar', 'Az̧ Z̧a‘āyin');
insert into CITY (Country_name, City_name) values ('Qatar', 'Ar Ru’ays');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vila Viçosa');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vila Nova da Baronia');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vera Cruz');
insert into CITY (Country_name, City_name) values ('Portugal', 'Várzea da Serra');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vale da Bajouca');
insert into CITY (Country_name, City_name) values ('Portugal', 'Urrô');
insert into CITY (Country_name, City_name) values ('Portugal', 'Trafaria');
insert into CITY (Country_name, City_name) values ('Portugal', 'Tojeira');
insert into CITY (Country_name, City_name) values ('Portugal', 'Sobral da Abelheira');
insert into CITY (Country_name, City_name) values ('Portugal', 'Seixas do Douro');
insert into CITY (Country_name, City_name) values ('Portugal', 'Sarrazola');
insert into CITY (Country_name, City_name) values ('Portugal', 'São Miguel de Machede');
insert into CITY (Country_name, City_name) values ('Portugal', 'São Manços');
insert into CITY (Country_name, City_name) values ('Portugal', 'Rio de Moinhos');
insert into CITY (Country_name, City_name) values ('Portugal', 'Picoto');
insert into CITY (Country_name, City_name) values ('Portugal', 'Olhão');
insert into CITY (Country_name, City_name) values ('Portugal', 'Meia Via');
insert into CITY (Country_name, City_name) values ('Portugal', 'Lourido');
insert into CITY (Country_name, City_name) values ('Portugal', 'Jardia');
insert into CITY (Country_name, City_name) values ('Portugal', 'Janes');
insert into CITY (Country_name, City_name) values ('Portugal', 'Gaula');
insert into CITY (Country_name, City_name) values ('Portugal', 'Gândara');
insert into CITY (Country_name, City_name) values ('Portugal', 'Galamares');
insert into CITY (Country_name, City_name) values ('Portugal', 'Figueiró dos Vinhos');
insert into CITY (Country_name, City_name) values ('Portugal', 'Costa de Rios Frios');
insert into CITY (Country_name, City_name) values ('Portugal', 'Cimo de Vila');
insert into CITY (Country_name, City_name) values ('Portugal', 'Casais de Vera Cruz');
insert into CITY (Country_name, City_name) values ('Portugal', 'Calvaria de Baixo');
insert into CITY (Country_name, City_name) values ('Portugal', 'Bicas');
insert into CITY (Country_name, City_name) values ('Portugal', 'Azeitão');
insert into CITY (Country_name, City_name) values ('Portugal', 'Atães');
insert into CITY (Country_name, City_name) values ('Portugal', 'Arão');
insert into CITY (Country_name, City_name) values ('Portugal', 'Amieira do Tejo');
insert into CITY (Country_name, City_name) values ('Portugal', 'Abades');
insert into CITY (Country_name, City_name) values ('Poland', 'Żółkiewka');
insert into CITY (Country_name, City_name) values ('Poland', 'Zambrów');
insert into CITY (Country_name, City_name) values ('Poland', 'Wolin');
insert into CITY (Country_name, City_name) values ('Poland', 'Wiskitki');
insert into CITY (Country_name, City_name) values ('Poland', 'Wilczyce');
insert into CITY (Country_name, City_name) values ('Poland', 'Węgry');
insert into CITY (Country_name, City_name) values ('Poland', 'Wałcz');
insert into CITY (Country_name, City_name) values ('Poland', 'Świętajno');
insert into CITY (Country_name, City_name) values ('Poland', 'Stoczek Łukowski');
insert into CITY (Country_name, City_name) values ('Poland', 'Sosnówka');
insert into CITY (Country_name, City_name) values ('Poland', 'Solec Nad Wisłą');
insert into CITY (Country_name, City_name) values ('Poland', 'Skrwilno');
insert into CITY (Country_name, City_name) values ('Poland', 'Skorogoszcz');
insert into CITY (Country_name, City_name) values ('Poland', 'Skawica');
insert into CITY (Country_name, City_name) values ('Poland', 'Ryczywół');
insert into CITY (Country_name, City_name) values ('Poland', 'Rybczewice');
insert into CITY (Country_name, City_name) values ('Poland', 'Rogów');
insert into CITY (Country_name, City_name) values ('Poland', 'Przyborów');
insert into CITY (Country_name, City_name) values ('Poland', 'Przewóz');
insert into CITY (Country_name, City_name) values ('Poland', 'Pruszków');
insert into CITY (Country_name, City_name) values ('Poland', 'Podgórzyn');
insert into CITY (Country_name, City_name) values ('Poland', 'Piotrków Trybunalski');
insert into CITY (Country_name, City_name) values ('Poland', 'Olszówka');
insert into CITY (Country_name, City_name) values ('Poland', 'Olkusz');
insert into CITY (Country_name, City_name) values ('Poland', 'Nieszawa');
insert into CITY (Country_name, City_name) values ('Poland', 'Mogilany');
insert into CITY (Country_name, City_name) values ('Poland', 'Miętne');
insert into CITY (Country_name, City_name) values ('Poland', 'Łeba');
insert into CITY (Country_name, City_name) values ('Poland', 'Laszki');
insert into CITY (Country_name, City_name) values ('Poland', 'Koronowo');
insert into CITY (Country_name, City_name) values ('Poland', 'Kamieniec Wrocławski');
insert into CITY (Country_name, City_name) values ('Poland', 'Januszkowice');
insert into CITY (Country_name, City_name) values ('Poland', 'Janowiec');
insert into CITY (Country_name, City_name) values ('Poland', 'Janowice');
insert into CITY (Country_name, City_name) values ('Poland', 'Grzybowa Góra');
insert into CITY (Country_name, City_name) values ('Poland', 'Grębów');
insert into CITY (Country_name, City_name) values ('Poland', 'Głubczyce');
insert into CITY (Country_name, City_name) values ('Poland', 'Dukla');
insert into CITY (Country_name, City_name) values ('Poland', 'Czeremcha');
insert into CITY (Country_name, City_name) values ('Poland', 'Czechowice-Dziedzice');
insert into CITY (Country_name, City_name) values ('Poland', 'Cieplice Śląskie Zdrój');
insert into CITY (Country_name, City_name) values ('Poland', 'Chojnów');
insert into CITY (Country_name, City_name) values ('Poland', 'Chodów');
insert into CITY (Country_name, City_name) values ('Poland', 'Brzozów');
insert into CITY (Country_name, City_name) values ('Poland', 'Borzęcin');
insert into CITY (Country_name, City_name) values ('Poland', 'Bodzentyn');
insert into CITY (Country_name, City_name) values ('Poland', 'Blizne');
insert into CITY (Country_name, City_name) values ('Poland', 'Biecz');
insert into CITY (Country_name, City_name) values ('Poland', 'Baranowo');
insert into CITY (Country_name, City_name) values ('Poland', 'Babice');
insert into CITY (Country_name, City_name) values ('Philippines', 'Zamboanguita');
insert into CITY (Country_name, City_name) values ('Philippines', 'Villa Aglipay');
insert into CITY (Country_name, City_name) values ('Philippines', 'Uacon');
insert into CITY (Country_name, City_name) values ('Philippines', 'Tubod');
insert into CITY (Country_name, City_name) values ('Philippines', 'Tawala');
insert into CITY (Country_name, City_name) values ('Philippines', 'Tamnag');
insert into CITY (Country_name, City_name) values ('Philippines', 'Tabuk');
insert into CITY (Country_name, City_name) values ('Philippines', 'Suyo');
insert into CITY (Country_name, City_name) values ('Philippines', 'Socorro');
insert into CITY (Country_name, City_name) values ('Philippines', 'Siraway');
insert into CITY (Country_name, City_name) values ('Philippines', 'Santol');
insert into CITY (Country_name, City_name) values ('Philippines', 'Santiago');
insert into CITY (Country_name, City_name) values ('Philippines', 'Santa Fe');
insert into CITY (Country_name, City_name) values ('Philippines', 'San Rafael');
insert into CITY (Country_name, City_name) values ('Philippines', 'Piñahan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Pangapisan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Pancol');
insert into CITY (Country_name, City_name) values ('Philippines', 'Pananaw');
insert into CITY (Country_name, City_name) values ('Philippines', 'Palanit');
insert into CITY (Country_name, City_name) values ('Philippines', 'Obong');
insert into CITY (Country_name, City_name) values ('Philippines', 'Natonin');
insert into CITY (Country_name, City_name) values ('Philippines', 'Merida');
insert into CITY (Country_name, City_name) values ('Philippines', 'Mapalad');
insert into CITY (Country_name, City_name) values ('Philippines', 'Mainit');
insert into CITY (Country_name, City_name) values ('Philippines', 'Mabilang');
insert into CITY (Country_name, City_name) values ('Philippines', 'Lusacan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Lupo');
insert into CITY (Country_name, City_name) values ('Philippines', 'Luksuhin');
insert into CITY (Country_name, City_name) values ('Philippines', 'Llanera');
insert into CITY (Country_name, City_name) values ('Philippines', 'Lagasit');
insert into CITY (Country_name, City_name) values ('Philippines', 'Kudanding');
insert into CITY (Country_name, City_name) values ('Philippines', 'Kolumbug');
insert into CITY (Country_name, City_name) values ('Philippines', 'Irosin');
insert into CITY (Country_name, City_name) values ('Philippines', 'Ilihan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Gasan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Dulag');
insert into CITY (Country_name, City_name) values ('Philippines', 'Daguma');
insert into CITY (Country_name, City_name) values ('Philippines', 'Conel');
insert into CITY (Country_name, City_name) values ('Philippines', 'Cogtong');
insert into CITY (Country_name, City_name) values ('Philippines', 'Cayang');
insert into CITY (Country_name, City_name) values ('Philippines', 'Carmen');
insert into CITY (Country_name, City_name) values ('Philippines', 'Candon');
insert into CITY (Country_name, City_name) values ('Philippines', 'Cabatuan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Cabanbanan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Butuan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Bungabon');
insert into CITY (Country_name, City_name) values ('Philippines', 'Bulod');
insert into CITY (Country_name, City_name) values ('Philippines', 'Bolboc');
insert into CITY (Country_name, City_name) values ('Philippines', 'Bolaoit');
insert into CITY (Country_name, City_name) values ('Philippines', 'Batasan Bata');
insert into CITY (Country_name, City_name) values ('Philippines', 'Barurao');
insert into CITY (Country_name, City_name) values ('Philippines', 'Balugo');
insert into CITY (Country_name, City_name) values ('Philippines', 'Angatel');
insert into CITY (Country_name, City_name) values ('Philippines', 'Aloleng');
insert into CITY (Country_name, City_name) values ('Peru', 'Zapatero');
insert into CITY (Country_name, City_name) values ('Peru', 'Yanahuaya');
insert into CITY (Country_name, City_name) values ('Peru', 'Yanacancha');
insert into CITY (Country_name, City_name) values ('Peru', 'Tomas');
insert into CITY (Country_name, City_name) values ('Peru', 'San Miguel de Cauri');
insert into CITY (Country_name, City_name) values ('Peru', 'San Antonio');
insert into CITY (Country_name, City_name) values ('Peru', 'Quichuay');
insert into CITY (Country_name, City_name) values ('Peru', 'Pueblo Nuevo');
insert into CITY (Country_name, City_name) values ('Peru', 'Pilcuyo');
insert into CITY (Country_name, City_name) values ('Peru', 'Mendoza');
insert into CITY (Country_name, City_name) values ('Peru', 'Marcabal');
insert into CITY (Country_name, City_name) values ('Peru', 'Maranura');
insert into CITY (Country_name, City_name) values ('Peru', 'Maca');
insert into CITY (Country_name, City_name) values ('Peru', 'Laraos');
insert into CITY (Country_name, City_name) values ('Peru', 'Huayllati');
insert into CITY (Country_name, City_name) values ('Peru', 'Condoroma');
insert into CITY (Country_name, City_name) values ('Peru', 'Concordia');
insert into CITY (Country_name, City_name) values ('Peru', 'Caja');
insert into CITY (Country_name, City_name) values ('Peru', 'Bellavista');
insert into CITY (Country_name, City_name) values ('Peru', 'Acomayo');
insert into CITY (Country_name, City_name) values ('Paraguay', 'General Elizardo Aquino');
insert into CITY (Country_name, City_name) values ('Paraguay', 'Caazapá');
insert into CITY (Country_name, City_name) values ('Papua New Guinea', 'Aitape');
insert into CITY (Country_name, City_name) values ('Panama', 'La Palma');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Zaytā');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Kafr al Labad');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Banī Suhaylā');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', '‘Ābūd');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Wārāh');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Thatta');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Malakwāl');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Khārān');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Haveliān');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Haveli');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Chak');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Baffa');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Alīābad');
insert into CITY (Country_name, City_name) values ('Norway', 'Stavanger');
insert into CITY (Country_name, City_name) values ('Norway', 'Oslo');
insert into CITY (Country_name, City_name) values ('Norway', 'Harstad');
insert into CITY (Country_name, City_name) values ('Norway', 'Grimstad');
insert into CITY (Country_name, City_name) values ('North Korea', 'Yuktae-dong');
insert into CITY (Country_name, City_name) values ('North Korea', 'Ŭiju');
insert into CITY (Country_name, City_name) values ('North Korea', 'Sŏnbong');
insert into CITY (Country_name, City_name) values ('North Korea', 'Kilju');
insert into CITY (Country_name, City_name) values ('North Korea', 'Chasŏng');
insert into CITY (Country_name, City_name) values ('Niger', 'Tanout');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Zuru');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Osogbo');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Kwolla');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Kontagora');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Katsina-Ala');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Gujba');
insert into CITY (Country_name, City_name) values ('Niger', 'Birni N Konni');
insert into CITY (Country_name, City_name) values ('Netherlands', 'Waalwijk');
insert into CITY (Country_name, City_name) values ('Netherlands', '''s-Hertogenbosch');
insert into CITY (Country_name, City_name) values ('Netherlands', 'Schiedam postbusnummers');
insert into CITY (Country_name, City_name) values ('Netherlands', 'Harderwijk');
insert into CITY (Country_name, City_name) values ('Netherlands', 'Den Haag');
insert into CITY (Country_name, City_name) values ('Nepal', 'Jomsom');
insert into CITY (Country_name, City_name) values ('Myanmar', 'Myaydo');
insert into CITY (Country_name, City_name) values ('Myanmar', 'Chauk');
insert into CITY (Country_name, City_name) values ('Morocco', 'Tidili Mesfioua');
insert into CITY (Country_name, City_name) values ('Morocco', 'Taza');
insert into CITY (Country_name, City_name) values ('Morocco', 'Tabouda');
insert into CITY (Country_name, City_name) values ('Montenegro', 'Žabljak');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Mandal');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Jargalant');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Höshigiyn-Ar');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Duut');
insert into CITY (Country_name, City_name) values ('Moldova', 'Rîbniţa');
insert into CITY (Country_name, City_name) values ('Moldova', 'Floreşti');
insert into CITY (Country_name, City_name) values ('Moldova', 'Donduşeni');
insert into CITY (Country_name, City_name) values ('Micronesia', 'Lukunor');
insert into CITY (Country_name, City_name) values ('Mexico', 'Santa Rosa');
insert into CITY (Country_name, City_name) values ('Mexico', 'San Jose');
insert into CITY (Country_name, City_name) values ('Mexico', 'Guanajuato');
insert into CITY (Country_name, City_name) values ('Mexico', 'Francisco Villa');
insert into CITY (Country_name, City_name) values ('Mexico', 'Fernando Gutierrez Barrios');
insert into CITY (Country_name, City_name) values ('Mexico', 'Cuauhtemoc');
insert into CITY (Country_name, City_name) values ('Malta', 'Luqa');
insert into CITY (Country_name, City_name) values ('Mali', 'Nara');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Pulau Pinang');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Melaka');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Kuala Lumpur');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Johor Bahru');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Ipoh');
insert into CITY (Country_name, City_name) values ('Malawi', 'Mangochi');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Арачиново');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Ilinden');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Gurgurnica');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Desovo');
insert into CITY (Country_name, City_name) values ('Macao', 'Macau');
insert into CITY (Country_name, City_name) values ('Luxembourg', 'Waldbredimus');
insert into CITY (Country_name, City_name) values ('Libya', 'Tarhuna');
insert into CITY (Country_name, City_name) values ('Lebanon', 'Marjayoûn');
insert into CITY (Country_name, City_name) values ('Latvia', 'Ādaži');
insert into CITY (Country_name, City_name) values ('Laos', 'Pakxé');
insert into CITY (Country_name, City_name) values ('Kyrgyzstan', 'Bazar-Korgon');
insert into CITY (Country_name, City_name) values ('Kenya', 'Nanyuki');
insert into CITY (Country_name, City_name) values ('Kenya', 'Nairobi');
insert into CITY (Country_name, City_name) values ('Kenya', 'Maralal');
insert into CITY (Country_name, City_name) values ('Kazakhstan', 'Zhezqazghan');
insert into CITY (Country_name, City_name) values ('Kazakhstan', 'Shar');
insert into CITY (Country_name, City_name) values ('Kazakhstan', 'Komsomolets');
insert into CITY (Country_name, City_name) values ('Japan', 'Yamazakichō-nakabirose');
insert into CITY (Country_name, City_name) values ('Japan', 'Tsu-shi');
insert into CITY (Country_name, City_name) values ('Japan', 'Tsukawaki');
insert into CITY (Country_name, City_name) values ('Japan', 'Tondabayashichō');
insert into CITY (Country_name, City_name) values ('Japan', 'Tanabe');
insert into CITY (Country_name, City_name) values ('Japan', 'Satte');
insert into CITY (Country_name, City_name) values ('Japan', 'Rumoi');
insert into CITY (Country_name, City_name) values ('Japan', 'Oyama');
insert into CITY (Country_name, City_name) values ('Japan', 'Ōtsuchi');
insert into CITY (Country_name, City_name) values ('Japan', 'Ōkuchi');
insert into CITY (Country_name, City_name) values ('Japan', 'Ōdate');
insert into CITY (Country_name, City_name) values ('Japan', 'Obanazawa');
insert into CITY (Country_name, City_name) values ('Japan', 'Nikkō');
insert into CITY (Country_name, City_name) values ('Japan', 'Nanao');
insert into CITY (Country_name, City_name) values ('Japan', 'Nagareyama');
insert into CITY (Country_name, City_name) values ('Japan', 'Kuroiso');
insert into CITY (Country_name, City_name) values ('Japan', 'Kobayashi');
insert into CITY (Country_name, City_name) values ('Japan', 'Kamogatachō-kamogata');
insert into CITY (Country_name, City_name) values ('Japan', 'Futtsu');
insert into CITY (Country_name, City_name) values ('Japan', 'Fuchūchō');
insert into CITY (Country_name, City_name) values ('Jamaica', 'Stony Hill');
insert into CITY (Country_name, City_name) values ('Jamaica', 'Point Hill');
insert into CITY (Country_name, City_name) values ('Ivory Coast', 'Mankono');
insert into CITY (Country_name, City_name) values ('Ivory Coast', 'Biankouma');
insert into CITY (Country_name, City_name) values ('Ivory Coast', 'Bangolo');
insert into CITY (Country_name, City_name) values ('Italy', 'Villanova');
insert into CITY (Country_name, City_name) values ('Italy', 'Padova');
insert into CITY (Country_name, City_name) values ('Italy', 'Laspezia');
insert into CITY (Country_name, City_name) values ('Italy', 'Bologna');
insert into CITY (Country_name, City_name) values ('Israel', 'Kfar NaOranim');
insert into CITY (Country_name, City_name) values ('Israel', 'Kafr Mandā');
insert into CITY (Country_name, City_name) values ('Israel', 'Herzliyya');
insert into CITY (Country_name, City_name) values ('Israel', 'Deir Ḥannā');
insert into CITY (Country_name, City_name) values ('Ireland', 'Tralee');
insert into CITY (Country_name, City_name) values ('Ireland', 'Prosperous');
insert into CITY (Country_name, City_name) values ('Ireland', 'Cloyne');
insert into CITY (Country_name, City_name) values ('Iran', 'Zehak');
insert into CITY (Country_name, City_name) values ('Iran', 'Tonekābon');
insert into CITY (Country_name, City_name) values ('Iran', 'Shāhīn Dezh');
insert into CITY (Country_name, City_name) values ('Iran', 'Khalkhāl');
insert into CITY (Country_name, City_name) values ('Iran', 'Khalīlābād');
insert into CITY (Country_name, City_name) values ('Iran', 'Kermānshāh');
insert into CITY (Country_name, City_name) values ('Iran', 'Gālīkesh');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Woto');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wonosari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wiyayu Barat');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Weda');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wailolong');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Utarapasar');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Umbulan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Turi');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Toroy');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tempeh Tengah');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tekik Wetan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tanjung Timur');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tangkanpulit');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tanggungrejo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tambarangan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tambakrejo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Talok');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Takengon');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tagog');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sumberpandan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sukorejo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sukabumi');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sugihwaras');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sudimanik');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Srabah');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Singajaya');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sere');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sapeken');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Rote');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Riangbaring');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Rancapeundey');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Puncaktugu');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Puncakbaru');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pulosari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pondokkaha Kelod');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pledo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Plaju');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pendawanbaru');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pasembon');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Panjir');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pangawaren');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Oeleon');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Nusaherang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ngulahan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Mranggen');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Matangpayang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Margasari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Malati');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Lokatadho');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Lewograran');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Laka');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kudang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kotakan Selatan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kiukasen');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ketawang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kertosari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kebonan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kawangu Satu');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Katur');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Karangdalam');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kalidawe');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kalabahi');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jayawangi');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jatirejo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jajaway');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gunungputri');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gondanglegi Wetan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gandekan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gamping Lor');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Dayeuhluhur');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cisasak');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cisadap');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cipanas');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cipadung');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cimahi');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cikulina');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ciketak');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cijeungjing Kaler');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cihampelas');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cigintung');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ciemas');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cibunar');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cangkuang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bungur');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Blokdesa Situgede');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Belanting');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Banjar Yehsatang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Banjar Pangkungkarung Kangin');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Babakan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Alukama');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Aliuroba');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Alasmalang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ajung');
insert into CITY (Country_name, City_name) values ('Hungary', 'Győr');
insert into CITY (Country_name, City_name) values ('Honduras', 'Villa Nueva');
insert into CITY (Country_name, City_name) values ('Honduras', 'Santa Rosa de Copán');
insert into CITY (Country_name, City_name) values ('Honduras', 'San Jerónimo');
insert into CITY (Country_name, City_name) values ('Honduras', 'La Jutosa');
insert into CITY (Country_name, City_name) values ('Honduras', 'Jocón');
insert into CITY (Country_name, City_name) values ('Honduras', 'Iralaya');
insert into CITY (Country_name, City_name) values ('Haiti', 'Carrefour');
insert into CITY (Country_name, City_name) values ('Guinea-Bissau', 'Bissau');
insert into CITY (Country_name, City_name) values ('Guatemala', 'San Pedro Sacatepéquez');
insert into CITY (Country_name, City_name) values ('Guatemala', 'Lívingston');
insert into CITY (Country_name, City_name) values ('Greenland', 'Narsaq');
insert into CITY (Country_name, City_name) values ('Greece', 'Xylókastro');
insert into CITY (Country_name, City_name) values ('Greece', 'Xylaganí');
insert into CITY (Country_name, City_name) values ('Greece', 'Xinó Neró');
insert into CITY (Country_name, City_name) values ('Greece', 'Tílisos');
insert into CITY (Country_name, City_name) values ('Greece', 'Sérvia');
insert into CITY (Country_name, City_name) values ('Greece', 'Rodhítsa');
insert into CITY (Country_name, City_name) values ('Greece', 'Profítis Ilías');
insert into CITY (Country_name, City_name) values ('Greece', 'Pelópion');
insert into CITY (Country_name, City_name) values ('Greece', 'Megáli Khóra');
insert into CITY (Country_name, City_name) values ('Greece', 'Makrochóri');
insert into CITY (Country_name, City_name) values ('Greece', 'Kynopiástes');
insert into CITY (Country_name, City_name) values ('Greece', 'Kallithéa');
insert into CITY (Country_name, City_name) values ('Greece', 'Examília');
insert into CITY (Country_name, City_name) values ('Greece', 'Asíni');
insert into CITY (Country_name, City_name) values ('Ghana', 'Ho');
insert into CITY (Country_name, City_name) values ('Ghana', 'Duayaw Nkwanta');
insert into CITY (Country_name, City_name) values ('Germany', 'Essen');
insert into CITY (Country_name, City_name) values ('Germany', 'Bochum');
insert into CITY (Country_name, City_name) values ('Germany', 'Berlin');
insert into CITY (Country_name, City_name) values ('Georgia', 'Dmanisi');
insert into CITY (Country_name, City_name) values ('France', 'Villeneuve-sur-Lot');
insert into CITY (Country_name, City_name) values ('France', 'Villefontaine');
insert into CITY (Country_name, City_name) values ('France', 'Valence');
insert into CITY (Country_name, City_name) values ('France', 'Thiais');
insert into CITY (Country_name, City_name) values ('France', 'Tarbes');
insert into CITY (Country_name, City_name) values ('France', 'Saint-Pierre-des-Corps');
insert into CITY (Country_name, City_name) values ('France', 'Saint-Gaudens');
insert into CITY (Country_name, City_name) values ('France', 'Pont-à-Mousson');
insert into CITY (Country_name, City_name) values ('France', 'Paris La Défense');
insert into CITY (Country_name, City_name) values ('France', 'Paris 04');
insert into CITY (Country_name, City_name) values ('France', 'Nîmes');
insert into CITY (Country_name, City_name) values ('France', 'Nice');
insert into CITY (Country_name, City_name) values ('France', 'Montluel');
insert into CITY (Country_name, City_name) values ('France', 'Marcq-en-Barœul');
insert into CITY (Country_name, City_name) values ('France', 'Lille');
insert into CITY (Country_name, City_name) values ('France', 'Goussainville');
insert into CITY (Country_name, City_name) values ('France', 'Draguignan');
insert into CITY (Country_name, City_name) values ('France', 'Digne-les-Bains');
insert into CITY (Country_name, City_name) values ('France', 'Compiègne');
insert into CITY (Country_name, City_name) values ('France', 'Bourgoin-Jallieu');
insert into CITY (Country_name, City_name) values ('France', 'Bordeaux');
insert into CITY (Country_name, City_name) values ('France', 'Blois');
insert into CITY (Country_name, City_name) values ('France', 'Béziers');
insert into CITY (Country_name, City_name) values ('France', 'Aubagne');
insert into CITY (Country_name, City_name) values ('France', 'Ajaccio');
insert into CITY (Country_name, City_name) values ('Finland', 'Utsjoki');
insert into CITY (Country_name, City_name) values ('Finland', 'Pyhäselkä');
insert into CITY (Country_name, City_name) values ('Finland', 'Pyhäsalmi');
insert into CITY (Country_name, City_name) values ('Finland', 'Loimaan Kunta');
insert into CITY (Country_name, City_name) values ('Finland', 'Kouvola');
insert into CITY (Country_name, City_name) values ('Finland', 'Ilmajoki');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Kombolcha');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Kibre Mengist');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Huruta');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Hawassa');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Hāgere Hiywet');
insert into CITY (Country_name, City_name) values ('Estonia', 'Võhma');
insert into CITY (Country_name, City_name) values ('Estonia', 'Tabivere');
insert into CITY (Country_name, City_name) values ('El Salvador', 'Usulután');
insert into CITY (Country_name, City_name) values ('El Salvador', 'Nueva Guadalupe');
insert into CITY (Country_name, City_name) values ('Egypt', 'Banhā');
insert into CITY (Country_name, City_name) values ('Egypt', 'Al Ḩawāmidīyah');
insert into CITY (Country_name, City_name) values ('Ecuador', 'Loja');
insert into CITY (Country_name, City_name) values ('East Timor', 'Liquica');
insert into CITY (Country_name, City_name) values ('Dominican Republic', 'Villa Consuelo');
insert into CITY (Country_name, City_name) values ('Dominican Republic', 'Santo Domingo Oeste');
insert into CITY (Country_name, City_name) values ('Dominican Republic', 'Santa Cruz de El Seibo');
insert into CITY (Country_name, City_name) values ('Dominican Republic', 'Sabana Iglesia');
insert into CITY (Country_name, City_name) values ('Djibouti', 'Ḏânan');
insert into CITY (Country_name, City_name) values ('Denmark', 'København');
insert into CITY (Country_name, City_name) values ('Democratic Republic of the Congo', 'Yangambi');
insert into CITY (Country_name, City_name) values ('Democratic Republic of the Congo', 'Kananga');
insert into CITY (Country_name, City_name) values ('Democratic Republic of the Congo', 'Kambove');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Žlutice');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Vysočany');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Velké Karlovice');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Údlice');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Třešť');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Sokolnice');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Řečany nad Labem');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Rájec-Jestřebí');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Poděbrady');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Klatovy');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Jindřichův Hradec');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Holýšov');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Dvůr Králové nad Labem');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Brniště');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Březová nad Svitavou');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Blatná');
insert into CITY (Country_name, City_name) values ('Cuba', 'San Luis');
insert into CITY (Country_name, City_name) values ('Cuba', 'Pedro Betancourt');
insert into CITY (Country_name, City_name) values ('Cuba', 'Boyeros');
insert into CITY (Country_name, City_name) values ('Croatia', 'Osekovo');
insert into CITY (Country_name, City_name) values ('Croatia', 'Kašina');
insert into CITY (Country_name, City_name) values ('Croatia', 'Feričanci');
insert into CITY (Country_name, City_name) values ('Croatia', 'Bobota');
insert into CITY (Country_name, City_name) values ('Colombia', 'Sincé');
insert into CITY (Country_name, City_name) values ('Colombia', 'Sibaté');
insert into CITY (Country_name, City_name) values ('Colombia', 'Rovira');
insert into CITY (Country_name, City_name) values ('Colombia', 'Mercaderes');
insert into CITY (Country_name, City_name) values ('Colombia', 'La Virginia');
insert into CITY (Country_name, City_name) values ('Colombia', 'La Vega');
insert into CITY (Country_name, City_name) values ('Colombia', 'Juradó');
insert into CITY (Country_name, City_name) values ('Colombia', 'Hobo');
insert into CITY (Country_name, City_name) values ('Colombia', 'El Carmen');
insert into CITY (Country_name, City_name) values ('Colombia', 'Cartagena');
insert into CITY (Country_name, City_name) values ('Colombia', 'Bagadó');
insert into CITY (Country_name, City_name) values ('Colombia', 'Arbeláez');
insert into CITY (Country_name, City_name) values ('China', 'Zhuxi');
insert into CITY (Country_name, City_name) values ('China', 'Zhusha');
insert into CITY (Country_name, City_name) values ('China', 'Zhourui');
insert into CITY (Country_name, City_name) values ('China', 'Zhongxi');
insert into CITY (Country_name, City_name) values ('China', 'Zhaowanzhuang');
insert into CITY (Country_name, City_name) values ('China', 'Zhangjiagang');
insert into CITY (Country_name, City_name) values ('China', 'Zhangjia');
insert into CITY (Country_name, City_name) values ('China', 'Zhanggongmiao');
insert into CITY (Country_name, City_name) values ('China', 'Zengtian');
insert into CITY (Country_name, City_name) values ('China', 'Yunlu');
insert into CITY (Country_name, City_name) values ('China', 'Yuewan');
insert into CITY (Country_name, City_name) values ('China', 'Yuetang');
insert into CITY (Country_name, City_name) values ('China', 'Yuanping');
insert into CITY (Country_name, City_name) values ('China', 'Yuanjiazhuang');
insert into CITY (Country_name, City_name) values ('China', 'Yonghe');
insert into CITY (Country_name, City_name) values ('China', 'Yonggu');
insert into CITY (Country_name, City_name) values ('China', 'Yeping');
insert into CITY (Country_name, City_name) values ('China', 'Yaozhanzi');
insert into CITY (Country_name, City_name) values ('China', 'Yanghu');
insert into CITY (Country_name, City_name) values ('China', 'Xuwei');
insert into CITY (Country_name, City_name) values ('China', 'Xundian');
insert into CITY (Country_name, City_name) values ('China', 'Xufeng');
insert into CITY (Country_name, City_name) values ('China', 'Xiongjia');
insert into CITY (Country_name, City_name) values ('China', 'Xiongbei');
insert into CITY (Country_name, City_name) values ('China', 'Xinyang');
insert into CITY (Country_name, City_name) values ('China', 'Xinsheng');
insert into CITY (Country_name, City_name) values ('China', 'Xingshou');
insert into CITY (Country_name, City_name) values ('China', 'Xinchong');
insert into CITY (Country_name, City_name) values ('China', 'Xibali');
insert into CITY (Country_name, City_name) values ('China', 'Xiaohekou');
insert into CITY (Country_name, City_name) values ('China', 'Xiaochi');
insert into CITY (Country_name, City_name) values ('China', 'Xianshuigu');
insert into CITY (Country_name, City_name) values ('China', 'Wuxing');
insert into CITY (Country_name, City_name) values ('China', 'Wushi');
insert into CITY (Country_name, City_name) values ('China', 'Wuquan');
insert into CITY (Country_name, City_name) values ('China', 'Wuqiao');
insert into CITY (Country_name, City_name) values ('China', 'Wukeshu');
insert into CITY (Country_name, City_name) values ('China', 'Weizheng');
insert into CITY (Country_name, City_name) values ('China', 'Wanglinkou');
insert into CITY (Country_name, City_name) values ('China', 'Wangdain');
insert into CITY (Country_name, City_name) values ('China', 'Tunguang');
insert into CITY (Country_name, City_name) values ('China', 'Tuanlin');
insert into CITY (Country_name, City_name) values ('China', 'Tonghu');
insert into CITY (Country_name, City_name) values ('China', 'Tianzhu');
insert into CITY (Country_name, City_name) values ('China', 'Tacheng');
insert into CITY (Country_name, City_name) values ('China', 'Songjiang');
insert into CITY (Country_name, City_name) values ('China', 'Shuangqiaoping');
insert into CITY (Country_name, City_name) values ('China', 'Shuangqiao');
insert into CITY (Country_name, City_name) values ('China', 'Shuanglong');
insert into CITY (Country_name, City_name) values ('China', 'Shuanghejiedao');
insert into CITY (Country_name, City_name) values ('China', 'Shizi');
insert into CITY (Country_name, City_name) values ('China', 'Shixi');
insert into CITY (Country_name, City_name) values ('China', 'Shanxi');
insert into CITY (Country_name, City_name) values ('China', 'Shanhou');
insert into CITY (Country_name, City_name) values ('China', 'Shangyang');
insert into CITY (Country_name, City_name) values ('China', 'Shangrao');
insert into CITY (Country_name, City_name) values ('China', 'Shangde');
insert into CITY (Country_name, City_name) values ('China', 'Sanshandao');
insert into CITY (Country_name, City_name) values ('China', 'Sanjia');
insert into CITY (Country_name, City_name) values ('China', 'Renhe');
insert into CITY (Country_name, City_name) values ('China', 'Ralung');
insert into CITY (Country_name, City_name) values ('China', 'Quwa');
insert into CITY (Country_name, City_name) values ('China', 'Qingliu');
insert into CITY (Country_name, City_name) values ('China', 'Qilong');
insert into CITY (Country_name, City_name) values ('China', 'Pingshi');
insert into CITY (Country_name, City_name) values ('China', 'Pingshan');
insert into CITY (Country_name, City_name) values ('China', 'Pingfeng');
insert into CITY (Country_name, City_name) values ('China', 'Penglai');
insert into CITY (Country_name, City_name) values ('China', 'Ningtang');
insert into CITY (Country_name, City_name) values ('China', 'Nanyang');
insert into CITY (Country_name, City_name) values ('China', 'Nantang');
insert into CITY (Country_name, City_name) values ('China', 'Nanshi');
insert into CITY (Country_name, City_name) values ('China', 'Nankengzi');
insert into CITY (Country_name, City_name) values ('China', 'Nanchangshan');
insert into CITY (Country_name, City_name) values ('China', 'Mushu');
insert into CITY (Country_name, City_name) values ('China', 'Motge');
insert into CITY (Country_name, City_name) values ('China', 'Miaofengshan');
insert into CITY (Country_name, City_name) values ('China', 'Mengjia');
insert into CITY (Country_name, City_name) values ('China', 'Mazongling');
insert into CITY (Country_name, City_name) values ('China', 'Matou');
insert into CITY (Country_name, City_name) values ('China', 'Matangshan');
insert into CITY (Country_name, City_name) values ('China', 'Maoping');
insert into CITY (Country_name, City_name) values ('China', 'Luyang');
insert into CITY (Country_name, City_name) values ('China', 'Lukou');
insert into CITY (Country_name, City_name) values ('China', 'Longtanhe');
insert into CITY (Country_name, City_name) values ('China', 'Longfeng');
insert into CITY (Country_name, City_name) values ('China', 'Liuzhi');
insert into CITY (Country_name, City_name) values ('China', 'Liushikou');
insert into CITY (Country_name, City_name) values ('China', 'Lintingkou');
insert into CITY (Country_name, City_name) values ('China', 'Lingmen');
insert into CITY (Country_name, City_name) values ('China', 'Lingbei');
insert into CITY (Country_name, City_name) values ('China', 'Lincheng');
insert into CITY (Country_name, City_name) values ('China', 'Liaoyang');
insert into CITY (Country_name, City_name) values ('China', 'Lianyun');
insert into CITY (Country_name, City_name) values ('China', 'Lianran');
insert into CITY (Country_name, City_name) values ('China', 'Laxiong');
insert into CITY (Country_name, City_name) values ('China', 'Kanshi');
insert into CITY (Country_name, City_name) values ('China', 'Jiuzhou');
insert into CITY (Country_name, City_name) values ('China', 'Jiumen');
insert into CITY (Country_name, City_name) values ('China', 'Jiuhua');
insert into CITY (Country_name, City_name) values ('China', 'Jinzao');
insert into CITY (Country_name, City_name) values ('China', 'Jinsha');
insert into CITY (Country_name, City_name) values ('China', 'Jinjing');
insert into CITY (Country_name, City_name) values ('China', 'Jinchang');
insert into CITY (Country_name, City_name) values ('China', 'Jimusa’er');
insert into CITY (Country_name, City_name) values ('China', 'Jichang');
insert into CITY (Country_name, City_name) values ('China', 'Jiazi');
insert into CITY (Country_name, City_name) values ('China', 'Jiaqu');
insert into CITY (Country_name, City_name) values ('China', 'Jianxincun');
insert into CITY (Country_name, City_name) values ('China', 'Jiangjia');
insert into CITY (Country_name, City_name) values ('China', 'Jiacun');
insert into CITY (Country_name, City_name) values ('China', 'Huomachong');
insert into CITY (Country_name, City_name) values ('China', 'Hulu');
insert into CITY (Country_name, City_name) values ('China', 'Hujiaying');
insert into CITY (Country_name, City_name) values ('China', 'Huixing');
insert into CITY (Country_name, City_name) values ('China', 'Huazangsi');
insert into CITY (Country_name, City_name) values ('China', 'Huangshui');
insert into CITY (Country_name, City_name) values ('China', 'Huangqi');
insert into CITY (Country_name, City_name) values ('China', 'Huangjing');
insert into CITY (Country_name, City_name) values ('China', 'Huanghua');
insert into CITY (Country_name, City_name) values ('China', 'Huancheng');
insert into CITY (Country_name, City_name) values ('China', 'Huamu');
insert into CITY (Country_name, City_name) values ('China', 'Huacao');
insert into CITY (Country_name, City_name) values ('China', 'Hongxing');
insert into CITY (Country_name, City_name) values ('China', 'Hongtang');
insert into CITY (Country_name, City_name) values ('China', 'Heping');
insert into CITY (Country_name, City_name) values ('China', 'Hengqu');
insert into CITY (Country_name, City_name) values ('China', 'Hekou');
insert into CITY (Country_name, City_name) values ('China', 'Hejia');
insert into CITY (Country_name, City_name) values ('China', 'Heicheng');
insert into CITY (Country_name, City_name) values ('China', 'Haokou');
insert into CITY (Country_name, City_name) values ('China', 'Hanlin');
insert into CITY (Country_name, City_name) values ('China', 'Haiyu');
insert into CITY (Country_name, City_name) values ('China', 'Haibeitou');
insert into CITY (Country_name, City_name) values ('China', 'Guhuai');
insert into CITY (Country_name, City_name) values ('China', 'Guandi');
insert into CITY (Country_name, City_name) values ('China', 'Gegu');
insert into CITY (Country_name, City_name) values ('China', 'Gaoqiao');
insert into CITY (Country_name, City_name) values ('China', 'Gaoliang');
insert into CITY (Country_name, City_name) values ('China', 'Gangnan');
insert into CITY (Country_name, City_name) values ('China', 'Gangmei');
insert into CITY (Country_name, City_name) values ('China', 'Fuxing');
insert into CITY (Country_name, City_name) values ('China', 'Fushun');
insert into CITY (Country_name, City_name) values ('China', 'Fenggao');
insert into CITY (Country_name, City_name) values ('China', 'Erping');
insert into CITY (Country_name, City_name) values ('China', 'Erhe');
insert into CITY (Country_name, City_name) values ('China', 'Duma');
insert into CITY (Country_name, City_name) values ('China', 'Dugu');
insert into CITY (Country_name, City_name) values ('China', 'Dongzhaogezhuang');
insert into CITY (Country_name, City_name) values ('China', 'Dongxi');
insert into CITY (Country_name, City_name) values ('China', 'Donglinxi');
insert into CITY (Country_name, City_name) values ('China', 'Donggang');
insert into CITY (Country_name, City_name) values ('China', 'Dong’ao');
insert into CITY (Country_name, City_name) values ('China', 'Diaoling');
insert into CITY (Country_name, City_name) values ('China', 'Dalonghua');
insert into CITY (Country_name, City_name) values ('China', 'Daixi');
insert into CITY (Country_name, City_name) values ('China', 'Choushui');
insert into CITY (Country_name, City_name) values ('China', 'Chongru');
insert into CITY (Country_name, City_name) values ('China', 'Chengqiao');
insert into CITY (Country_name, City_name) values ('China', 'Chengjiao Chengguanzhen');
insert into CITY (Country_name, City_name) values ('China', 'Chengdong');
insert into CITY (Country_name, City_name) values ('China', 'Changpo');
insert into CITY (Country_name, City_name) values ('China', 'Changping');
insert into CITY (Country_name, City_name) values ('China', 'Chaka');
insert into CITY (Country_name, City_name) values ('China', 'Chagang');
insert into CITY (Country_name, City_name) values ('China', 'Caotang');
insert into CITY (Country_name, City_name) values ('China', 'Caojia');
insert into CITY (Country_name, City_name) values ('China', 'Bozhou');
insert into CITY (Country_name, City_name) values ('China', 'Bohai');
insert into CITY (Country_name, City_name) values ('China', 'Bieligutai');
insert into CITY (Country_name, City_name) values ('China', 'Beizhakou');
insert into CITY (Country_name, City_name) values ('China', 'Beixinjie');
insert into CITY (Country_name, City_name) values ('China', 'Beiqijia');
insert into CITY (Country_name, City_name) values ('China', 'Beijiang');
insert into CITY (Country_name, City_name) values ('China', 'Beigang');
insert into CITY (Country_name, City_name) values ('China', 'Bashan');
insert into CITY (Country_name, City_name) values ('China', 'Baoshui');
insert into CITY (Country_name, City_name) values ('China', 'Baoshi');
insert into CITY (Country_name, City_name) values ('China', 'Baoping');
insert into CITY (Country_name, City_name) values ('China', 'Banqiaodian');
insert into CITY (Country_name, City_name) values ('China', 'Baisha');
insert into CITY (Country_name, City_name) values ('China', 'Anrong');
insert into CITY (Country_name, City_name) values ('Chile', 'Illapel');
insert into CITY (Country_name, City_name) values ('Chile', 'Cochrane');
insert into CITY (Country_name, City_name) values ('Chad', 'Fada');
insert into CITY (Country_name, City_name) values ('Chad', 'Am Djarass');
insert into CITY (Country_name, City_name) values ('Canada', 'Saskatoon');
insert into CITY (Country_name, City_name) values ('Canada', 'Orangeville');
insert into CITY (Country_name, City_name) values ('Canada', 'Morris');
insert into CITY (Country_name, City_name) values ('Canada', 'Melville');
insert into CITY (Country_name, City_name) values ('Canada', 'Les Cèdres');
insert into CITY (Country_name, City_name) values ('Canada', 'Ladner');
insert into CITY (Country_name, City_name) values ('Canada', 'Lac-Brome');
insert into CITY (Country_name, City_name) values ('Canada', 'Dollard-Des Ormeaux');
insert into CITY (Country_name, City_name) values ('Canada', 'Bonavista');
insert into CITY (Country_name, City_name) values ('Cameroon', 'Dizangué');
insert into CITY (Country_name, City_name) values ('Cameroon', 'Buea');
insert into CITY (Country_name, City_name) values ('Cameroon', 'Bekondo');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Shipka');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Sapareva Banya');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Kula');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Asen');
insert into CITY (Country_name, City_name) values ('Brazil', 'Trairi');
insert into CITY (Country_name, City_name) values ('Brazil', 'Sousa');
insert into CITY (Country_name, City_name) values ('Brazil', 'Soledade');
insert into CITY (Country_name, City_name) values ('Brazil', 'Sinop');
insert into CITY (Country_name, City_name) values ('Brazil', 'Santiago');
insert into CITY (Country_name, City_name) values ('Brazil', 'Rio Grande da Serra');
insert into CITY (Country_name, City_name) values ('Brazil', 'Queimados');
insert into CITY (Country_name, City_name) values ('Brazil', 'Porto Calvo');
insert into CITY (Country_name, City_name) values ('Brazil', 'Passos');
insert into CITY (Country_name, City_name) values ('Brazil', 'Muriaé');
insert into CITY (Country_name, City_name) values ('Brazil', 'Monte Alegre');
insert into CITY (Country_name, City_name) values ('Brazil', 'Mococa');
insert into CITY (Country_name, City_name) values ('Brazil', 'Mirandopólis');
insert into CITY (Country_name, City_name) values ('Brazil', 'Mendes');
insert into CITY (Country_name, City_name) values ('Brazil', 'Medeiros Neto');
insert into CITY (Country_name, City_name) values ('Brazil', 'Matozinhos');
insert into CITY (Country_name, City_name) values ('Brazil', 'Marília');
insert into CITY (Country_name, City_name) values ('Brazil', 'Maracás');
insert into CITY (Country_name, City_name) values ('Brazil', 'Limoeiro do Norte');
insert into CITY (Country_name, City_name) values ('Brazil', 'Laranjeiras');
insert into CITY (Country_name, City_name) values ('Brazil', 'Lajedo');
insert into CITY (Country_name, City_name) values ('Brazil', 'Ladário');
insert into CITY (Country_name, City_name) values ('Brazil', 'Itaporanga');
insert into CITY (Country_name, City_name) values ('Brazil', 'Itacoatiara');
insert into CITY (Country_name, City_name) values ('Brazil', 'Itabaianinha');
insert into CITY (Country_name, City_name) values ('Brazil', 'Herval');
insert into CITY (Country_name, City_name) values ('Brazil', 'Guaiúba');
insert into CITY (Country_name, City_name) values ('Brazil', 'Gravatá');
insert into CITY (Country_name, City_name) values ('Brazil', 'Francisco Morato');
insert into CITY (Country_name, City_name) values ('Brazil', 'Flores da Cunha');
insert into CITY (Country_name, City_name) values ('Brazil', 'Codó');
insert into CITY (Country_name, City_name) values ('Brazil', 'Chapecó');
insert into CITY (Country_name, City_name) values ('Brazil', 'Campo Verde');
insert into CITY (Country_name, City_name) values ('Brazil', 'Caldas Novas');
insert into CITY (Country_name, City_name) values ('Brazil', 'Cachoeira');
insert into CITY (Country_name, City_name) values ('Brazil', 'Caçador');
insert into CITY (Country_name, City_name) values ('Brazil', 'Buritama');
insert into CITY (Country_name, City_name) values ('Brazil', 'Bela Vista do Paraíso');
insert into CITY (Country_name, City_name) values ('Brazil', 'Bastos');
insert into CITY (Country_name, City_name) values ('Brazil', 'Arauá');
insert into CITY (Country_name, City_name) values ('Brazil', 'Águas Formosas');
insert into CITY (Country_name, City_name) values ('Botswana', 'Manyana');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Radišići');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Orahovica Donja');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Ljubuški');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Ilići');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Hiseti');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Gnojnica');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Čelinac');
insert into CITY (Country_name, City_name) values ('Bonaire, Saint Eustatius and Saba ', 'Dorp Antriol');
insert into CITY (Country_name, City_name) values ('Bolivia', 'Huatajata');
insert into CITY (Country_name, City_name) values ('Belgium', 'Ath');
insert into CITY (Country_name, City_name) values ('Belarus', 'Zhyrovichy');
insert into CITY (Country_name, City_name) values ('Belarus', 'Vyerkhnyadzvinsk');
insert into CITY (Country_name, City_name) values ('Belarus', 'Palykavichy Pyershyya');
insert into CITY (Country_name, City_name) values ('Bangladesh', 'Nawābganj');
insert into CITY (Country_name, City_name) values ('Bangladesh', 'Morrelgonj');
insert into CITY (Country_name, City_name) values ('Bangladesh', 'Habiganj');
insert into CITY (Country_name, City_name) values ('Bangladesh', 'Gaurnadi');
insert into CITY (Country_name, City_name) values ('Azerbaijan', 'Verkhniy Dashkesan');
insert into CITY (Country_name, City_name) values ('Australia', 'Sydney');
insert into CITY (Country_name, City_name) values ('Armenia', 'Dashtavan');
insert into CITY (Country_name, City_name) values ('Argentina', 'San José de Jáchal');
insert into CITY (Country_name, City_name) values ('Argentina', 'Pampa del Infierno');
insert into CITY (Country_name, City_name) values ('Argentina', 'Naschel');
insert into CITY (Country_name, City_name) values ('Argentina', 'Miramar');
insert into CITY (Country_name, City_name) values ('Argentina', 'Mariano Moreno');
insert into CITY (Country_name, City_name) values ('Argentina', 'Laguna Paiva');
insert into CITY (Country_name, City_name) values ('Argentina', 'Cinco Saltos');
insert into CITY (Country_name, City_name) values ('Argentina', 'Capitán Solari');
insert into CITY (Country_name, City_name) values ('American Samoa', 'Ta`ū');
insert into CITY (Country_name, City_name) values ('Albania', 'Shupenzë');
insert into CITY (Country_name, City_name) values ('Albania', 'Orosh');
insert into CITY (Country_name, City_name) values ('Aland Islands', 'Vårdö');
insert into CITY (Country_name, City_name) values ('Afghanistan', 'Panjāb');
insert into CITY (Country_name, City_name) values ('Afghanistan', 'Dū Qal‘ah');
insert into CITY (Country_name, City_name) values ('Afghanistan', 'Barakī Barak');
