set nocount on;
insert into STADIUM (Stadium_name, Capacity) values ('YES TO TOMATOES ACNE CONTROL GEL CLEANSER', 49000);
insert into STADIUM (Stadium_name, Capacity) values ('White Alder', 14500);
insert into STADIUM (Stadium_name, Capacity) values ('Wasp hymenoptera venom Venomil Maintenance', 22000);
insert into STADIUM (Stadium_name, Capacity) values ('Warfarin Sodium', 20500);
insert into STADIUM (Stadium_name, Capacity) values ('Visine Tears', 25000);
insert into STADIUM (Stadium_name, Capacity) values ('Velivet', 38500);
insert into STADIUM (Stadium_name, Capacity) values ('Vaporizing Chest Rub', 12500);
insert into STADIUM (Stadium_name, Capacity) values ('Vanilla Cupcake Antibacterial Hand Sanitizer', 41500);
insert into STADIUM (Stadium_name, Capacity) values ('Triple Vitamin Drops with Fluoride', 47000);
insert into STADIUM (Stadium_name, Capacity) values ('TREE OF HEAVEN POLLEN', 47500);
insert into STADIUM (Stadium_name, Capacity) values ('THALITONE', 23000);
insert into STADIUM (Stadium_name, Capacity) values ('Stratuscare Glycerin Laxative Pediatric', 7500);
insert into STADIUM (Stadium_name, Capacity) values ('Standardized Bermuda Grass Pollen', 30500);
insert into STADIUM (Stadium_name, Capacity) values ('Spironolactone', 46000);
insert into STADIUM (Stadium_name, Capacity) values ('Solar Sense Zany Zinc SPF 50 - Blue', 41000);
insert into STADIUM (Stadium_name, Capacity) values ('SNAIL THERAPY PACT', 20500);
insert into STADIUM (Stadium_name, Capacity) values ('smart sense pain relief', 31500);
insert into STADIUM (Stadium_name, Capacity) values ('simvastatin', 30000);
insert into STADIUM (Stadium_name, Capacity) values ('Scallop', 24500);
insert into STADIUM (Stadium_name, Capacity) values ('Pyridostigmine Bromide', 49500);
insert into STADIUM (Stadium_name, Capacity) values ('PROMETHAZINE HYDROCHLORIDE', 36500);
insert into STADIUM (Stadium_name, Capacity) values ('ProCoMycin', 45500);
insert into STADIUM (Stadium_name, Capacity) values ('Pramipexole Dihydrochloride', 12000);
insert into STADIUM (Stadium_name, Capacity) values ('Potassium Chloride in Dextrose and Sodium Chloride', 35500);
insert into STADIUM (Stadium_name, Capacity) values ('PHLORIDZIN', 43500);
insert into STADIUM (Stadium_name, Capacity) values ('PERIPLANETA AMERICANA', 46000);
insert into STADIUM (Stadium_name, Capacity) values ('pain relief', 5000);
insert into STADIUM (Stadium_name, Capacity) values ('Oxygen', 8000);
insert into STADIUM (Stadium_name, Capacity) values ('Orange Spice Scented Antibacterial Hand Sanitizer', 18500);
insert into STADIUM (Stadium_name, Capacity) values ('Oral Dent', 23000);
insert into STADIUM (Stadium_name, Capacity) values ('Opcon-A', 38000);
insert into STADIUM (Stadium_name, Capacity) values ('Omeprazole', 8000);
insert into STADIUM (Stadium_name, Capacity) values ('Normosol-R', 5000);
insert into STADIUM (Stadium_name, Capacity) values ('Nitrous Oxide', 23500);
insert into STADIUM (Stadium_name, Capacity) values ('Nitrofurantoin (monohydrate/macrocrystals)', 43500);
insert into STADIUM (Stadium_name, Capacity) values ('NITETIME', 17000);
insert into STADIUM (Stadium_name, Capacity) values ('nicotine polacrilex', 46500);
insert into STADIUM (Stadium_name, Capacity) values ('Nicotine', 5500);
insert into STADIUM (Stadium_name, Capacity) values ('Neutrogena Ultra Sheer Dry Touch', 40000);
insert into STADIUM (Stadium_name, Capacity) values ('Neuro', 7000);
insert into STADIUM (Stadium_name, Capacity) values ('Neuralgia', 41000);
insert into STADIUM (Stadium_name, Capacity) values ('nasal decongestant pe', 29500);
insert into STADIUM (Stadium_name, Capacity) values ('Naproxen Sodium', 9500);
insert into STADIUM (Stadium_name, Capacity) values ('NALTREXONE HYDROCHLORIDE', 17500);
insert into STADIUM (Stadium_name, Capacity) values ('Miconazole 3 Combination Pack', 8500);
insert into STADIUM (Stadium_name, Capacity) values ('Metronidazole', 49500);
insert into STADIUM (Stadium_name, Capacity) values ('Methylphenidate Hydrochloride', 29500);
insert into STADIUM (Stadium_name, Capacity) values ('Metformin Hydrochloride', 12500);
insert into STADIUM (Stadium_name, Capacity) values ('Mary Kay Tinted Lip Balm Sunscreen SPF 15 Mango', 28500);
insert into STADIUM (Stadium_name, Capacity) values ('Lovenox', 6000);
insert into STADIUM (Stadium_name, Capacity) values ('LOreal Paris Visible lift Medium Deep CC Broad Spectrum SPF', 40500);
insert into STADIUM (Stadium_name, Capacity) values ('Lorazepam', 32000);
insert into STADIUM (Stadium_name, Capacity) values ('Lisinopril and Hydrochlorothiazide', 36500);
insert into STADIUM (Stadium_name, Capacity) values ('Lisinopril', 44500);
insert into STADIUM (Stadium_name, Capacity) values ('Lice Complete Kit', 45500);
insert into STADIUM (Stadium_name, Capacity) values ('Lexapro', 48000);
insert into STADIUM (Stadium_name, Capacity) values ('Leucovorin Calcium', 50000);
insert into STADIUM (Stadium_name, Capacity) values ('LBEL', 7500);
insert into STADIUM (Stadium_name, Capacity) values ('Kroger Sport Sunscreen', 49000);
insert into STADIUM (Stadium_name, Capacity) values ('Krebs Stimulator Plus', 30500);
insert into STADIUM (Stadium_name, Capacity) values ('IPKN ARTISTS TOUCH BB 01 LIGHT', 23000);
insert into STADIUM (Stadium_name, Capacity) values ('Instant Hand Sanitizer with Moisturizers Unscented', 9500);
insert into STADIUM (Stadium_name, Capacity) values ('infants pain and fever', 20500);
insert into STADIUM (Stadium_name, Capacity) values ('Ibuprofen', 47000);
insert into STADIUM (Stadium_name, Capacity) values ('Hydroxyzine Hydrochloride', 47000);
insert into STADIUM (Stadium_name, Capacity) values ('Hydrogen Peroxide', 14000);
insert into STADIUM (Stadium_name, Capacity) values ('Humphreys Baby Teething Relief Original', 46500);
insert into STADIUM (Stadium_name, Capacity) values ('Histamine', 29000);
insert into STADIUM (Stadium_name, Capacity) values ('Haloperidol', 30500);
insert into STADIUM (Stadium_name, Capacity) values ('Hackberry Pollen', 40500);
insert into STADIUM (Stadium_name, Capacity) values ('GO TIME', 21500);
insert into STADIUM (Stadium_name, Capacity) values ('Good Sense Antacid', 39000);
insert into STADIUM (Stadium_name, Capacity) values ('GoodSense', 38000);
insert into STADIUM (Stadium_name, Capacity) values ('Ginsamin Memory', 18500);
insert into STADIUM (Stadium_name, Capacity) values ('Gillette Power Beads', 44500);
insert into STADIUM (Stadium_name, Capacity) values ('gemcitabine', 38500);
insert into STADIUM (Stadium_name, Capacity) values ('Gabapentin', 40500);
insert into STADIUM (Stadium_name, Capacity) values ('Fungi Nail Toe and Foot', 41000);
insert into STADIUM (Stadium_name, Capacity) values ('Formica Oxalis', 43500);
insert into STADIUM (Stadium_name, Capacity) values ('Exjade', 36000);
insert into STADIUM (Stadium_name, Capacity) values ('Excedrin', 11000);
insert into STADIUM (Stadium_name, Capacity) values ('Ethambutol Hydrochloride', 10500);
insert into STADIUM (Stadium_name, Capacity) values ('Estring', 24500);
insert into STADIUM (Stadium_name, Capacity) values ('Escitalopram', 5500);
insert into STADIUM (Stadium_name, Capacity) values ('equaline ibuprofen', 32000);
insert into STADIUM (Stadium_name, Capacity) values ('Enalaprilat', 33000);
insert into STADIUM (Stadium_name, Capacity) values ('Ear Care', 15000);
insert into STADIUM (Stadium_name, Capacity) values ('Dry Idea A.Dry Inv.Sol. Antiperspirant Cool Blast', 33000);
insert into STADIUM (Stadium_name, Capacity) values ('DR.G WHITENING BOOSTER AMPLE', 38000);
insert into STADIUM (Stadium_name, Capacity) values ('Doxazosin', 17500);
insert into STADIUM (Stadium_name, Capacity) values ('Diltiazem Hydrochloride', 11000);
insert into STADIUM (Stadium_name, Capacity) values ('Darkleaves Mugwort', 9000);
insert into STADIUM (Stadium_name, Capacity) values ('Cystotone', 27000);
insert into STADIUM (Stadium_name, Capacity) values ('Cyclobenzaprine Hydrochloride', 42500);
insert into STADIUM (Stadium_name, Capacity) values ('CVS Pharmacy', 6000);
insert into STADIUM (Stadium_name, Capacity) values ('CURAD Hydrogen Peroxide', 49000);
insert into STADIUM (Stadium_name, Capacity) values ('Crataegus e fol. et fructus 2 Special Order', 42000);
insert into STADIUM (Stadium_name, Capacity) values ('cooling', 41500);
insert into STADIUM (Stadium_name, Capacity) values ('Codeine Sulfate', 10000);
insert into STADIUM (Stadium_name, Capacity) values ('Cephalexin', 46500);
insert into STADIUM (Stadium_name, Capacity) values ('CEFTRIAXONE', 10500);
insert into STADIUM (Stadium_name, Capacity) values ('CEFPODOXIME PROXETIL', 43000);
insert into STADIUM (Stadium_name, Capacity) values ('CareOne Nitetime Cold Flu Relief', 40500);
insert into STADIUM (Stadium_name, Capacity) values ('CareOne Daytime Cold Flu Relief', 12000);
insert into STADIUM (Stadium_name, Capacity) values ('Canadian Blue Grass', 27500);
insert into STADIUM (Stadium_name, Capacity) values ('BuPROPion Hydrochloride', 36500);
insert into STADIUM (Stadium_name, Capacity) values ('Body', 42500);
insert into STADIUM (Stadium_name, Capacity) values ('berkley and jensen adult tussin dm', 8500);
insert into STADIUM (Stadium_name, Capacity) values ('Baclofen', 7000);
insert into STADIUM (Stadium_name, Capacity) values ('AVAPTA', 37000);
insert into STADIUM (Stadium_name, Capacity) values ('Atorvastatin Calcium', 13000);
insert into STADIUM (Stadium_name, Capacity) values ('Aspirin', 5000);
insert into STADIUM (Stadium_name, Capacity) values ('Antipyrine and Benzocaine', 7000);
insert into STADIUM (Stadium_name, Capacity) values ('Amlodipine Besylate', 29500);
insert into STADIUM (Stadium_name, Capacity) values ('Amantadine Hydrochloride', 5000);
insert into STADIUM (Stadium_name, Capacity) values ('Amantadine HCl', 19000);
insert into STADIUM (Stadium_name, Capacity) values ('All Day Allergy', 15500);
insert into STADIUM (Stadium_name, Capacity) values ('Aleve', 17000);
insert into STADIUM (Stadium_name, Capacity) values ('Air', 12000);
insert into STADIUM (Stadium_name, Capacity) values ('07 Balancing Foundation', 21000);
