set nocount on;
insert into EDITION (Season_name, Competition_name) values ('20/21', 'Serie A');
insert into EDITION (Season_name, Competition_name) values ('20/21', 'Premier League');
insert into EDITION (Season_name, Competition_name) values ('20/21', 'La Liga');
insert into EDITION (Season_name, Competition_name) values ('20/21', 'Keukenkampioen Divisie');
insert into EDITION (Season_name, Competition_name) values ('20/21', 'Eredivisie');
insert into EDITION (Season_name, Competition_name) values ('20/21', 'Bundesliga');
insert into EDITION (Season_name, Competition_name) values ('19/20', 'Serie A');
insert into EDITION (Season_name, Competition_name) values ('19/20', 'Premier League');
insert into EDITION (Season_name, Competition_name) values ('19/20', 'La Liga');
insert into EDITION (Season_name, Competition_name) values ('19/20', 'Keukenkampioen Divisie');
insert into EDITION (Season_name, Competition_name) values ('19/20', 'Eredivisie');
insert into EDITION (Season_name, Competition_name) values ('19/20', 'Bundesliga');
insert into EDITION (Season_name, Competition_name) values ('18/19', 'Serie A');
insert into EDITION (Season_name, Competition_name) values ('18/19', 'Premier League');
insert into EDITION (Season_name, Competition_name) values ('18/19', 'La Liga');
insert into EDITION (Season_name, Competition_name) values ('18/19', 'Keukenkampioen Divisie');
insert into EDITION (Season_name, Competition_name) values ('18/19', 'Eredivisie');
insert into EDITION (Season_name, Competition_name) values ('18/19', 'Bundesliga');
