set nocount on;
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Wikido', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Voonte', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topicblab', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Topdrive', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Tavu', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Quimm', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Feedmix', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Fadeo', '18/19', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '20/21', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '20/21', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '20/21', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '20/21', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '20/21', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '20/21', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '19/20', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '19/20', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '19/20', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '19/20', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '19/20', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '19/20', 'Bundesliga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '18/19', 'Serie A');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '18/19', 'Premier League');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '18/19', 'La Liga');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '18/19', 'Keukenkampioen Divisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '18/19', 'Eredivisie');
insert into CLUB_plays_in_EDITION (Club_name, Season_name, Competition_name) values ('Eadel', '18/19', 'Bundesliga');
