CREATE OR ALTER VIEW VW_BRACKETS_KO AS
WITH KO_MATCHES AS (
	SELECT MATCH_ID, SEASON_NAME, m.COMPETITION_NAME, START_DATE, MATCH_DAY
	FROM MATCH m 
		JOIN COMPETITION c 
		ON m.COMPETITION_NAME = c.COMPETITION_NAME
	AND c.COMPETITION_TYPE = 'Knockout')
SELECT	ko.MATCH_ID, 
		r.ROUND_NR, 
		r.ROUND_NAME, 
		gm.HOME_CLUB_NAME, 
		gm.OUT_CLUB_NAME, 
		gm.HOME_GOALS, 
		gm.OUT_GOALS
FROM KO_MATCHES ko 
JOIN ROUND r	ON ko.SEASON_NAME = r.SEASON_NAME 
				AND ko.COMPETITION_NAME = r.COMPETITION_NAME 
				AND ko.START_DATE = r.START_DATE
JOIN GOALS_MATCHES gm ON ko.MATCH_ID = gm.MATCH_ID