set nocount on;
insert into COUNTRY (Country_name) values ('Zimbabwe');
insert into COUNTRY (Country_name) values ('Yemen');
insert into COUNTRY (Country_name) values ('Vietnam');
insert into COUNTRY (Country_name) values ('Venezuela');
insert into COUNTRY (Country_name) values ('Uzbekistan');
insert into COUNTRY (Country_name) values ('Uruguay');
insert into COUNTRY (Country_name) values ('United States');
insert into COUNTRY (Country_name) values ('Ukraine');
insert into COUNTRY (Country_name) values ('Uganda');
insert into COUNTRY (Country_name) values ('Turkmenistan');
insert into COUNTRY (Country_name) values ('Tunisia');
insert into COUNTRY (Country_name) values ('Tokelau');
insert into COUNTRY (Country_name) values ('Togo');
insert into COUNTRY (Country_name) values ('Thailand');
insert into COUNTRY (Country_name) values ('Tanzania');
insert into COUNTRY (Country_name) values ('Tajikistan');
insert into COUNTRY (Country_name) values ('Taiwan');
insert into COUNTRY (Country_name) values ('Syria');
insert into COUNTRY (Country_name) values ('Sweden');
insert into COUNTRY (Country_name) values ('Sudan');
insert into COUNTRY (Country_name) values ('Sri Lanka');
insert into COUNTRY (Country_name) values ('Spain');
insert into COUNTRY (Country_name) values ('South Korea');
insert into COUNTRY (Country_name) values ('South Africa');
insert into COUNTRY (Country_name) values ('Slovenia');
insert into COUNTRY (Country_name) values ('Sierra Leone');
insert into COUNTRY (Country_name) values ('Serbia');
insert into COUNTRY (Country_name) values ('Senegal');
insert into COUNTRY (Country_name) values ('Samoa');
insert into COUNTRY (Country_name) values ('Saint Vincent and the Grenadines');
insert into COUNTRY (Country_name) values ('Russia');
insert into COUNTRY (Country_name) values ('Republic of the Congo');
insert into COUNTRY (Country_name) values ('Qatar');
insert into COUNTRY (Country_name) values ('Portugal');
insert into COUNTRY (Country_name) values ('Poland');
insert into COUNTRY (Country_name) values ('Philippines');
insert into COUNTRY (Country_name) values ('Peru');
insert into COUNTRY (Country_name) values ('Paraguay');
insert into COUNTRY (Country_name) values ('Papua New Guinea');
insert into COUNTRY (Country_name) values ('Panama');
insert into COUNTRY (Country_name) values ('Palestinian Territory');
insert into COUNTRY (Country_name) values ('Pakistan');
insert into COUNTRY (Country_name) values ('Norway');
insert into COUNTRY (Country_name) values ('North Korea');
insert into COUNTRY (Country_name) values ('Nigeria');
insert into COUNTRY (Country_name) values ('Niger');
insert into COUNTRY (Country_name) values ('Netherlands');
insert into COUNTRY (Country_name) values ('Nepal');
insert into COUNTRY (Country_name) values ('Myanmar');
insert into COUNTRY (Country_name) values ('Morocco');
insert into COUNTRY (Country_name) values ('Montenegro');
insert into COUNTRY (Country_name) values ('Mongolia');
insert into COUNTRY (Country_name) values ('Moldova');
insert into COUNTRY (Country_name) values ('Micronesia');
insert into COUNTRY (Country_name) values ('Mexico');
insert into COUNTRY (Country_name) values ('Malta');
insert into COUNTRY (Country_name) values ('Mali');
insert into COUNTRY (Country_name) values ('Malaysia');
insert into COUNTRY (Country_name) values ('Malawi');
insert into COUNTRY (Country_name) values ('Macedonia');
insert into COUNTRY (Country_name) values ('Macao');
insert into COUNTRY (Country_name) values ('Luxembourg');
insert into COUNTRY (Country_name) values ('Libya');
insert into COUNTRY (Country_name) values ('Lebanon');
insert into COUNTRY (Country_name) values ('Latvia');
insert into COUNTRY (Country_name) values ('Laos');
insert into COUNTRY (Country_name) values ('Kyrgyzstan');
insert into COUNTRY (Country_name) values ('Kenya');
insert into COUNTRY (Country_name) values ('Kazakhstan');
insert into COUNTRY (Country_name) values ('Japan');
insert into COUNTRY (Country_name) values ('Jamaica');
insert into COUNTRY (Country_name) values ('Ivory Coast');
insert into COUNTRY (Country_name) values ('Italy');
insert into COUNTRY (Country_name) values ('Israel');
insert into COUNTRY (Country_name) values ('Ireland');
insert into COUNTRY (Country_name) values ('Iran');
insert into COUNTRY (Country_name) values ('Indonesia');
insert into COUNTRY (Country_name) values ('Hungary');
insert into COUNTRY (Country_name) values ('Honduras');
insert into COUNTRY (Country_name) values ('Haiti');
insert into COUNTRY (Country_name) values ('Guinea-Bissau');
insert into COUNTRY (Country_name) values ('Guatemala');
insert into COUNTRY (Country_name) values ('Greenland');
insert into COUNTRY (Country_name) values ('Greece');
insert into COUNTRY (Country_name) values ('Ghana');
insert into COUNTRY (Country_name) values ('Germany');
insert into COUNTRY (Country_name) values ('Georgia');
insert into COUNTRY (Country_name) values ('France');
insert into COUNTRY (Country_name) values ('Finland');
insert into COUNTRY (Country_name) values ('Ethiopia');
insert into COUNTRY (Country_name) values ('Estonia');
insert into COUNTRY (Country_name) values ('El Salvador');
insert into COUNTRY (Country_name) values ('Egypt');
insert into COUNTRY (Country_name) values ('Ecuador');
insert into COUNTRY (Country_name) values ('East Timor');
insert into COUNTRY (Country_name) values ('Dominican Republic');
insert into COUNTRY (Country_name) values ('Djibouti');
insert into COUNTRY (Country_name) values ('Denmark');
insert into COUNTRY (Country_name) values ('Democratic Republic of the Congo');
insert into COUNTRY (Country_name) values ('Czech Republic');
insert into COUNTRY (Country_name) values ('Cuba');
insert into COUNTRY (Country_name) values ('Croatia');
insert into COUNTRY (Country_name) values ('Colombia');
insert into COUNTRY (Country_name) values ('China');
insert into COUNTRY (Country_name) values ('Chile');
insert into COUNTRY (Country_name) values ('Chad');
insert into COUNTRY (Country_name) values ('Canada');
insert into COUNTRY (Country_name) values ('Cameroon');
insert into COUNTRY (Country_name) values ('Bulgaria');
insert into COUNTRY (Country_name) values ('Brazil');
insert into COUNTRY (Country_name) values ('Botswana');
insert into COUNTRY (Country_name) values ('Bosnia and Herzegovina');
insert into COUNTRY (Country_name) values ('Bonaire, Saint Eustatius and Saba ');
insert into COUNTRY (Country_name) values ('Bolivia');
insert into COUNTRY (Country_name) values ('Belgium');
insert into COUNTRY (Country_name) values ('Belarus');
insert into COUNTRY (Country_name) values ('Bangladesh');
insert into COUNTRY (Country_name) values ('Azerbaijan');
insert into COUNTRY (Country_name) values ('Australia');
insert into COUNTRY (Country_name) values ('Armenia');
insert into COUNTRY (Country_name) values ('Argentina');
insert into COUNTRY (Country_name) values ('American Samoa');
insert into COUNTRY (Country_name) values ('Albania');
insert into COUNTRY (Country_name) values ('Aland Islands');
insert into COUNTRY (Country_name) values ('Afghanistan');
