set nocount on;
insert into COUNTRY (Country_name) values ('Zimbabwe');
insert into COUNTRY (Country_name) values ('Vietnam');
insert into COUNTRY (Country_name) values ('Venezuela');
insert into COUNTRY (Country_name) values ('Uzbekistan');
insert into COUNTRY (Country_name) values ('United States');
insert into COUNTRY (Country_name) values ('Ukraine');
insert into COUNTRY (Country_name) values ('Uganda');
insert into COUNTRY (Country_name) values ('Turkmenistan');
insert into COUNTRY (Country_name) values ('Tunisia');
insert into COUNTRY (Country_name) values ('Trinidad and Tobago');
insert into COUNTRY (Country_name) values ('Thailand');
insert into COUNTRY (Country_name) values ('Tanzania');
insert into COUNTRY (Country_name) values ('Tajikistan');
insert into COUNTRY (Country_name) values ('Taiwan');
insert into COUNTRY (Country_name) values ('Syria');
insert into COUNTRY (Country_name) values ('Switzerland');
insert into COUNTRY (Country_name) values ('Sweden');
insert into COUNTRY (Country_name) values ('Sudan');
insert into COUNTRY (Country_name) values ('Sri Lanka');
insert into COUNTRY (Country_name) values ('Spain');
insert into COUNTRY (Country_name) values ('South Korea');
insert into COUNTRY (Country_name) values ('South Africa');
insert into COUNTRY (Country_name) values ('Somalia');
insert into COUNTRY (Country_name) values ('Slovenia');
insert into COUNTRY (Country_name) values ('Sierra Leone');
insert into COUNTRY (Country_name) values ('Serbia');
insert into COUNTRY (Country_name) values ('Saudi Arabia');
insert into COUNTRY (Country_name) values ('Samoa');
insert into COUNTRY (Country_name) values ('Saint Lucia');
insert into COUNTRY (Country_name) values ('Russia');
insert into COUNTRY (Country_name) values ('Portugal');
insert into COUNTRY (Country_name) values ('Poland');
insert into COUNTRY (Country_name) values ('Philippines');
insert into COUNTRY (Country_name) values ('Peru');
insert into COUNTRY (Country_name) values ('Paraguay');
insert into COUNTRY (Country_name) values ('Panama');
insert into COUNTRY (Country_name) values ('Palestinian Territory');
insert into COUNTRY (Country_name) values ('Pakistan');
insert into COUNTRY (Country_name) values ('Oman');
insert into COUNTRY (Country_name) values ('Norway');
insert into COUNTRY (Country_name) values ('North Korea');
insert into COUNTRY (Country_name) values ('Northern Mariana Islands');
insert into COUNTRY (Country_name) values ('Nigeria');
insert into COUNTRY (Country_name) values ('Niger');
insert into COUNTRY (Country_name) values ('Nicaragua');
insert into COUNTRY (Country_name) values ('New Zealand');
insert into COUNTRY (Country_name) values ('Netherlands');
insert into COUNTRY (Country_name) values ('Nepal');
insert into COUNTRY (Country_name) values ('Namibia');
insert into COUNTRY (Country_name) values ('Morocco');
insert into COUNTRY (Country_name) values ('Montenegro');
insert into COUNTRY (Country_name) values ('Mongolia');
insert into COUNTRY (Country_name) values ('Moldova');
insert into COUNTRY (Country_name) values ('Mexico');
insert into COUNTRY (Country_name) values ('Mauritius');
insert into COUNTRY (Country_name) values ('Malta');
insert into COUNTRY (Country_name) values ('Mali');
insert into COUNTRY (Country_name) values ('Malaysia');
insert into COUNTRY (Country_name) values ('Malawi');
insert into COUNTRY (Country_name) values ('Madagascar');
insert into COUNTRY (Country_name) values ('Macedonia');
insert into COUNTRY (Country_name) values ('Luxembourg');
insert into COUNTRY (Country_name) values ('Libya');
insert into COUNTRY (Country_name) values ('Lebanon');
insert into COUNTRY (Country_name) values ('Latvia');
insert into COUNTRY (Country_name) values ('Kyrgyzstan');
insert into COUNTRY (Country_name) values ('Kuwait');
insert into COUNTRY (Country_name) values ('Kosovo');
insert into COUNTRY (Country_name) values ('Kenya');
insert into COUNTRY (Country_name) values ('Kazakhstan');
insert into COUNTRY (Country_name) values ('Jordan');
insert into COUNTRY (Country_name) values ('Japan');
insert into COUNTRY (Country_name) values ('Jamaica');
insert into COUNTRY (Country_name) values ('Ivory Coast');
insert into COUNTRY (Country_name) values ('Israel');
insert into COUNTRY (Country_name) values ('Ireland');
insert into COUNTRY (Country_name) values ('Iraq');
insert into COUNTRY (Country_name) values ('Iran');
insert into COUNTRY (Country_name) values ('Indonesia');
insert into COUNTRY (Country_name) values ('Hungary');
insert into COUNTRY (Country_name) values ('Honduras');
insert into COUNTRY (Country_name) values ('Guinea');
insert into COUNTRY (Country_name) values ('Guatemala');
insert into COUNTRY (Country_name) values ('Guam');
insert into COUNTRY (Country_name) values ('Greenland');
insert into COUNTRY (Country_name) values ('Greece');
insert into COUNTRY (Country_name) values ('Ghana');
insert into COUNTRY (Country_name) values ('Germany');
insert into COUNTRY (Country_name) values ('Georgia');
insert into COUNTRY (Country_name) values ('Gambia');
insert into COUNTRY (Country_name) values ('French Polynesia');
insert into COUNTRY (Country_name) values ('France');
insert into COUNTRY (Country_name) values ('Finland');
insert into COUNTRY (Country_name) values ('Ethiopia');
insert into COUNTRY (Country_name) values ('Estonia');
insert into COUNTRY (Country_name) values ('Egypt');
insert into COUNTRY (Country_name) values ('Ecuador');
insert into COUNTRY (Country_name) values ('Dominican Republic');
insert into COUNTRY (Country_name) values ('Denmark');
insert into COUNTRY (Country_name) values ('Democratic Republic of the Congo');
insert into COUNTRY (Country_name) values ('Czech Republic');
insert into COUNTRY (Country_name) values ('Cyprus');
insert into COUNTRY (Country_name) values ('Cuba');
insert into COUNTRY (Country_name) values ('Croatia');
insert into COUNTRY (Country_name) values ('Costa Rica');
insert into COUNTRY (Country_name) values ('Comoros');
insert into COUNTRY (Country_name) values ('Colombia');
insert into COUNTRY (Country_name) values ('China');
insert into COUNTRY (Country_name) values ('Chile');
insert into COUNTRY (Country_name) values ('Chad');
insert into COUNTRY (Country_name) values ('Central African Republic');
insert into COUNTRY (Country_name) values ('Canada');
insert into COUNTRY (Country_name) values ('Cameroon');
insert into COUNTRY (Country_name) values ('Burundi');
insert into COUNTRY (Country_name) values ('Bulgaria');
insert into COUNTRY (Country_name) values ('Brazil');
insert into COUNTRY (Country_name) values ('Botswana');
insert into COUNTRY (Country_name) values ('Bosnia and Herzegovina');
insert into COUNTRY (Country_name) values ('Bolivia');
insert into COUNTRY (Country_name) values ('Bhutan');
insert into COUNTRY (Country_name) values ('Benin');
insert into COUNTRY (Country_name) values ('Belize');
insert into COUNTRY (Country_name) values ('Belarus');
insert into COUNTRY (Country_name) values ('Bangladesh');
insert into COUNTRY (Country_name) values ('Bahrain');
insert into COUNTRY (Country_name) values ('Azerbaijan');
insert into COUNTRY (Country_name) values ('Austria');
insert into COUNTRY (Country_name) values ('Armenia');
insert into COUNTRY (Country_name) values ('Argentina');
insert into COUNTRY (Country_name) values ('Angola');
insert into COUNTRY (Country_name) values ('Albania');
insert into COUNTRY (Country_name) values ('Aland Islands');
insert into COUNTRY (Country_name) values ('Afghanistan');
