CREATE or ALTER TRIGGER TRG_NO_UPDATES_ON_CURRENT_EDITION_CLUB ON MATCH
AFTER UPDATE, DELETE ,INSERT
AS
BEGIN
	IF @@rowcount = 0
		RETURN
	SET NOCOUNT ON

	IF EXISTS(
	    SELECT *
	    FROM inserted i
	    JOIN MATCHDAY M2 on M2.SEASON_NAME = i.SEASON_NAME and M2.COMPETITION_NAME = i.COMPETITION_NAME and M2.START_DATE = i.START_DATE and M2.MATCH_DAY = i.MATCH_DAY
	    JOIN ROUND R2 on M2.SEASON_NAME = R2.SEASON_NAME and M2.COMPETITION_NAME = R2.COMPETITION_NAME and M2.START_DATE = R2.START_DATE
	    JOIN EDITION E on R2.SEASON_NAME = E.SEASON_NAME and R2.COMPETITION_NAME = E.COMPETITION_NAME
	    JOIN SEASON S on E.SEASON_NAME = S.SEASON_NAME
	    WHERE END_DATE < GETDATE()
	)
		THROW 50000, 'Season is still active, cannot update data', 1

    	IF EXISTS(
	    SELECT *
	    FROM deleted d
	    JOIN MATCHDAY M2 on M2.SEASON_NAME = d.SEASON_NAME and M2.COMPETITION_NAME = d.COMPETITION_NAME and M2.START_DATE = d.START_DATE and M2.MATCH_DAY = d.MATCH_DAY
	    JOIN ROUND R2 on M2.SEASON_NAME = R2.SEASON_NAME and M2.COMPETITION_NAME = R2.COMPETITION_NAME and M2.START_DATE = R2.START_DATE
	    JOIN EDITION E on R2.SEASON_NAME = E.SEASON_NAME and R2.COMPETITION_NAME = E.COMPETITION_NAME
	    JOIN SEASON S on E.SEASON_NAME = S.SEASON_NAME
	    WHERE END_DATE < GETDATE()
	)
		THROW 50000, 'Season is still active, cannot delete data', 1
END
GO