CREATE OR ALTER TRIGGER TRG_VALID_AMOUNT_OF_SPECTATORS ON [MATCH]
FOR INSERT, UPDATE
AS
BEGIN
IF @@ROWCOUNT > 0 AND UPDATE(SPECTATORS)
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM inserted i 
							LEFT JOIN STADIUM s ON i.STADIUM_NAME = s.STADIUM_NAME
					WHERE i.SPECTATORS > s.CAPACITY
					)
			THROW 50001, 'Amount of spectators can''t be larger than the capacity of stadium', 1
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
GO