CREATE OR ALTER TRIGGER TRG_CHECK_PLAYER_COUNT
	ON POSITION
	FOR INSERT, UPDATE
	AS
BEGIN
	IF @@ROWCOUNT > 0
		BEGIN TRY
			IF EXISTS(
					SELECT COUNT(PLAYER_PERSON_ID)
					FROM POSITION
					GROUP BY MATCH_ID
					HAVING COUNT(*) > 22
				)
				THROW 50001, 'There can only be a max of 22 players in a match', 1;
		END TRY
		BEGIN CATCH
			THROW
		END CATCH
END
GO