CREATE OR ALTER TRIGGER TRG_CHECK_PLAYER_COUNT
	ON LINEUP
	FOR INSERT, UPDATE
	AS
BEGIN
	IF @@ROWCOUNT > 0
		BEGIN TRY
			IF EXISTS (
				SELECT POS.MATCH_ID, COUNT(POS.PLAYER_PERSON_ID) AS player_count
				FROM POSITION AS POS
				INNER JOIN PLAYER AS P
					ON P.PERSON_ID = POS.PLAYER_PERSON_ID
				WHERE POS.MATCH_ID IN (
					SELECT MATCH_ID
					FROM INSERTED
				)
				GROUP BY POS.MATCH_ID, P.CLUB_NAME
				HAVING COUNT(POS.PLAYER_PERSON_ID) < 7 OR COUNT(POS.PLAYER_PERSON_ID) > 11
			)
			THROW 50002, 'There can only be a minimum of 7 and a maximum of 11 players in a club while playing a match', 1;
		END TRY

		BEGIN CATCH
			THROW
		END CATCH
END

GO

