CREATE OR ALTER TRIGGER TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_PLAYER_AS_RESERVE_IN_MATCH ON PLAYER_AS_RESERVE_IN_MATCH
FOR INSERT, UPDATE
AS
BEGIN
IF @@ROWCOUNT > 0
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM inserted i 
									join [MATCH] m on i.MATCH_ID = m.MATCH_ID 
									join PLAYER p on p.PERSON_ID = i.PLAYER_PERSON_ID 
							WHERE not (p.CLUB_NAME = HOME_CLUB_NAME 
										OR p.CLUB_NAME = OUT_CLUB_NAME) 
										OR p.CLUB_NAME IS NULL
					)
			THROW 50001, 'Player must be member of home_club or out_club', 1;
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
GO
CREATE OR ALTER TRIGGER TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_POSITION ON LINEUP
FOR INSERT, UPDATE
AS
BEGIN
IF @@ROWCOUNT > 0
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM inserted i 
									join [MATCH] m on i.MATCH_ID = m.MATCH_ID 
									join PLAYER p on p.PERSON_ID = i.PLAYER_PERSON_ID 
							WHERE not (p.CLUB_NAME = HOME_CLUB_NAME 
										OR p.CLUB_NAME = OUT_CLUB_NAME)
										OR p.CLUB_NAME IS NULL
					)
			THROW 50001, 'Player must be member of home_club or out_club', 1;
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
GO