CREATE OR ALTER TRIGGER TRG_CHECK_CLUB_IN_EDITION ON [MATCH]
FOR INSERT, UPDATE
AS
BEGIN
IF @@ROWCOUNT > 0 AND (UPDATE(HOME_CLUB_NAME) OR UPDATE(OUT_CLUB_NAME))
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM inserted i 
							LEFT JOIN CLUB_PLAYS_IN_EDITION home ON i.HOME_CLUB_NAME = home.CLUB_NAME
																	AND i.SEASON_NAME = home.SEASON_NAME
																	AND i.COMPETITION_NAME = home.COMPETITION_NAME
							LEFT JOIN CLUB_PLAYS_IN_EDITION [out] ON i.OUT_CLUB_NAME = [out].CLUB_NAME
																	AND i.SEASON_NAME = [out].SEASON_NAME
																	AND i.COMPETITION_NAME = [out].COMPETITION_NAME
					WHERE home.CLUB_NAME IS NULL
							OR [out].CLUB_NAME IS NULL
					)
			THROW 50001, 'The clubs playing in the match need to be part of the edition', 1
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
