CREATE OR ALTER TRIGGER TRG_MAX_16_CLUBS_KNOCKOUT ON CLUB_PLAYS_IN_EDITION
FOR INSERT, UPDATE, DELETE
AS
BEGIN
IF @@ROWCOUNT > 0
	BEGIN
	BEGIN TRY
		IF EXISTS(
			SELECT 1
				FROM CLUB_PLAYS_IN_EDITION AS CIE
					INNER JOIN COMPETITION AS C
						ON CIE.COMPETITION_NAME = C.COMPETITION_NAME
				WHERE C.COMPETITION_TYPE = 'Knockout'
				GROUP BY CIE.SEASON_NAME, CIE.COMPETITION_NAME
				HAVING COUNT(*) != 16
		)
			THROW 50000, 'Can only insert 16 clubs per Knockout competition', 1;
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
END
