set nocount on;
insert into CITY (Country_name, City_name) values ('Zimbabwe', 'Chitungwiza');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Uyen Hung');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Thị Trấn Yên Cát');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Thị Trấn Quan Hóa');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Thị Trấn Phú Mỹ');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Thành Phố Ninh Bình');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Hòa Bình');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Đắk Glei');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Đà Bắc');
insert into CITY (Country_name, City_name) values ('Vietnam', 'Cẩm Phả Mines');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Zea');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Valle de La Pascua');
insert into CITY (Country_name, City_name) values ('Venezuela', 'San Juan de los Morros');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Sabana Grande');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Mariara');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Delicias');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Ciudad Bolivia');
insert into CITY (Country_name, City_name) values ('Venezuela', 'Aroa');
insert into CITY (Country_name, City_name) values ('Uzbekistan', 'Yangiobod');
insert into CITY (Country_name, City_name) values ('Uzbekistan', 'Chimboy Shahri');
insert into CITY (Country_name, City_name) values ('United States', 'Wilmington');
insert into CITY (Country_name, City_name) values ('United States', 'Tulsa');
insert into CITY (Country_name, City_name) values ('United States', 'San Diego');
insert into CITY (Country_name, City_name) values ('United States', 'San Bernardino');
insert into CITY (Country_name, City_name) values ('United States', 'Salt Lake City');
insert into CITY (Country_name, City_name) values ('United States', 'Sacramento');
insert into CITY (Country_name, City_name) values ('United States', 'Rochester');
insert into CITY (Country_name, City_name) values ('United States', 'Portland');
insert into CITY (Country_name, City_name) values ('United States', 'New York City');
insert into CITY (Country_name, City_name) values ('United States', 'Miami');
insert into CITY (Country_name, City_name) values ('United States', 'Mesquite');
insert into CITY (Country_name, City_name) values ('United States', 'Louisville');
insert into CITY (Country_name, City_name) values ('United States', 'Little Rock');
insert into CITY (Country_name, City_name) values ('United States', 'Lansing');
insert into CITY (Country_name, City_name) values ('United States', 'Knoxville');
insert into CITY (Country_name, City_name) values ('United States', 'Kissimmee');
insert into CITY (Country_name, City_name) values ('United States', 'Jackson');
insert into CITY (Country_name, City_name) values ('United States', 'Dulles');
insert into CITY (Country_name, City_name) values ('United States', 'Denver');
insert into CITY (Country_name, City_name) values ('United States', 'Dayton');
insert into CITY (Country_name, City_name) values ('United States', 'Cincinnati');
insert into CITY (Country_name, City_name) values ('United States', 'Chicago');
insert into CITY (Country_name, City_name) values ('United States', 'Carson City');
insert into CITY (Country_name, City_name) values ('United States', 'Boston');
insert into CITY (Country_name, City_name) values ('United States', 'Boise');
insert into CITY (Country_name, City_name) values ('United States', 'Boca Raton');
insert into CITY (Country_name, City_name) values ('United States', 'Atlanta');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Zhovkva');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Yasynuvata');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Verkhnyaya Belka');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Storozhynets’');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Semenivka');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Popasna');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Manevychi');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Kostopil’');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Kolochava');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Kakhovka');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Chemerivtsi');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Bilshivtsi');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Bilohirs’k');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Batiovo');
insert into CITY (Country_name, City_name) values ('Ukraine', 'Amvrosiyivka');
insert into CITY (Country_name, City_name) values ('Uganda', 'Zombo');
insert into CITY (Country_name, City_name) values ('Uganda', 'Ntungamo');
insert into CITY (Country_name, City_name) values ('Turkmenistan', 'Tagta');
insert into CITY (Country_name, City_name) values ('Turkmenistan', 'Daşoguz');
insert into CITY (Country_name, City_name) values ('Tunisia', 'Zarzis');
insert into CITY (Country_name, City_name) values ('Tunisia', 'El Kef');
insert into CITY (Country_name, City_name) values ('Tunisia', 'Carthage');
insert into CITY (Country_name, City_name) values ('Trinidad and Tobago', 'Petit Valley');
insert into CITY (Country_name, City_name) values ('Thailand', 'Waeng Yai');
insert into CITY (Country_name, City_name) values ('Thailand', 'Thai Charoen');
insert into CITY (Country_name, City_name) values ('Thailand', 'Si Narong');
insert into CITY (Country_name, City_name) values ('Thailand', 'Phu Kradueng');
insert into CITY (Country_name, City_name) values ('Thailand', 'Phetchabun');
insert into CITY (Country_name, City_name) values ('Thailand', 'Na Khu');
insert into CITY (Country_name, City_name) values ('Thailand', 'Ko Samui');
insert into CITY (Country_name, City_name) values ('Thailand', 'Khok Sung');
insert into CITY (Country_name, City_name) values ('Thailand', 'Chiang Yuen');
insert into CITY (Country_name, City_name) values ('Tanzania', 'Puma');
insert into CITY (Country_name, City_name) values ('Tanzania', 'Masumbwe');
insert into CITY (Country_name, City_name) values ('Tanzania', 'Kyela');
insert into CITY (Country_name, City_name) values ('Tajikistan', 'Abdurahmoni Jomí');
insert into CITY (Country_name, City_name) values ('Taiwan', 'Taichung');
insert into CITY (Country_name, City_name) values ('Syria', 'Hīsh');
insert into CITY (Country_name, City_name) values ('Syria', 'Ar Riqāmā');
insert into CITY (Country_name, City_name) values ('Switzerland', 'Zürich');
insert into CITY (Country_name, City_name) values ('Sweden', 'Uppsala');
insert into CITY (Country_name, City_name) values ('Sweden', 'Tullinge');
insert into CITY (Country_name, City_name) values ('Sweden', 'Täby');
insert into CITY (Country_name, City_name) values ('Sweden', 'Sundbyberg');
insert into CITY (Country_name, City_name) values ('Sweden', 'Storvreta');
insert into CITY (Country_name, City_name) values ('Sweden', 'Stockholm');
insert into CITY (Country_name, City_name) values ('Sweden', 'Solna');
insert into CITY (Country_name, City_name) values ('Sweden', 'Södertälje');
insert into CITY (Country_name, City_name) values ('Sweden', 'Säffle');
insert into CITY (Country_name, City_name) values ('Sweden', 'Örnsköldsvik');
insert into CITY (Country_name, City_name) values ('Sweden', 'Nossebro');
insert into CITY (Country_name, City_name) values ('Sweden', 'Norrköping');
insert into CITY (Country_name, City_name) values ('Sweden', 'Munkfors');
insert into CITY (Country_name, City_name) values ('Sweden', 'Mora');
insert into CITY (Country_name, City_name) values ('Sweden', 'Linköping');
insert into CITY (Country_name, City_name) values ('Sweden', 'Lidingö');
insert into CITY (Country_name, City_name) values ('Sweden', 'Kungsbacka');
insert into CITY (Country_name, City_name) values ('Sweden', 'Kramfors');
insert into CITY (Country_name, City_name) values ('Sweden', 'Hässelby');
insert into CITY (Country_name, City_name) values ('Sweden', 'Göteborg');
insert into CITY (Country_name, City_name) values ('Sweden', 'Gävle');
insert into CITY (Country_name, City_name) values ('Sweden', 'Färgelanda');
insert into CITY (Country_name, City_name) values ('Sweden', 'Falkenberg');
insert into CITY (Country_name, City_name) values ('Sweden', 'Eskilstuna');
insert into CITY (Country_name, City_name) values ('Sweden', 'Boden');
insert into CITY (Country_name, City_name) values ('Sweden', 'Billdal');
insert into CITY (Country_name, City_name) values ('Sweden', 'Älvängen');
insert into CITY (Country_name, City_name) values ('Sudan', 'Al Qadarif');
insert into CITY (Country_name, City_name) values ('Sri Lanka', 'Peliyagoda');
insert into CITY (Country_name, City_name) values ('Sri Lanka', 'Haputale');
insert into CITY (Country_name, City_name) values ('Spain', 'Palma De Mallorca');
insert into CITY (Country_name, City_name) values ('Spain', 'Gijon');
insert into CITY (Country_name, City_name) values ('Spain', 'Alicante/Alacant');
insert into CITY (Country_name, City_name) values ('South Korea', 'Yesan');
insert into CITY (Country_name, City_name) values ('South Africa', 'Vredefort');
insert into CITY (Country_name, City_name) values ('South Africa', 'Hluhluwe');
insert into CITY (Country_name, City_name) values ('South Africa', 'Empangeni');
insert into CITY (Country_name, City_name) values ('South Africa', 'Elliot');
insert into CITY (Country_name, City_name) values ('South Africa', 'Deneysville');
insert into CITY (Country_name, City_name) values ('South Africa', 'Bothaville');
insert into CITY (Country_name, City_name) values ('South Africa', 'Bergville');
insert into CITY (Country_name, City_name) values ('Somalia', 'Ceerigaabo');
insert into CITY (Country_name, City_name) values ('Slovenia', 'Zgornje Pirniče');
insert into CITY (Country_name, City_name) values ('Slovenia', 'Štore');
insert into CITY (Country_name, City_name) values ('Slovenia', 'Solčava');
insert into CITY (Country_name, City_name) values ('Slovenia', 'Puconci');
insert into CITY (Country_name, City_name) values ('Slovenia', 'Moravče');
insert into CITY (Country_name, City_name) values ('Sierra Leone', 'Potoru');
insert into CITY (Country_name, City_name) values ('Serbia', 'Sonta');
insert into CITY (Country_name, City_name) values ('Serbia', 'Riđica');
insert into CITY (Country_name, City_name) values ('Serbia', 'Perlez');
insert into CITY (Country_name, City_name) values ('Serbia', 'Gudurica');
insert into CITY (Country_name, City_name) values ('Serbia', 'Čortanovci');
insert into CITY (Country_name, City_name) values ('Serbia', 'Čoka');
insert into CITY (Country_name, City_name) values ('Serbia', 'Biljača');
insert into CITY (Country_name, City_name) values ('Saudi Arabia', 'Najrān');
insert into CITY (Country_name, City_name) values ('Samoa', 'Fasito‘outa');
insert into CITY (Country_name, City_name) values ('Samoa', 'Faleula');
insert into CITY (Country_name, City_name) values ('Saint Lucia', 'Soufrière');
insert into CITY (Country_name, City_name) values ('Russia', 'Zhigulevsk');
insert into CITY (Country_name, City_name) values ('Russia', 'Yurovka');
insert into CITY (Country_name, City_name) values ('Russia', 'Yessentuki');
insert into CITY (Country_name, City_name) values ('Russia', 'Vyksa');
insert into CITY (Country_name, City_name) values ('Russia', 'Vostryakovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Veshnyaki');
insert into CITY (Country_name, City_name) values ('Russia', 'Vasyl''evsky Ostrov');
insert into CITY (Country_name, City_name) values ('Russia', 'Vagonoremont');
insert into CITY (Country_name, City_name) values ('Russia', 'Uvarovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Tuapse');
insert into CITY (Country_name, City_name) values ('Russia', 'Tirlyanskiy');
insert into CITY (Country_name, City_name) values ('Russia', 'Tiksi');
insert into CITY (Country_name, City_name) values ('Russia', 'Tigil’');
insert into CITY (Country_name, City_name) values ('Russia', 'Taremskoye');
insert into CITY (Country_name, City_name) values ('Russia', 'Suponevo');
insert into CITY (Country_name, City_name) values ('Russia', 'Sudzha');
insert into CITY (Country_name, City_name) values ('Russia', 'Spassk-Dal’niy');
insert into CITY (Country_name, City_name) values ('Russia', 'Sovetskaya Gavan’');
insert into CITY (Country_name, City_name) values ('Russia', 'Sosnovka');
insert into CITY (Country_name, City_name) values ('Russia', 'Satis');
insert into CITY (Country_name, City_name) values ('Russia', 'Pokrovskoye');
insert into CITY (Country_name, City_name) values ('Russia', 'Orekhovo-Borisovo Severnoye');
insert into CITY (Country_name, City_name) values ('Russia', 'Nizhniy Kislyay');
insert into CITY (Country_name, City_name) values ('Russia', 'Neryungri');
insert into CITY (Country_name, City_name) values ('Russia', 'Nagornyy');
insert into CITY (Country_name, City_name) values ('Russia', 'Mugi');
insert into CITY (Country_name, City_name) values ('Russia', 'Mayskiy');
insert into CITY (Country_name, City_name) values ('Russia', 'Maromitsa');
insert into CITY (Country_name, City_name) values ('Russia', 'Levashi');
insert into CITY (Country_name, City_name) values ('Russia', 'Ladushkin');
insert into CITY (Country_name, City_name) values ('Russia', 'Krasnogorskiy');
insert into CITY (Country_name, City_name) values ('Russia', 'Kolyubakino');
insert into CITY (Country_name, City_name) values ('Russia', 'Khomutovo');
insert into CITY (Country_name, City_name) values ('Russia', 'Kalanguy');
insert into CITY (Country_name, City_name) values ('Russia', 'Isakly');
insert into CITY (Country_name, City_name) values ('Russia', 'Gorbatovka');
insert into CITY (Country_name, City_name) values ('Russia', 'Golovinskiy');
insert into CITY (Country_name, City_name) values ('Russia', 'Gal’bshtadt');
insert into CITY (Country_name, City_name) values ('Russia', 'Burla');
insert into CITY (Country_name, City_name) values ('Russia', 'Berëza');
insert into CITY (Country_name, City_name) values ('Russia', 'Akademicheskoe');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vilarelho');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vila Franca do Campo');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vila Alva');
insert into CITY (Country_name, City_name) values ('Portugal', 'Várzea');
insert into CITY (Country_name, City_name) values ('Portugal', 'Vale Maceiras');
insert into CITY (Country_name, City_name) values ('Portugal', 'Soutelo');
insert into CITY (Country_name, City_name) values ('Portugal', 'Sever do Vouga');
insert into CITY (Country_name, City_name) values ('Portugal', 'Senhor da Serra');
insert into CITY (Country_name, City_name) values ('Portugal', 'Seixo de Manhoses');
insert into CITY (Country_name, City_name) values ('Portugal', 'Seixo');
insert into CITY (Country_name, City_name) values ('Portugal', 'São Mateus');
insert into CITY (Country_name, City_name) values ('Portugal', 'Santa Cruz');
insert into CITY (Country_name, City_name) values ('Portugal', 'Póvoa de Penela');
insert into CITY (Country_name, City_name) values ('Portugal', 'Póvoa');
insert into CITY (Country_name, City_name) values ('Portugal', 'Ourentã');
insert into CITY (Country_name, City_name) values ('Portugal', 'Oliveira de Frades');
insert into CITY (Country_name, City_name) values ('Portugal', 'Loureiro');
insert into CITY (Country_name, City_name) values ('Portugal', 'Leiria');
insert into CITY (Country_name, City_name) values ('Portugal', 'Laveiras');
insert into CITY (Country_name, City_name) values ('Portugal', 'Igreja');
insert into CITY (Country_name, City_name) values ('Portugal', 'Guifões');
insert into CITY (Country_name, City_name) values ('Portugal', 'Cortinhas');
insert into CITY (Country_name, City_name) values ('Portugal', 'Cochadas');
insert into CITY (Country_name, City_name) values ('Portugal', 'Chouto');
insert into CITY (Country_name, City_name) values ('Portugal', 'Cepões');
insert into CITY (Country_name, City_name) values ('Portugal', 'Castelo');
insert into CITY (Country_name, City_name) values ('Portugal', 'Carrascal');
insert into CITY (Country_name, City_name) values ('Portugal', 'Calde');
insert into CITY (Country_name, City_name) values ('Portugal', 'Cabra Figa');
insert into CITY (Country_name, City_name) values ('Portugal', 'Cabouco');
insert into CITY (Country_name, City_name) values ('Portugal', 'Boucinha');
insert into CITY (Country_name, City_name) values ('Portugal', 'Biscoitos');
insert into CITY (Country_name, City_name) values ('Portugal', 'Bárrio');
insert into CITY (Country_name, City_name) values ('Portugal', 'Arruda dos Vinhos');
insert into CITY (Country_name, City_name) values ('Poland', 'Złotów');
insert into CITY (Country_name, City_name) values ('Poland', 'Wielgie');
insert into CITY (Country_name, City_name) values ('Poland', 'Świnice Warckie');
insert into CITY (Country_name, City_name) values ('Poland', 'Stoszowice');
insert into CITY (Country_name, City_name) values ('Poland', 'Skawica');
insert into CITY (Country_name, City_name) values ('Poland', 'Sierpc');
insert into CITY (Country_name, City_name) values ('Poland', 'Ścinawa');
insert into CITY (Country_name, City_name) values ('Poland', 'Sanok');
insert into CITY (Country_name, City_name) values ('Poland', 'Rokitno Szlacheckie');
insert into CITY (Country_name, City_name) values ('Poland', 'Raniżów');
insert into CITY (Country_name, City_name) values ('Poland', 'Raków');
insert into CITY (Country_name, City_name) values ('Poland', 'Radzanów');
insert into CITY (Country_name, City_name) values ('Poland', 'Przybyszówka');
insert into CITY (Country_name, City_name) values ('Poland', 'Pniewy');
insert into CITY (Country_name, City_name) values ('Poland', 'Pewel Wielka');
insert into CITY (Country_name, City_name) values ('Poland', 'Naprawa');
insert into CITY (Country_name, City_name) values ('Poland', 'Mniszków');
insert into CITY (Country_name, City_name) values ('Poland', 'Mieszkowice');
insert into CITY (Country_name, City_name) values ('Poland', 'Lipsko');
insert into CITY (Country_name, City_name) values ('Poland', 'Łeba');
insert into CITY (Country_name, City_name) values ('Poland', 'Koźle');
insert into CITY (Country_name, City_name) values ('Poland', 'Kowale');
insert into CITY (Country_name, City_name) values ('Poland', 'Kórnik');
insert into CITY (Country_name, City_name) values ('Poland', 'Konstancin-Jeziorna');
insert into CITY (Country_name, City_name) values ('Poland', 'Gzy');
insert into CITY (Country_name, City_name) values ('Poland', 'Gubin');
insert into CITY (Country_name, City_name) values ('Poland', 'Grębów');
insert into CITY (Country_name, City_name) values ('Poland', 'Dubiecko');
insert into CITY (Country_name, City_name) values ('Poland', 'Cieplice Śląskie Zdrój');
insert into CITY (Country_name, City_name) values ('Poland', 'Choroszcz');
insert into CITY (Country_name, City_name) values ('Poland', 'Chorkówka');
insert into CITY (Country_name, City_name) values ('Poland', 'Bardo');
insert into CITY (Country_name, City_name) values ('Philippines', 'Villaviciosa');
insert into CITY (Country_name, City_name) values ('Philippines', 'Tungao');
insert into CITY (Country_name, City_name) values ('Philippines', 'Talisayan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Tabonoc');
insert into CITY (Country_name, City_name) values ('Philippines', 'Santo Domingo');
insert into CITY (Country_name, City_name) values ('Philippines', 'Santa Teresita');
insert into CITY (Country_name, City_name) values ('Philippines', 'Santa Monica');
insert into CITY (Country_name, City_name) values ('Philippines', 'San Luis');
insert into CITY (Country_name, City_name) values ('Philippines', 'San Antonio');
insert into CITY (Country_name, City_name) values ('Philippines', 'Salogon');
insert into CITY (Country_name, City_name) values ('Philippines', 'Rimpeso');
insert into CITY (Country_name, City_name) values ('Philippines', 'Quiling');
insert into CITY (Country_name, City_name) values ('Philippines', 'Punolu');
insert into CITY (Country_name, City_name) values ('Philippines', 'Payao');
insert into CITY (Country_name, City_name) values ('Philippines', 'Panacan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Pag-asa');
insert into CITY (Country_name, City_name) values ('Philippines', 'Narvacan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Marihatag');
insert into CITY (Country_name, City_name) values ('Philippines', 'Marantao');
insert into CITY (Country_name, City_name) values ('Philippines', 'Manila');
insert into CITY (Country_name, City_name) values ('Philippines', 'Malway');
insert into CITY (Country_name, City_name) values ('Philippines', 'Malibago');
insert into CITY (Country_name, City_name) values ('Philippines', 'Maduao');
insert into CITY (Country_name, City_name) values ('Philippines', 'Lupo');
insert into CITY (Country_name, City_name) values ('Philippines', 'Leon Postigo');
insert into CITY (Country_name, City_name) values ('Philippines', 'Lanot');
insert into CITY (Country_name, City_name) values ('Philippines', 'Kalawit');
insert into CITY (Country_name, City_name) values ('Philippines', 'Kabuynan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Kabankalan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Kabalen');
insert into CITY (Country_name, City_name) values ('Philippines', 'Igang');
insert into CITY (Country_name, City_name) values ('Philippines', 'Guinticgan');
insert into CITY (Country_name, City_name) values ('Philippines', 'General Santos');
insert into CITY (Country_name, City_name) values ('Philippines', 'Gasan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Dulangan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Caticugan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Caromatan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Candijay');
insert into CITY (Country_name, City_name) values ('Philippines', 'Calubcub Dos');
insert into CITY (Country_name, City_name) values ('Philippines', 'Calaba');
insert into CITY (Country_name, City_name) values ('Philippines', 'Cabucgayan');
insert into CITY (Country_name, City_name) values ('Philippines', 'Cabaritan East');
insert into CITY (Country_name, City_name) values ('Philippines', 'Bundoc');
insert into CITY (Country_name, City_name) values ('Philippines', 'Buenavista');
insert into CITY (Country_name, City_name) values ('Philippines', 'Bilar');
insert into CITY (Country_name, City_name) values ('Philippines', 'Armenia');
insert into CITY (Country_name, City_name) values ('Philippines', 'Arcangel');
insert into CITY (Country_name, City_name) values ('Philippines', 'Amuñgan');
insert into CITY (Country_name, City_name) values ('Peru', 'Zarumilla');
insert into CITY (Country_name, City_name) values ('Peru', 'Yauca');
insert into CITY (Country_name, City_name) values ('Peru', 'San Pablo');
insert into CITY (Country_name, City_name) values ('Peru', 'Pampa Hermosa');
insert into CITY (Country_name, City_name) values ('Peru', 'El Carmen');
insert into CITY (Country_name, City_name) values ('Peru', 'Cuispes');
insert into CITY (Country_name, City_name) values ('Peru', 'Combapata');
insert into CITY (Country_name, City_name) values ('Peru', 'Changuillo');
insert into CITY (Country_name, City_name) values ('Peru', 'Asia');
insert into CITY (Country_name, City_name) values ('Paraguay', 'Paraguarí');
insert into CITY (Country_name, City_name) values ('Paraguay', 'Naranjal');
insert into CITY (Country_name, City_name) values ('Paraguay', 'Horqueta');
insert into CITY (Country_name, City_name) values ('Panama', 'Ustupo');
insert into CITY (Country_name, City_name) values ('Panama', 'Puerto Obaldía');
insert into CITY (Country_name, City_name) values ('Panama', 'Mulatupo');
insert into CITY (Country_name, City_name) values ('Panama', 'Chepo');
insert into CITY (Country_name, City_name) values ('Panama', 'Alto del Espino');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Yāsūf');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Ţūlkarm');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Quşrah');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Majdal Banī Fāḑil');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Imrīsh');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Iktābah');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Bazzāryah');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Bayt ‘Ūr at Taḩtā');
insert into CITY (Country_name, City_name) values ('Palestinian Territory', 'Azun Atme');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Mithi');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Keti Bandar');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Jarānwāla');
insert into CITY (Country_name, City_name) values ('Pakistan', 'Jalālpur Pīrwāla');
insert into CITY (Country_name, City_name) values ('Oman', '‘Ibrī');
insert into CITY (Country_name, City_name) values ('Norway', 'Oslo');
insert into CITY (Country_name, City_name) values ('Norway', 'Hønefoss');
insert into CITY (Country_name, City_name) values ('Norway', 'Fyllingsdalen');
insert into CITY (Country_name, City_name) values ('Norway', 'Drammen');
insert into CITY (Country_name, City_name) values ('North Korea', 'Sunan');
insert into CITY (Country_name, City_name) values ('North Korea', 'Sŏnbong');
insert into CITY (Country_name, City_name) values ('Northern Mariana Islands', 'San Jose Village');
insert into CITY (Country_name, City_name) values ('Northern Mariana Islands', 'Saipan');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Yola');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Sokoto');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Owo');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Obollo-Afor');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Maru');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Iwo');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Anka');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Amassoma');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Abonnema');
insert into CITY (Country_name, City_name) values ('Nigeria', 'Abakaliki');
insert into CITY (Country_name, City_name) values ('Niger', 'Agadez');
insert into CITY (Country_name, City_name) values ('Nicaragua', 'Valle San Francisco');
insert into CITY (Country_name, City_name) values ('New Zealand', 'Thames');
insert into CITY (Country_name, City_name) values ('New Zealand', 'Moerewa');
insert into CITY (Country_name, City_name) values ('Netherlands', 'Tilburg');
insert into CITY (Country_name, City_name) values ('Netherlands', 'Haarlem');
insert into CITY (Country_name, City_name) values ('Nepal', 'Jomsom');
insert into CITY (Country_name, City_name) values ('Namibia', 'Rehoboth');
insert into CITY (Country_name, City_name) values ('Namibia', 'Okahandja');
insert into CITY (Country_name, City_name) values ('Morocco', 'Tizguine');
insert into CITY (Country_name, City_name) values ('Morocco', 'Taza');
insert into CITY (Country_name, City_name) values ('Morocco', 'Tata');
insert into CITY (Country_name, City_name) values ('Morocco', 'Sidi Smaïl');
insert into CITY (Country_name, City_name) values ('Morocco', 'Ouijjane');
insert into CITY (Country_name, City_name) values ('Morocco', 'Martil');
insert into CITY (Country_name, City_name) values ('Morocco', 'Boulaouane');
insert into CITY (Country_name, City_name) values ('Montenegro', 'Ulcinj');
insert into CITY (Country_name, City_name) values ('Montenegro', 'Tivat');
insert into CITY (Country_name, City_name) values ('Montenegro', 'Bijela');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Rashaant');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Javhlant');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Jargalant');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Hoolt');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Hongor');
insert into CITY (Country_name, City_name) values ('Mongolia', 'Altanbulag');
insert into CITY (Country_name, City_name) values ('Moldova', 'Chişinău');
insert into CITY (Country_name, City_name) values ('Mexico', 'Venustiano Carranza');
insert into CITY (Country_name, City_name) values ('Mexico', 'San Sebastian');
insert into CITY (Country_name, City_name) values ('Mexico', 'San Rafael');
insert into CITY (Country_name, City_name) values ('Mexico', 'San Jose');
insert into CITY (Country_name, City_name) values ('Mexico', 'San Francisco');
insert into CITY (Country_name, City_name) values ('Mexico', 'San Antonio');
insert into CITY (Country_name, City_name) values ('Mexico', 'Miguel Hidalgo');
insert into CITY (Country_name, City_name) values ('Mexico', 'Lazaro Cardenas');
insert into CITY (Country_name, City_name) values ('Mexico', 'La Joya');
insert into CITY (Country_name, City_name) values ('Mexico', 'El Porvenir');
insert into CITY (Country_name, City_name) values ('Mauritius', 'Providence');
insert into CITY (Country_name, City_name) values ('Mauritius', 'Cluny');
insert into CITY (Country_name, City_name) values ('Mauritius', 'Centre de Flacq');
insert into CITY (Country_name, City_name) values ('Malta', 'Attard');
insert into CITY (Country_name, City_name) values ('Mali', 'Gao');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Shah Alam');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Sandakan');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Kota Kinabalu');
insert into CITY (Country_name, City_name) values ('Malaysia', 'Kota Bharu');
insert into CITY (Country_name, City_name) values ('Malawi', 'Blantyre');
insert into CITY (Country_name, City_name) values ('Madagascar', 'Tsiroanomandidy');
insert into CITY (Country_name, City_name) values ('Madagascar', 'Soavinandriana');
insert into CITY (Country_name, City_name) values ('Madagascar', 'Marolambo');
insert into CITY (Country_name, City_name) values ('Madagascar', 'Antalaha');
insert into CITY (Country_name, City_name) values ('Madagascar', 'Ambositra');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Ростуша');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Poroj');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Kamenjane');
insert into CITY (Country_name, City_name) values ('Macedonia', 'Dobrošte');
insert into CITY (Country_name, City_name) values ('Luxembourg', 'Larochette');
insert into CITY (Country_name, City_name) values ('Luxembourg', 'Fentange');
insert into CITY (Country_name, City_name) values ('Libya', 'Nālūt');
insert into CITY (Country_name, City_name) values ('Lebanon', 'Sîr ed Danniyé');
insert into CITY (Country_name, City_name) values ('Latvia', 'Inčukalns');
insert into CITY (Country_name, City_name) values ('Latvia', 'Bolderaja');
insert into CITY (Country_name, City_name) values ('Latvia', 'Baldone');
insert into CITY (Country_name, City_name) values ('Kyrgyzstan', 'At-Bashi');
insert into CITY (Country_name, City_name) values ('Kuwait', 'Al Jahrā’');
insert into CITY (Country_name, City_name) values ('Kuwait', 'Ad Dasmah');
insert into CITY (Country_name, City_name) values ('Kosovo', 'Prizren');
insert into CITY (Country_name, City_name) values ('Kenya', 'Molo');
insert into CITY (Country_name, City_name) values ('Kazakhstan', 'Ordzhonikidze');
insert into CITY (Country_name, City_name) values ('Kazakhstan', 'Moyynkum');
insert into CITY (Country_name, City_name) values ('Kazakhstan', 'Merke');
insert into CITY (Country_name, City_name) values ('Kazakhstan', 'Ekibastuz');
insert into CITY (Country_name, City_name) values ('Jordan', 'Safi');
insert into CITY (Country_name, City_name) values ('Jordan', 'Ḩātim');
insert into CITY (Country_name, City_name) values ('Jordan', 'Ḩakamā');
insert into CITY (Country_name, City_name) values ('Japan', 'Uwajima');
insert into CITY (Country_name, City_name) values ('Japan', 'Shimo-furano');
insert into CITY (Country_name, City_name) values ('Japan', 'Sandachō');
insert into CITY (Country_name, City_name) values ('Japan', 'Okazaki');
insert into CITY (Country_name, City_name) values ('Japan', 'Mitaka-shi');
insert into CITY (Country_name, City_name) values ('Japan', 'Marugame');
insert into CITY (Country_name, City_name) values ('Japan', 'Ishige');
insert into CITY (Country_name, City_name) values ('Japan', 'Handa');
insert into CITY (Country_name, City_name) values ('Japan', 'Gosen');
insert into CITY (Country_name, City_name) values ('Japan', 'Edosaki');
insert into CITY (Country_name, City_name) values ('Japan', 'Akune');
insert into CITY (Country_name, City_name) values ('Jamaica', 'Yallahs');
insert into CITY (Country_name, City_name) values ('Ivory Coast', 'Akoupé');
insert into CITY (Country_name, City_name) values ('Israel', 'Ḥurfeish');
insert into CITY (Country_name, City_name) values ('Israel', '‘Arad');
insert into CITY (Country_name, City_name) values ('Ireland', 'Macroom');
insert into CITY (Country_name, City_name) values ('Ireland', 'Listowel');
insert into CITY (Country_name, City_name) values ('Ireland', 'Kinsale');
insert into CITY (Country_name, City_name) values ('Ireland', 'Enniskerry');
insert into CITY (Country_name, City_name) values ('Ireland', 'Dunmanway');
insert into CITY (Country_name, City_name) values ('Ireland', 'Ballinteer');
insert into CITY (Country_name, City_name) values ('Iraq', 'Zākhū');
insert into CITY (Country_name, City_name) values ('Iran', 'Zarrīn Shahr');
insert into CITY (Country_name, City_name) values ('Iran', 'Tonekābon');
insert into CITY (Country_name, City_name) values ('Iran', 'Sūrīān');
insert into CITY (Country_name, City_name) values ('Iran', 'Javānrūd');
insert into CITY (Country_name, City_name) values ('Iran', 'Chenārān');
insert into CITY (Country_name, City_name) values ('Iran', 'Bāgh-e Malek');
insert into CITY (Country_name, City_name) values ('Iran', 'Anār');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wonosobo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wolowiro');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wirodayan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Watulabara');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wangi');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Waimangura');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Wahawaha');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ulee Gle');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Uitiuhtuan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tulusmulyo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tempuran');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Telukpakedai');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tawangsari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Tangkanpulit');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Takokak');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sumberpucung');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sukamulia');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sukamaju');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sukadana');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sukabatu');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sifala');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sidomulyo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Seririt');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sedandang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sarae');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Sampit');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Randuboto');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Rancamaya');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pumai');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Prantaan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Penanggapan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pasirbatang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pasinan Barat');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pamedaran');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pakuncen');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pakis');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Pakemitan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Padangbai');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Orong');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ngreco');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Naikolan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Nagasari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Naebugis');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Muting');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Montasik');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Mliwang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Merapit');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Mandapajaya');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Maliiha');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Lirung');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Labangka Satu');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kubang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Krebet');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Krajan Kedungsalam');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Krajan Keboromo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kotingnatagete');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kiarajangkung');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kertanegla');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kertamukti');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kawalimukti');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Karangtengah');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kandang Timur');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kalijeruk');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Kaem');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jurak Lao’');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jenang Selatan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jembatandua');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jatisari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Japerejo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Jalupang Dua');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Hegarsari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gunungkoneng');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gunem');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gersikputih Tengah');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Genteng');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Gareba');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Garahan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Galubakul');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Dukuhturi');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Dodol');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Detusoko');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Ciudian');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cisaat');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cipatujah');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cimaragas');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cihaur');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cigembor');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Cibingbin');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Brondong');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Boro Utara');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bojonggenteng');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bogorejo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bogorame');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Biting');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Birowo');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bidikotak');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Beraim');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Batawa');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Batang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Banyutengah');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Banjar Yehsatang');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bandungsari');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bakaran Kulon');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Bagok');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Babakanjaya');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Angan');
insert into CITY (Country_name, City_name) values ('Indonesia', 'Amerta');
insert into CITY (Country_name, City_name) values ('Hungary', 'Szeged');
insert into CITY (Country_name, City_name) values ('Hungary', 'Ózd');
insert into CITY (Country_name, City_name) values ('Hungary', 'Kecskemét');
insert into CITY (Country_name, City_name) values ('Honduras', 'San Diego');
insert into CITY (Country_name, City_name) values ('Honduras', 'Campamento');
insert into CITY (Country_name, City_name) values ('Honduras', 'Aramecina');
insert into CITY (Country_name, City_name) values ('Guinea', 'Fria');
insert into CITY (Country_name, City_name) values ('Guatemala', 'Santa Bárbara');
insert into CITY (Country_name, City_name) values ('Guatemala', 'Patulul');
insert into CITY (Country_name, City_name) values ('Guatemala', 'El Estor');
insert into CITY (Country_name, City_name) values ('Guam', 'Asan-Maina Village');
insert into CITY (Country_name, City_name) values ('Greenland', 'Uummannaq');
insert into CITY (Country_name, City_name) values ('Greenland', 'Aasiaat');
insert into CITY (Country_name, City_name) values ('Greece', 'Valsamáta');
insert into CITY (Country_name, City_name) values ('Greece', 'Palaiochóri');
insert into CITY (Country_name, City_name) values ('Greece', 'Nigríta');
insert into CITY (Country_name, City_name) values ('Greece', 'Néa Manolás');
insert into CITY (Country_name, City_name) values ('Greece', 'Néa Karváli');
insert into CITY (Country_name, City_name) values ('Greece', 'Lianokládhion');
insert into CITY (Country_name, City_name) values ('Greece', 'Katoúna');
insert into CITY (Country_name, City_name) values ('Greece', 'Episkopí');
insert into CITY (Country_name, City_name) values ('Ghana', 'Konongo');
insert into CITY (Country_name, City_name) values ('Germany', 'Hamburg Winterhude');
insert into CITY (Country_name, City_name) values ('Germany', 'Berlin');
insert into CITY (Country_name, City_name) values ('Germany', 'Aachen');
insert into CITY (Country_name, City_name) values ('Georgia', 'Kelasuri');
insert into CITY (Country_name, City_name) values ('Georgia', 'Gudauta');
insert into CITY (Country_name, City_name) values ('Gambia', 'Kass Wollof');
insert into CITY (Country_name, City_name) values ('Gambia', 'Georgetown');
insert into CITY (Country_name, City_name) values ('French Polynesia', 'Faaone');
insert into CITY (Country_name, City_name) values ('France', 'Villeurbanne');
insert into CITY (Country_name, City_name) values ('France', 'Vichy');
insert into CITY (Country_name, City_name) values ('France', 'Valenciennes');
insert into CITY (Country_name, City_name) values ('France', 'Valence');
insert into CITY (Country_name, City_name) values ('France', 'Toulouse');
insert into CITY (Country_name, City_name) values ('France', 'Saint-Lô');
insert into CITY (Country_name, City_name) values ('France', 'Saint-Étienne');
insert into CITY (Country_name, City_name) values ('France', 'Rouen');
insert into CITY (Country_name, City_name) values ('France', 'Port-de-Bouc');
insert into CITY (Country_name, City_name) values ('France', 'Paris 10');
insert into CITY (Country_name, City_name) values ('France', 'Paris 08');
insert into CITY (Country_name, City_name) values ('France', 'Orly aérogare');
insert into CITY (Country_name, City_name) values ('France', 'Neuilly-sur-Marne');
insert into CITY (Country_name, City_name) values ('France', 'Nantes');
insert into CITY (Country_name, City_name) values ('France', 'Mulhouse');
insert into CITY (Country_name, City_name) values ('France', 'Mirecourt');
insert into CITY (Country_name, City_name) values ('France', 'Méru');
insert into CITY (Country_name, City_name) values ('France', 'Meaux');
insert into CITY (Country_name, City_name) values ('France', 'Massy');
insert into CITY (Country_name, City_name) values ('France', 'Marseille');
insert into CITY (Country_name, City_name) values ('France', 'Marne-la-Vallée');
insert into CITY (Country_name, City_name) values ('France', 'Les Clayes-sous-Bois');
insert into CITY (Country_name, City_name) values ('France', 'Lattes');
insert into CITY (Country_name, City_name) values ('France', 'Guyancourt');
insert into CITY (Country_name, City_name) values ('France', 'Grenoble');
insert into CITY (Country_name, City_name) values ('France', 'Croix');
insert into CITY (Country_name, City_name) values ('France', 'Clichy');
insert into CITY (Country_name, City_name) values ('France', 'Bourges');
insert into CITY (Country_name, City_name) values ('France', 'Amiens');
insert into CITY (Country_name, City_name) values ('France', 'Altkirch');
insert into CITY (Country_name, City_name) values ('Finland', 'Pyhäranta');
insert into CITY (Country_name, City_name) values ('Finland', 'Orimattila');
insert into CITY (Country_name, City_name) values ('Finland', 'Leppävirta');
insert into CITY (Country_name, City_name) values ('Finland', 'Kouvola');
insert into CITY (Country_name, City_name) values ('Finland', 'Koukkuniemi');
insert into CITY (Country_name, City_name) values ('Finland', 'Kittilä');
insert into CITY (Country_name, City_name) values ('Finland', 'Ilmajoki');
insert into CITY (Country_name, City_name) values ('Finland', 'Hausjärvi');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Ziway');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Tippi');
insert into CITY (Country_name, City_name) values ('Ethiopia', 'Felege Neway');
insert into CITY (Country_name, City_name) values ('Estonia', 'Pärnu');
insert into CITY (Country_name, City_name) values ('Egypt', 'Siwa Oasis');
insert into CITY (Country_name, City_name) values ('Ecuador', 'Cayambe');
insert into CITY (Country_name, City_name) values ('Dominican Republic', 'Juan Santiago');
insert into CITY (Country_name, City_name) values ('Dominican Republic', 'Esperalvillo');
insert into CITY (Country_name, City_name) values ('Denmark', 'København');
insert into CITY (Country_name, City_name) values ('Democratic Republic of the Congo', 'Mweka');
insert into CITY (Country_name, City_name) values ('Democratic Republic of the Congo', 'Mangai');
insert into CITY (Country_name, City_name) values ('Democratic Republic of the Congo', 'Kindu');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Zliv');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Všenory');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Velké Němčice');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Ústí nad Labem');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Trnava');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Šluknov');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Slavkov u Brna');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Radvanice');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Ostrožská Nová Ves');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Milín');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Lipník nad Bečvou');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Lípa');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Kájov');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Horní Jelení');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Heřmanova Huť');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Hazlov');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Havlíčkův Brod');
insert into CITY (Country_name, City_name) values ('Czech Republic', 'Dolní Lhota');
insert into CITY (Country_name, City_name) values ('Cyprus', 'Famagusta');
insert into CITY (Country_name, City_name) values ('Cuba', 'San José de las Lajas');
insert into CITY (Country_name, City_name) values ('Cuba', 'Minas de Matahambre');
insert into CITY (Country_name, City_name) values ('Cuba', 'Bartolomé Masó');
insert into CITY (Country_name, City_name) values ('Cuba', 'Arroyo Naranjo');
insert into CITY (Country_name, City_name) values ('Croatia', 'Viškovci');
insert into CITY (Country_name, City_name) values ('Croatia', 'Oštarije');
insert into CITY (Country_name, City_name) values ('Croatia', 'Grubišno Polje');
insert into CITY (Country_name, City_name) values ('Croatia', 'Gračec');
insert into CITY (Country_name, City_name) values ('Costa Rica', 'San Rafael');
insert into CITY (Country_name, City_name) values ('Costa Rica', 'Calle Blancos');
insert into CITY (Country_name, City_name) values ('Comoros', 'Mavingouni');
insert into CITY (Country_name, City_name) values ('Colombia', 'Urrao');
insert into CITY (Country_name, City_name) values ('Colombia', 'Riofrío');
insert into CITY (Country_name, City_name) values ('Colombia', 'Paicol');
insert into CITY (Country_name, City_name) values ('Colombia', 'Murindó');
insert into CITY (Country_name, City_name) values ('Colombia', 'Melgar');
insert into CITY (Country_name, City_name) values ('Colombia', 'Manzanares');
insert into CITY (Country_name, City_name) values ('Colombia', 'Guachucal');
insert into CITY (Country_name, City_name) values ('Colombia', 'Girón');
insert into CITY (Country_name, City_name) values ('Colombia', 'Fresno');
insert into CITY (Country_name, City_name) values ('Colombia', 'El Cerrito');
insert into CITY (Country_name, City_name) values ('Colombia', 'Distracción');
insert into CITY (Country_name, City_name) values ('Colombia', 'Coromoro');
insert into CITY (Country_name, City_name) values ('Colombia', 'Chaguaní');
insert into CITY (Country_name, City_name) values ('China', 'Zoushi');
insert into CITY (Country_name, City_name) values ('China', 'Zhuyang');
insert into CITY (Country_name, City_name) values ('China', 'Zhongxin');
insert into CITY (Country_name, City_name) values ('China', 'Zhonghe');
insert into CITY (Country_name, City_name) values ('China', 'Zhongchao');
insert into CITY (Country_name, City_name) values ('China', 'Zhaizigou');
insert into CITY (Country_name, City_name) values ('China', 'Zaoxi');
insert into CITY (Country_name, City_name) values ('China', 'Yushugou');
insert into CITY (Country_name, City_name) values ('China', 'Yujin');
insert into CITY (Country_name, City_name) values ('China', 'Yucheng');
insert into CITY (Country_name, City_name) values ('China', 'Yuanquan');
insert into CITY (Country_name, City_name) values ('China', 'Youdunjie');
insert into CITY (Country_name, City_name) values ('China', 'Yongledian');
insert into CITY (Country_name, City_name) values ('China', 'Yong’an');
insert into CITY (Country_name, City_name) values ('China', 'Yingtou');
insert into CITY (Country_name, City_name) values ('China', 'Yiliu');
insert into CITY (Country_name, City_name) values ('China', 'Yezhi');
insert into CITY (Country_name, City_name) values ('China', 'Yatunpu');
insert into CITY (Country_name, City_name) values ('China', 'Yanyang');
insert into CITY (Country_name, City_name) values ('China', 'Yanmenkou');
insert into CITY (Country_name, City_name) values ('China', 'Yanliang');
insert into CITY (Country_name, City_name) values ('China', 'Xujiadian');
insert into CITY (Country_name, City_name) values ('China', 'Xiyang');
insert into CITY (Country_name, City_name) values ('China', 'Xiumei');
insert into CITY (Country_name, City_name) values ('China', 'Xinxing');
insert into CITY (Country_name, City_name) values ('China', 'Xinminxiang');
insert into CITY (Country_name, City_name) values ('China', 'Xingren');
insert into CITY (Country_name, City_name) values ('China', 'Xingou');
insert into CITY (Country_name, City_name) values ('China', 'Xin Bulag');
insert into CITY (Country_name, City_name) values ('China', 'Xifengshan');
insert into CITY (Country_name, City_name) values ('China', 'Xiejia');
insert into CITY (Country_name, City_name) values ('China', 'Xiasi');
insert into CITY (Country_name, City_name) values ('China', 'Xiaoshi');
insert into CITY (Country_name, City_name) values ('China', 'Xian’an');
insert into CITY (Country_name, City_name) values ('China', 'Wuyang');
insert into CITY (Country_name, City_name) values ('China', 'Wenxing');
insert into CITY (Country_name, City_name) values ('China', 'Wenheng');
insert into CITY (Country_name, City_name) values ('China', 'Tunggar');
insert into CITY (Country_name, City_name) values ('China', 'Tonghu');
insert into CITY (Country_name, City_name) values ('China', 'Tiebukenwusan');
insert into CITY (Country_name, City_name) values ('China', 'Tanxi');
insert into CITY (Country_name, City_name) values ('China', 'Tangxing');
insert into CITY (Country_name, City_name) values ('China', 'Sucun');
insert into CITY (Country_name, City_name) values ('China', 'Shuitianzhuang');
insert into CITY (Country_name, City_name) values ('China', 'Shuidun');
insert into CITY (Country_name, City_name) values ('China', 'Shuibatang');
insert into CITY (Country_name, City_name) values ('China', 'Shuhong');
insert into CITY (Country_name, City_name) values ('China', 'Shuangjiang');
insert into CITY (Country_name, City_name) values ('China', 'Shuanghe');
insert into CITY (Country_name, City_name) values ('China', 'Shitang');
insert into CITY (Country_name, City_name) values ('China', 'Shiquan');
insert into CITY (Country_name, City_name) values ('China', 'Shiqian');
insert into CITY (Country_name, City_name) values ('China', 'Shilin');
insert into CITY (Country_name, City_name) values ('China', 'Shifo');
insert into CITY (Country_name, City_name) values ('China', 'Shaogongzhuang');
insert into CITY (Country_name, City_name) values ('China', 'Sanyang');
insert into CITY (Country_name, City_name) values ('China', 'Sanshilipu');
insert into CITY (Country_name, City_name) values ('China', 'Sanjiangkou');
insert into CITY (Country_name, City_name) values ('China', 'Sanhe');
insert into CITY (Country_name, City_name) values ('China', 'Qingyun');
insert into CITY (Country_name, City_name) values ('China', 'Qingqu');
insert into CITY (Country_name, City_name) values ('China', 'Qifang');
insert into CITY (Country_name, City_name) values ('China', 'Qiansuo');
insert into CITY (Country_name, City_name) values ('China', 'Pingxiang');
insert into CITY (Country_name, City_name) values ('China', 'Pingshan');
insert into CITY (Country_name, City_name) values ('China', 'Pingdong');
insert into CITY (Country_name, City_name) values ('China', 'Pingdi');
insert into CITY (Country_name, City_name) values ('China', 'Ningmute');
insert into CITY (Country_name, City_name) values ('China', 'Nanxinxiang');
insert into CITY (Country_name, City_name) values ('China', 'Nangxian');
insert into CITY (Country_name, City_name) values ('China', 'Mizhou');
insert into CITY (Country_name, City_name) values ('China', 'Mishixiang');
insert into CITY (Country_name, City_name) values ('China', 'Miliangju');
insert into CITY (Country_name, City_name) values ('China', 'Mianduhe');
insert into CITY (Country_name, City_name) values ('China', 'Mentougou');
insert into CITY (Country_name, City_name) values ('China', 'Mazongling');
insert into CITY (Country_name, City_name) values ('China', 'Maxiao');
insert into CITY (Country_name, City_name) values ('China', 'Matangshan');
insert into CITY (Country_name, City_name) values ('China', 'Majiao');
insert into CITY (Country_name, City_name) values ('China', 'Ma’an');
insert into CITY (Country_name, City_name) values ('China', 'Luoxiong');
insert into CITY (Country_name, City_name) values ('China', 'Luoqiao');
insert into CITY (Country_name, City_name) values ('China', 'Luocheng');
insert into CITY (Country_name, City_name) values ('China', 'Louguan');
insert into CITY (Country_name, City_name) values ('China', 'Longzhouwan');
insert into CITY (Country_name, City_name) values ('China', 'Longwan');
insert into CITY (Country_name, City_name) values ('China', 'Liyuan');
insert into CITY (Country_name, City_name) values ('China', 'Liuhuang');
insert into CITY (Country_name, City_name) values ('China', 'Liufang');
insert into CITY (Country_name, City_name) values ('China', 'Liucheng');
insert into CITY (Country_name, City_name) values ('China', 'Linjiang');
insert into CITY (Country_name, City_name) values ('China', 'Licheng');
insert into CITY (Country_name, City_name) values ('China', 'Lianran');
insert into CITY (Country_name, City_name) values ('China', 'Lian’an');
insert into CITY (Country_name, City_name) values ('China', 'Lengji');
insert into CITY (Country_name, City_name) values ('China', 'Layu');
insert into CITY (Country_name, City_name) values ('China', 'Laocheng');
insert into CITY (Country_name, City_name) values ('China', 'Langjun');
insert into CITY (Country_name, City_name) values ('China', 'Laiyuan');
insert into CITY (Country_name, City_name) values ('China', 'Kuntong');
insert into CITY (Country_name, City_name) values ('China', 'Konggar');
insert into CITY (Country_name, City_name) values ('China', 'Kaiyun');
insert into CITY (Country_name, City_name) values ('China', 'Kaiyuan');
insert into CITY (Country_name, City_name) values ('China', 'Juexi');
insert into CITY (Country_name, City_name) values ('China', 'Jiujie');
insert into CITY (Country_name, City_name) values ('China', 'Jinquan');
insert into CITY (Country_name, City_name) values ('China', 'Jinping');
insert into CITY (Country_name, City_name) values ('China', 'Jingdezhen');
insert into CITY (Country_name, City_name) values ('China', 'Jincheng');
insert into CITY (Country_name, City_name) values ('China', 'Jieshan');
insert into CITY (Country_name, City_name) values ('China', 'Jiepai');
insert into CITY (Country_name, City_name) values ('China', 'Jiekeng');
insert into CITY (Country_name, City_name) values ('China', 'Jiaotang');
insert into CITY (Country_name, City_name) values ('China', 'Jiaoshanhe');
insert into CITY (Country_name, City_name) values ('China', 'Jiaocun');
insert into CITY (Country_name, City_name) values ('China', 'Jianshan');
insert into CITY (Country_name, City_name) values ('China', 'Jialou');
insert into CITY (Country_name, City_name) values ('China', 'Jagistay');
insert into CITY (Country_name, City_name) values ('China', 'Huolu');
insert into CITY (Country_name, City_name) values ('China', 'Huitang');
insert into CITY (Country_name, City_name) values ('China', 'Huangwan');
insert into CITY (Country_name, City_name) values ('China', 'Huangshagang');
insert into CITY (Country_name, City_name) values ('China', 'Huangsangkou');
insert into CITY (Country_name, City_name) values ('China', 'Huanglong');
insert into CITY (Country_name, City_name) values ('China', 'Huangcun');
insert into CITY (Country_name, City_name) values ('China', 'Huai’an');
insert into CITY (Country_name, City_name) values ('China', 'Huaguo');
insert into CITY (Country_name, City_name) values ('China', 'Hong’an');
insert into CITY (Country_name, City_name) values ('China', 'Hezhi');
insert into CITY (Country_name, City_name) values ('China', 'Hepu');
insert into CITY (Country_name, City_name) values ('China', 'Hengzhou');
insert into CITY (Country_name, City_name) values ('China', 'Hema');
insert into CITY (Country_name, City_name) values ('China', 'Guishan');
insert into CITY (Country_name, City_name) values ('China', 'Guantian');
insert into CITY (Country_name, City_name) values ('China', 'Gengwan');
insert into CITY (Country_name, City_name) values ('China', 'Gedaliang');
insert into CITY (Country_name, City_name) values ('China', 'Gaoxu');
insert into CITY (Country_name, City_name) values ('China', 'Gaoxing');
insert into CITY (Country_name, City_name) values ('China', 'Gannan');
insert into CITY (Country_name, City_name) values ('China', 'Gangou');
insert into CITY (Country_name, City_name) values ('China', 'Fuxin');
insert into CITY (Country_name, City_name) values ('China', 'Futian');
insert into CITY (Country_name, City_name) values ('China', 'Fengxi');
insert into CITY (Country_name, City_name) values ('China', 'Fenglin');
insert into CITY (Country_name, City_name) values ('China', 'Fengcheng');
insert into CITY (Country_name, City_name) values ('China', 'Fenchen');
insert into CITY (Country_name, City_name) values ('China', 'Fangxi');
insert into CITY (Country_name, City_name) values ('China', 'Erdaohe');
insert into CITY (Country_name, City_name) values ('China', 'Enshi');
insert into CITY (Country_name, City_name) values ('China', 'Enhe Hada');
insert into CITY (Country_name, City_name) values ('China', 'Dougou');
insert into CITY (Country_name, City_name) values ('China', 'Dongsheng');
insert into CITY (Country_name, City_name) values ('China', 'Dongjin');
insert into CITY (Country_name, City_name) values ('China', 'Donghai');
insert into CITY (Country_name, City_name) values ('China', 'Dongchuan');
insert into CITY (Country_name, City_name) values ('China', 'Dingzigu');
insert into CITY (Country_name, City_name) values ('China', 'Derbur');
insert into CITY (Country_name, City_name) values ('China', 'Dazi');
insert into CITY (Country_name, City_name) values ('China', 'Dazhipo');
insert into CITY (Country_name, City_name) values ('China', 'Dayingjie');
insert into CITY (Country_name, City_name) values ('China', 'Dayangzhou');
insert into CITY (Country_name, City_name) values ('China', 'Dawan');
insert into CITY (Country_name, City_name) values ('China', 'Dalinhe');
insert into CITY (Country_name, City_name) values ('China', 'Dake');
insert into CITY (Country_name, City_name) values ('China', 'Chiguang');
insert into CITY (Country_name, City_name) values ('China', 'Chengzhong');
insert into CITY (Country_name, City_name) values ('China', 'Chengtian');
insert into CITY (Country_name, City_name) values ('China', 'Chengjiang');
insert into CITY (Country_name, City_name) values ('China', 'Chalu');
insert into CITY (Country_name, City_name) values ('China', 'Chahannao');
insert into CITY (Country_name, City_name) values ('China', 'Caicun');
insert into CITY (Country_name, City_name) values ('China', 'Biguo');
insert into CITY (Country_name, City_name) values ('China', 'Beishan');
insert into CITY (Country_name, City_name) values ('China', 'Bei’an');
insert into CITY (Country_name, City_name) values ('China', 'Bayanbaogede');
insert into CITY (Country_name, City_name) values ('China', 'Batan');
insert into CITY (Country_name, City_name) values ('China', 'Baliang');
insert into CITY (Country_name, City_name) values ('China', 'Baiyushan');
insert into CITY (Country_name, City_name) values ('China', 'Baixi');
insert into CITY (Country_name, City_name) values ('China', 'Baimajing');
insert into CITY (Country_name, City_name) values ('China', 'Anzi');
insert into CITY (Country_name, City_name) values ('Chile', 'Salamanca');
insert into CITY (Country_name, City_name) values ('Chile', 'Puerto Quellón');
insert into CITY (Country_name, City_name) values ('Chile', 'Puerto Aisén');
insert into CITY (Country_name, City_name) values ('Chile', 'Los Andes');
insert into CITY (Country_name, City_name) values ('Chile', 'Concepción');
insert into CITY (Country_name, City_name) values ('Chad', 'Doba');
insert into CITY (Country_name, City_name) values ('Chad', 'Bousso');
insert into CITY (Country_name, City_name) values ('Central African Republic', 'Ndélé');
insert into CITY (Country_name, City_name) values ('Canada', 'White City');
insert into CITY (Country_name, City_name) values ('Canada', 'Stony Plain');
insert into CITY (Country_name, City_name) values ('Canada', 'Sicamous');
insert into CITY (Country_name, City_name) values ('Canada', 'Saint-Félicien');
insert into CITY (Country_name, City_name) values ('Canada', 'Saint-Bruno-de-Montarville');
insert into CITY (Country_name, City_name) values ('Canada', 'Repentigny');
insert into CITY (Country_name, City_name) values ('Canada', 'Prince Rupert');
insert into CITY (Country_name, City_name) values ('Canada', 'Prince Albert');
insert into CITY (Country_name, City_name) values ('Canada', 'Port Hawkesbury');
insert into CITY (Country_name, City_name) values ('Canada', 'Pincher Creek');
insert into CITY (Country_name, City_name) values ('Canada', 'Papineauville');
insert into CITY (Country_name, City_name) values ('Canada', 'Omemee');
insert into CITY (Country_name, City_name) values ('Canada', 'North Cowichan');
insert into CITY (Country_name, City_name) values ('Canada', 'Lanigan');
insert into CITY (Country_name, City_name) values ('Canada', 'Lambton Shores');
insert into CITY (Country_name, City_name) values ('Canada', 'Kitimat');
insert into CITY (Country_name, City_name) values ('Canada', 'Cochrane');
insert into CITY (Country_name, City_name) values ('Canada', 'Coaticook');
insert into CITY (Country_name, City_name) values ('Cameroon', 'Fundong');
insert into CITY (Country_name, City_name) values ('Cameroon', 'Diang');
insert into CITY (Country_name, City_name) values ('Burundi', 'Ruyigi');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Vidin');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Sofia');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Simitli');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Pŭrvomaytsi');
insert into CITY (Country_name, City_name) values ('Bulgaria', 'Balgarevo');
insert into CITY (Country_name, City_name) values ('Brazil', 'Votuporanga');
insert into CITY (Country_name, City_name) values ('Brazil', 'Veranópolis');
insert into CITY (Country_name, City_name) values ('Brazil', 'Várzea da Palma');
insert into CITY (Country_name, City_name) values ('Brazil', 'Tupanciretã');
insert into CITY (Country_name, City_name) values ('Brazil', 'Santana do Livramento');
insert into CITY (Country_name, City_name) values ('Brazil', 'Santa Cruz do Capibaribe');
insert into CITY (Country_name, City_name) values ('Brazil', 'Propriá');
insert into CITY (Country_name, City_name) values ('Brazil', 'Petrópolis');
insert into CITY (Country_name, City_name) values ('Brazil', 'Pancas');
insert into CITY (Country_name, City_name) values ('Brazil', 'Palmital');
insert into CITY (Country_name, City_name) values ('Brazil', 'Nossa Senhora do Socorro');
insert into CITY (Country_name, City_name) values ('Brazil', 'Marília');
insert into CITY (Country_name, City_name) values ('Brazil', 'Lençóis Paulista');
insert into CITY (Country_name, City_name) values ('Brazil', 'João Alfredo');
insert into CITY (Country_name, City_name) values ('Brazil', 'Itatiba');
insert into CITY (Country_name, City_name) values ('Brazil', 'Itaberaba');
insert into CITY (Country_name, City_name) values ('Brazil', 'Iguape');
insert into CITY (Country_name, City_name) values ('Brazil', 'Gameleira');
insert into CITY (Country_name, City_name) values ('Brazil', 'Freguesia do Ribeirao da Ilha');
insert into CITY (Country_name, City_name) values ('Brazil', 'Cruz Alta');
insert into CITY (Country_name, City_name) values ('Brazil', 'Coxim');
insert into CITY (Country_name, City_name) values ('Brazil', 'Coronel Vivida');
insert into CITY (Country_name, City_name) values ('Brazil', 'Charqueadas');
insert into CITY (Country_name, City_name) values ('Brazil', 'Carmo do Paranaíba');
insert into CITY (Country_name, City_name) values ('Brazil', 'Caçapava');
insert into CITY (Country_name, City_name) values ('Brazil', 'Buíque');
insert into CITY (Country_name, City_name) values ('Brazil', 'Bom Jesus dos Perdões');
insert into CITY (Country_name, City_name) values ('Brazil', 'Bela Vista');
insert into CITY (Country_name, City_name) values ('Brazil', 'Araucária');
insert into CITY (Country_name, City_name) values ('Botswana', 'Nokaneng');
insert into CITY (Country_name, City_name) values ('Botswana', 'Gobojango');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Tomislavgrad');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Kakanj');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Čelinac');
insert into CITY (Country_name, City_name) values ('Bosnia and Herzegovina', 'Brka');
insert into CITY (Country_name, City_name) values ('Bolivia', 'San Pedro');
insert into CITY (Country_name, City_name) values ('Bolivia', 'Las Carreras');
insert into CITY (Country_name, City_name) values ('Bhutan', 'Tsirang');
insert into CITY (Country_name, City_name) values ('Benin', 'Ouidah');
insert into CITY (Country_name, City_name) values ('Benin', 'Abomey');
insert into CITY (Country_name, City_name) values ('Belize', 'Belize City');
insert into CITY (Country_name, City_name) values ('Belarus', 'Pinsk');
insert into CITY (Country_name, City_name) values ('Bangladesh', 'Parbatipur');
insert into CITY (Country_name, City_name) values ('Bahrain', 'Sitrah');
insert into CITY (Country_name, City_name) values ('Azerbaijan', 'Yuxarı Aran');
insert into CITY (Country_name, City_name) values ('Azerbaijan', 'Digah');
insert into CITY (Country_name, City_name) values ('Austria', 'Kumberg');
insert into CITY (Country_name, City_name) values ('Armenia', 'Yerazgavors');
insert into CITY (Country_name, City_name) values ('Armenia', 'Mrganush');
insert into CITY (Country_name, City_name) values ('Armenia', 'Kamaris');
insert into CITY (Country_name, City_name) values ('Armenia', 'Hrazdan');
insert into CITY (Country_name, City_name) values ('Armenia', 'Getahovit');
insert into CITY (Country_name, City_name) values ('Armenia', 'Buzhakan');
insert into CITY (Country_name, City_name) values ('Armenia', 'Artashat');
insert into CITY (Country_name, City_name) values ('Argentina', 'San José de Jáchal');
insert into CITY (Country_name, City_name) values ('Argentina', 'Puerto Madryn');
insert into CITY (Country_name, City_name) values ('Argentina', 'Pilcaniyeu');
insert into CITY (Country_name, City_name) values ('Argentina', 'Paso de Indios');
insert into CITY (Country_name, City_name) values ('Argentina', 'Paraná');
insert into CITY (Country_name, City_name) values ('Argentina', 'Molinos');
insert into CITY (Country_name, City_name) values ('Argentina', 'Hermoso Campo');
insert into CITY (Country_name, City_name) values ('Argentina', 'General Alvear');
insert into CITY (Country_name, City_name) values ('Argentina', 'Empedrado');
insert into CITY (Country_name, City_name) values ('Argentina', 'Diamante');
insert into CITY (Country_name, City_name) values ('Argentina', 'Cerro Corá');
insert into CITY (Country_name, City_name) values ('Argentina', 'Catriló');
insert into CITY (Country_name, City_name) values ('Argentina', 'Buenos Aires');
insert into CITY (Country_name, City_name) values ('Argentina', 'Brea Pozo');
insert into CITY (Country_name, City_name) values ('Argentina', 'Alto Río Senguer');
insert into CITY (Country_name, City_name) values ('Angola', 'Catumbela');
insert into CITY (Country_name, City_name) values ('Albania', 'Sult');
insert into CITY (Country_name, City_name) values ('Albania', 'Qelëz');
insert into CITY (Country_name, City_name) values ('Albania', 'Lekaj');
insert into CITY (Country_name, City_name) values ('Albania', 'Korçë');
insert into CITY (Country_name, City_name) values ('Albania', 'Gosë e Madhe');
insert into CITY (Country_name, City_name) values ('Aland Islands', 'Geta');
insert into CITY (Country_name, City_name) values ('Afghanistan', 'Pas Pul');
insert into CITY (Country_name, City_name) values ('Afghanistan', 'Deh-e Now');
