CREATE OR ALTER PROCEDURE GET_SELECTION_CLUB_OF_EDITION
(@club CLUB_NAME, @competition COMPETITION_NAME, @season SEASON_NAME)
AS BEGIN
	SELECT p.PERSON_ID, per.FIRST_NAME, per.MIDDLE_NAME, per.LAST_NAME, per.BIRTH_DATE FROM ALL_PLAYERS_EDITIONS ape 
	JOIN PLAYER p ON ape.PLAYER_PERSON_ID = p.PERSON_ID
	JOIN PERSON per ON ape.PLAYER_PERSON_ID = per.PERSON_ID
	WHERE SEASON_NAME = @season AND COMPETITION_NAME = @competition AND p.CLUB_NAME = @club
END

GO
