CREATE OR ALTER VIEW ALL_PLAYERS_EDITIONS AS
SELECT DISTINCT m.SEASON_NAME, m.COMPETITION_NAME, pp.PLAYER_PERSON_ID 
FROM MATCH m 
JOIN [PLAYER_PLAYED_IN_MATCH]  pp ON m.MATCH_ID = pp.MATCH_ID

GO
CREATE OR ALTER PROCEDURE GET_SELECTION_CLUB_OF_EDITION 
(@club CLUB_NAME, @competition COMPETITION_NAME, @season SEASON_NAME)
AS BEGIN
	SELECT p.PERSON_ID, per.FIRST_NAME, per.MIDDLE_NAME, per.LAST_NAME, per.BIRTH_DATE FROM ALL_PLAYERS_EDITIONS ape 
	JOIN PLAYER p ON ape.PLAYER_PERSON_ID = p.PERSON_ID
	JOIN PERSON per ON ape.PLAYER_PERSON_ID = per.PERSON_ID
	WHERE SEASON_NAME = @season AND COMPETITION_NAME = @competition AND p.CLUB_NAME = @club
END

GO
CREATE OR ALTER VIEW CLUB_INFORMATION AS
SELECT	CLUB_NAME, 
		CITY_NAME, 
		COUNTRY_NAME, 
		c.STADIUM_NAME, 
		s.CAPACITY as CAPACITY_STADIUM,
		COACH_PERSON_ID as COACH
FROM CLUB c 
JOIN STADIUM s ON s.STADIUM_NAME = c.STADIUM_NAME

GO
CREATE OR ALTER PROCEDURE GET_CLUB_INFORMATION
(@club CLUB_NAME)
AS
BEGIN
	SELECT *
	FROM dbo.CLUB_INFORMATION c
	WHERE c.CLUB_NAME = @club
END
