ALTER TABLE RED_CARD
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_RED_CARD CHECK (TIME >= 0)

GO

ALTER TABLE YELLOW_CARD
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_YELLOW_CARD CHECK (TIME >= 0)

GO

ALTER TABLE PASS
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_PASS CHECK (TIME >= 0)

GO

ALTER TABLE GOAL
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_GOAL CHECK (TIME >= 0)

GO

ALTER TABLE SHOT
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_SHOT CHECK (TIME >= 0)

GO

ALTER TABLE FOUL
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_FOUL CHECK (TIME >= 0)

GO

ALTER TABLE CORNER
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_CORNER CHECK (TIME >= 0)

GO

ALTER TABLE SUBSTITUTE
ADD CONSTRAINT CHK_VALID_MINUTE_IN_MATCH_SUBSTITUTE CHECK (TIME >= 0)

GO