CREATE OR ALTER TRIGGER TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_PLAYER_AS_RESERVE_IN_MATCH ON PLAYER_AS_RESERVE_IN_MATCH
FOR INSERT, UPDATE
AS
BEGIN
IF @@ROWCOUNT > 0
	BEGIN TRY
		IF EXISTS (
		    SELECT COUNT(POSITION.PLAYER_PERSON_ID) FROM POSITION
		    	HAVING COUNT(*) > 11
					)
			THROW 50001, 'Player must be member of home_club or out_club', 1;
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END