CREATE OR ALTER TRIGGER TRG_PERSON_IS_PLAYER_OR_COACH
	ON YELLOW_CARD
	FOR INSERT, UPDATE
	AS
BEGIN
	IF @@ROWCOUNT = 0
		RETURN
	SET NOCOUNT ON

	BEGIN TRY
		IF EXISTS(
			SELECT inserted.PERSON_ID
			FROM inserted
					 JOIN REFEREE on inserted.PERSON_ID = referee.PERSON_ID
			)
			THROW 50001, 'Referee can not have a yellow card!', 1;
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
GO
