EXEC tSQLt.NewTestClass 'test_CHK_VALID_JERSEY'
GO
CREATE OR ALTER PROCEDURE test_CHK_VALID_JERSEY.[SetUp]
AS
BEGIN
	EXEC tSQLt.FakeTable 'dbo.PLAYER'

	EXEC tSQLt.ApplyConstraint @TableName = 'dbo.PLAYER', @ConstraintName = 'CHK_VALID_JERSEY'
END
GO
CREATE OR ALTER PROCEDURE test_CHK_VALID_JERSEY.[test check jersey 1]
AS
BEGIN
	--ARRANGE

	--EXPECT
	EXEC tSQLt.ExpectNoException
	--ACT
	INSERT INTO PLAYER (JERSEY)
	VALUES (1)
	--ASSERT
END
GO
EXEC tSQLt.Run 'test_CHK_VALID_JERSEY.[test check jersey 1]'
GO
CREATE OR ALTER PROCEDURE test_CHK_VALID_JERSEY.[test check jersey 0]
AS
BEGIN
	EXEC tSQLt.ExpectException

	INSERT INTO PLAYER (JERSEY)
	VALUES (0)
END
GO
EXEC tSQLt.Run 'test_CHK_VALID_JERSEY.[test check jersey 0]'
GO
CREATE OR ALTER PROCEDURE test_CHK_VALID_JERSEY.[test check jersey 100]
AS
BEGIN
	EXEC tSQLt.ExpectException

	INSERT INTO PLAYER (JERSEY)
	VALUES (100)
END
GO
EXEC tSQLt.Run 'test_CHK_VALID_JERSEY.[test check jersey 100]'
GO
CREATE OR ALTER PROCEDURE test_CHK_VALID_JERSEY.[test check jersey 99]
AS
BEGIN
	EXEC tSQLt.ExpectNoException

	INSERT INTO PLAYER (JERSEY)
	VALUES (99)
END
GO
EXEC tSQLt.Run 'test_CHK_VALID_JERSEY.[test check jersey 99]'