EXEC TSQLT.NEWTESTCLASS 'test_TRG_VALID_AMOUNT_OF_SPECTATORS'
GO
CREATE OR ALTER PROCEDURE TEST_TRG_VALID_AMOUNT_OF_SPECTATORS.SETUP
AS
BEGIN
    EXEC TSQLT.FAKETABLE 'dbo.MATCH'
    EXEC TSQLT.FAKETABLE 'dbo.STADIUM'

    INSERT INTO STADIUM (STADIUM_NAME, CAPACITY)
    VALUES ('test', 100000)

    EXEC TSQLT.APPLYTRIGGER
        @TableName = 'dbo.MATCH',
        @TriggerName = 'TRG_VALID_AMOUNT_OF_SPECTATORS'
END
GO
CREATE OR ALTER PROCEDURE TEST_TRG_VALID_AMOUNT_OF_SPECTATORS.[test aant toeschouwers evengroot als capaciteit]
AS
BEGIN
    EXEC TSQLT.EXPECTNOEXCEPTION

    INSERT INTO MATCH (STADIUM_NAME, SPECTATORS)
    VALUES ('test', 100000)
END
GO
EXEC TSQLT.RUN
    'test_TRG_VALID_AMOUNT_OF_SPECTATORS.[test aant toeschouwers evengroot als capaciteit]'
GO
CREATE OR ALTER PROCEDURE TEST_TRG_VALID_AMOUNT_OF_SPECTATORS.[test aant toeschouwers meer dan capaciteit]
AS
BEGIN
    EXEC TSQLT.EXPECTEXCEPTION
        'Amount of spectators can''t be larger than the capacity of stadium'

    INSERT INTO MATCH (STADIUM_NAME, SPECTATORS)
    VALUES ('test', 100001)

    EXEC TSQLT.ASSERTEMPTYTABLE 'dbo.MATCH'
END
GO
EXEC TSQLT.RUN
    'test_TRG_VALID_AMOUNT_OF_SPECTATORS.[test aant toeschouwers meer dan capaciteit]'
