EXEC TSQLT.NEWTESTCLASS 'TEST_CHK_VALID_MINUTE_IN_MATCH'

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_RED_CARD]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.RED_CARD'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.RED_CARD', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_RED_CARD'

    EXEC TSQLT.ExpectException

	INSERT INTO RED_CARD (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, -10, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_YELLOW_CARD]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.YELLOW_CARD'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.YELLOW_CARD', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_YELLOW_CARD'

    EXEC TSQLT.ExpectException

	INSERT INTO YELLOW_CARD (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, -10, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_PASS]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.PASS'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.PASS', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_PASS'

    EXEC TSQLT.ExpectException

	INSERT INTO PASS (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, -10, 1)
END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_GOAL]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.GOAL'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.GOAL', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_GOAL'

    EXEC TSQLT.ExpectException

	INSERT INTO GOAL (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, -10, 1)
END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_SHOT]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.SHOT'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.SHOT', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_SHOT'

    EXEC TSQLT.ExpectException

	INSERT INTO SHOT (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, -10, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH.FOUL]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.FOUL'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.FOUL', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_FOUL'

    EXEC TSQLT.ExpectException

	INSERT INTO FOUL (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, -10, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH.SUBSTITUTE]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.SUBSTITUTE'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.SUBSTITUTE', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_SUBSTITUTE'

    EXEC TSQLT.ExpectException

    INSERT INTO SUBSTITUTE (MATCH_ID, TIME, IN_PERSON_ID, OUT_PERSON_ID)
        VALUES(1, -10, 1, 2)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH.CORNER]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.CORNER'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.CORNER', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_CORNER'

    EXEC TSQLT.ExpectException

    INSERT INTO CORNER (MATCH_ID, TIME, PERSON_ID)
        VALUES(1, -10, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_RED_CARD_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.RED_CARD'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.RED_CARD', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_RED_CARD'

    EXEC TSQLT.ExpectNoException

	INSERT INTO RED_CARD (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, 0, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_YELLOW_CARD_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.YELLOW_CARD'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.YELLOW_CARD', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_YELLOW_CARD'

    EXEC TSQLT.ExpectNoException

	INSERT INTO YELLOW_CARD (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, 0, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_PASS_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.PASS'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.PASS', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_PASS'

    EXEC TSQLT.ExpectNoException

	INSERT INTO PASS (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, 0, 1)
END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_GOAL_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.GOAL'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.GOAL', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_GOAL'

    EXEC TSQLT.ExpectNoException

	INSERT INTO GOAL (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, 0, 1)
END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH_SHOT_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.SHOT'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.SHOT', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_SHOT'

    EXEC TSQLT.ExpectNoException

	INSERT INTO SHOT (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, 0, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH.FOUL_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.FOUL'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.FOUL', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_FOUL'

    EXEC TSQLT.ExpectNoException

	INSERT INTO FOUL (MATCH_ID, TIME, PERSON_ID)
	VALUES(1, 0, 1)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH.SUBSTITUTE_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.SUBSTITUTE'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.SUBSTITUTE', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_SUBSTITUTE'

    EXEC TSQLT.ExpectNoException

    INSERT INTO SUBSTITUTE (MATCH_ID, TIME, IN_PERSON_ID, OUT_PERSON_ID)
        VALUES(1, 0, 1, 2)

END

GO

CREATE OR ALTER PROCEDURE TEST_CHK_VALID_MINUTE_IN_MATCH.[TEST_CHK_VALID_MINUTE_IN_MATCH.CORNER_SUCCES]
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.CORNER'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.CORNER', @ConstraintName = 'CHK_VALID_MINUTE_IN_MATCH_CORNER'

    EXEC TSQLT.ExpectNoException

    INSERT INTO CORNER (MATCH_ID, TIME, PERSON_ID)
        VALUES(1, 0, 1)

END

GO

EXEC TSQLT.Run[TEST_CHK_VALID_MINUTE_IN_MATCH]
