EXEC tSQLt.NewTestClass 'test_USECASE_OPHALEN_TUSSENSTAND_EDITIE'
GO
CREATE OR ALTER PROC test_USECASE_OPHALEN_TUSSENSTAND_EDITIE.SetUp
AS
BEGIN
	EXEC tSQLt.FakeTable 
END

-- punten
-- W 3
-- G 1
-- L 0