/*
De spelers die aan een wedstrijd zijn gekoppeld moeten lid zijn van een van de twee clubs die aan de wedstrijd meedoen;
*/
CREATE OR ALTER TRIGGER TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_PLAYER_AS_RESERVE_IN_MATCH ON PLAYER_AS_RESERVE_IN_MATCH
FOR INSERT, UPDATE
AS
BEGIN
IF @@ROWCOUNT > 0
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM inserted i 
									join [MATCH] m on i.MATCH_ID = m.MATCH_ID 
									join PLAYER p on p.PERSON_ID = i.PLAYER_PERSON_ID 
							WHERE not (p.CLUB_NAME = HOME_CLUB_NAME 
										OR p.CLUB_NAME = OUT_CLUB_NAME)
					)
			THROW 50001, 'Player must be member of home_club or out_club', 1;
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
GO
CREATE OR ALTER TRIGGER TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_POSITION ON POSITION
FOR INSERT, UPDATE
AS
BEGIN
IF @@ROWCOUNT > 0
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM inserted i 
									join [MATCH] m on i.MATCH_ID = m.MATCH_ID 
									join PLAYER p on p.PERSON_ID = i.PLAYER_PERSON_ID 
							WHERE not (p.CLUB_NAME = HOME_CLUB_NAME 
										OR p.CLUB_NAME = OUT_CLUB_NAME)
					)
			THROW 50001, 'Player must be member of home_club or out_club', 1;
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
GO
EXEC TSQLT.NEWTESTCLASS 'test_TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_PLAYER_AS_RESERVE_IN_MATCH'
GO
CREATE OR ALTER PROCEDURE TEST_TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_PLAYER_AS_RESERVE_IN_MATCH.SETUP
AS
BEGIN
	EXEC TSQLT.FAKETABLE 'dbo.PLAYER_AS_RESERVE_IN_MATCH'
	EXEC TSQLT.FAKETABLE 'dbo.MATCH'
	EXEC TSQLT.FAKETABLE 'dbo.PLAYER'

	INSERT INTO [MATCH] (MATCH_ID, HOME_CLUB_NAME, OUT_CLUB_NAME)
	VALUES (1, 'home_club', 'out_club')

	EXEC TSQLT.APPLYTRIGGER @TableName = 'dbo.PLAYER_AS_RESERVE_IN_MATCH', @TriggerName = 'TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_PLAYER_AS_RESERVE_IN_MATCH'
END
GO
CREATE OR ALTER PROCEDURE TEST_TRG_CHECK_CORRECT_PLAYERS_IN_MATCH_FOR_PLAYER_AS_RESERVE_IN_MATCH.[test trigger player from home_club]
AS
BEGIN
	INSERT INTO PLAYER (PERSON_ID, CLUB_NAME)
	VALUES (22, 'home_club')
	
	EXEC TSQLT.EXPECTNOEXCEPTION

	INSERT INTO PLAYER_AS_RESERVE_IN_MATCH (PLAYER_PERSON_ID, MATCH_ID)
	VALUES (22, 1)
END
EXEC TSQLT.