EXEC tSQLt.NewTestClass 'test_SHOW_MATCH_INFO'
GO
CREATE OR ALTER PROCEDURE test_SHOW_MATCH_INFO.SetUp
AS
BEGIN
	EXEC tSQLt.FakeTable 'dbo.CORNER'
	EXEC tSQLt.FakeTable 'dbo.FOUL'
	EXEC tSQLt.FakeTable 'dbo.GOAL'
	EXEC tSQLt.FakeTable 'dbo.MATCH'
	EXEC tSQLt.FakeTable 'dbo.PASS'
	EXEC tSQLt.FakeTable 'dbo.RED_CARD'
	EXEC tSQLt.FakeTable 'dbo.SHOT'
	EXEC tSQLt.FakeTable 'dbo.SUBSTITUTE'
	EXEC tSQLt.FakeTable 'dbo.YELLOW_CARD'

	INSERT INTO MATCH (MATCH_ID, SEASON_NAME, COMPETITION_NAME, START_DATE, MATCH_DAY, HOME_CLUB_NAME, OUT_CLUB_NAME, STADIUM_NAME, REFEREE_PERSON_ID, BALL_POSSESSION_HOME, BALL_POSSESSION_OUT, SPECTATORS)
	VALUES (1, '20/21', 'comp', GETDATE(), GETDATE(), 'home', 'out', 'aStadium', 420, 20, 70, 100020)

	INSERT INTO CORNER (MATCH_ID, TIME, PERSON_ID)
	VALUES (1, 2.3, 2)

	INSERT INTO FOUL (MATCH_ID, TIME, PERSON_ID)
	VALUES (1, 4, 5)

	INSERT INTO GOAL (MATCH_ID, TIME, PERSON_ID)
	VALUES (1, 55.6, 3)

	INSERT INTO PASS (MATCH_ID, TIME, PERSON_ID, SUCCES)
	VALUES (1, 53.6, 3, 1), (1, 20, 3, 0)

	INSERT INTO RED_CARD (MATCH_ID, TIME, PERSON_ID)
	VALUES (1, 80, 67)

	INSERT INTO YELLOW_CARD(MATCH_ID, TIME, PERSON_ID)
	VALUES (1, 1.1, 1)

	INSERT INTO SHOT (MATCH_ID, TIME, PERSON_ID, ON_GOAL)
	VALUES (1, 55.55, 3, 1), (1, 90.5, 99, 0)

	INSERT INTO SUBSTITUTE (MATCH_ID, TIME, IN_PERSON_ID, OUT_PERSON_ID)
	VALUES (1, 45.444, 665, 667)
END
GO
CREATE OR ALTER PROCEDURE test_SHOW_MATCH_INFO.[test test]
AS
BEGIN
	--SELECT m.*, 
	--g.MATCH_ID as GOAL_MATCH_ID, 
	--g.PERSON_ID as GOAL_PERSON_ID,
	--g.TIME as GOAL_TIME,

	--c.MATCH_ID as CORNER_MATCH_ID, 
	--c.PERSON_ID as CORNER_PERSON_ID,
	--c.TIME as CORNER_TIME,

	--g.MATCH_ID as GOAL_MATCH_ID, 
	--g.PERSON_ID as GOAL_PERSON_ID,
	--g.TIME as GOAL_TIME,

	--FROM MATCH m JOIN GOAL g ON m.MATCH_ID = g.MATCH_ID
	--						JOIN CORNER c ON m.MATCH_ID = c.MATCH_ID
	--						JOIN FOUL f ON m.MATCH_ID = f.MATCH_ID
	--						JOIN PASS p ON m.MATCH_ID = p.MATCH_ID
	--						JOIN RED_CARD rc ON m.MATCH_ID = rc.MATCH_ID
	--						JOIN YELLOW_CARD yc ON m.MATCH_ID = yc.MATCH_ID
	--						JOIN SHOT s ON m.MATCH_ID = s.MATCH_ID
	--						JOIN SUBSTITUTE sub ON m.MATCH_ID = sub.MATCH_ID

END
GO
EXEC tSQLt.Run 'test_SHOW_MATCH_INFO.[test test]'
GO
--CREATE OR ALTER PROCEDURE test_SHOW_MATCH_INFO.SetUp
--AS
--BEGIN

--END
--GO
--CREATE OR ALTER PROCEDURE test_SHOW_MATCH_INFO.SetUp
--AS
--BEGIN

--END