EXEC TSQLT.NEWTESTCLASS 'TEST_TRG_VALID_ROUND_START_DATE';

GO

CREATE OR ALTER PROCEDURE TEST_TRG_VALID_ROUND_START_DATE.TEST_TRG_VALID_ROUND_START_DATE_SUCCESS
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.ROUND'

    EXEC TSQLT.FAKETABLE 'dbo.MATCHDAY'

    EXEC TSQLT.APPLYTRIGGER
        @TableName = 'dbo.ROUND', @TriggerName = 'TRG_VALID_ROUND_START_DATE'

    EXEC TSQLT.EXPECTNOEXCEPTION

    INSERT INTO DBO.MATCHDAY (
        SEASON_NAME, COMPETITION_NAME, START_DATE, MATCH_DAY
    )
    VALUES('NAME', 'COMPETITION_NAME', '12-10-25', '12-10-25')

    INSERT INTO DBO.ROUND (SEASON_NAME, COMPETITION_NAME, START_DATE)
    VALUES('NAME', 'COMPETITION_NAME', '12-10-25')

END;

GO

CREATE OR ALTER PROCEDURE TEST_TRG_VALID_ROUND_START_DATE.TEST_TRG_VALID_ROUND_START_DATE_FAILS
AS
BEGIN

    EXEC TSQLT.FAKETABLE 'dbo.ROUND'

    EXEC TSQLT.FAKETABLE 'dbo.MATCHDAY'

    EXEC TSQLT.APPLYTRIGGER
        @TableName = 'dbo.ROUND', @TriggerName = 'TRG_VALID_ROUND_START_DATE'

    EXEC TSQLT.EXPECTEXCEPTION

    INSERT INTO DBO.MATCHDAY (
        SEASON_NAME, COMPETITION_NAME, START_DATE, MATCH_DAY
    )
    VALUES('NAME', 'COMPETITION_NAME', '12-10-25', '12-10-25')

    INSERT INTO DBO.ROUND (SEASON_NAME, COMPETITION_NAME, START_DATE)
    VALUES('NAME', 'COMPETITION_NAME', '12-10-20')

END;

GO

EXEC TSQLT.RUN'TEST_TRG_VALID_ROUND_START_DATE';
