EXEC tSQLt.NewTestClass 'test_TRG_PLAYER_MUST_BE_ONE_SUBTYPE_ON_COACH'
GO
CREATE OR ALTER PROCEDURE test_TRG_PLAYER_MUST_BE_ONE_SUBTYPE_ON_COACH.SetUp
AS
BEGIN
	EXEC tSQLt.FakeTable 'dbo.COACH'
	EXEC tSQLt.FakeTable 'dbo.REFEREE'
	EXEC tSQLt.FakeTable 'dbo.PLAYER'

	EXEC tSQLt.ApplyTrigger 'dbo.COACH', 'TRG_PLAYER_MUST_BE_ONE_SUBTYPE_ON_COACH'
END
GO
