EXEC TSQLT.NEWTESTCLASS 'TEST_TRG_VALID_ROUND_START_DATE';

GO

CREATE OR ALTER PROCEDURE TEST_TRG_VALID_ROUND_START_DATE.TEST_TRG_VALID_ROUND_START_AND_END_DATE_SUCCESS
AS
BEGIN

	EXEC TSQLT.FAKETABLE 'dbo.ROUND'

	EXEC TSQLT.FAKETABLE 'dbo.SEASON'

	EXEC TSQLT.APPLYTRIGGER
		 @TableName = 'dbo.ROUND', @TriggerName = 'TRG_VALID_ROUND_START_DATE'

	EXEC TSQLT.EXPECTNOEXCEPTION

	INSERT INTO DBO.SEASON (SEASON_NAME, SEASON_START, SEASON_END)
	VALUES ('NAME', '12-10-25', '12-10-30')

	INSERT INTO DBO.ROUND (SEASON_NAME, COMPETITION_NAME, START_DATE)
	VALUES ('NAME', 'COMPETITION_NAME', '12-10-25')

END;

GO

CREATE OR ALTER PROCEDURE TEST_TRG_VALID_ROUND_START_DATE.TEST_TRG_VALID_ROUND_START_DATE_FAILS
AS
BEGIN

	EXEC TSQLT.FAKETABLE 'dbo.ROUND'

	EXEC TSQLT.FAKETABLE 'dbo.SEASON'

	EXEC TSQLT.APPLYTRIGGER
		 @TableName = 'dbo.ROUND', @TriggerName = 'TRG_VALID_ROUND_START_DATE'

	EXEC TSQLT.ExpectException

	INSERT INTO DBO.SEASON (SEASON_NAME, SEASON_START, SEASON_END)
	VALUES ('NAME', '12-10-25', '12-10-30')

	INSERT INTO DBO.ROUND (SEASON_NAME, COMPETITION_NAME, START_DATE)
	VALUES ('NAME', 'COMPETITION_NAME', '12-09-24')

END;

GO

CREATE OR ALTER PROCEDURE TEST_TRG_VALID_ROUND_START_DATE.TEST_TRG_VALID_ROUND_END_DATE_FAILS
AS
BEGIN

	EXEC TSQLT.FAKETABLE 'dbo.ROUND'

	EXEC TSQLT.FAKETABLE 'dbo.SEASON'

	EXEC TSQLT.APPLYTRIGGER
		 @TableName = 'dbo.ROUND', @TriggerName = 'TRG_VALID_ROUND_START_DATE'

	EXEC TSQLT.ExpectException

	INSERT INTO DBO.SEASON (SEASON_NAME, SEASON_START, SEASON_END)
	VALUES ('NAME', '12-10-24', '12-10-30')

	INSERT INTO DBO.ROUND (SEASON_NAME, COMPETITION_NAME, START_DATE)
	VALUES ('NAME', 'COMPETITION_NAME', '12-12-31')

END;

GO

EXEC TSQLT.RUN 'TEST_TRG_VALID_ROUND_START_DATE';
