EXEC TSQLT.NEWTESTCLASS 'test_CHK_VALID_JERSEY'
GO
CREATE OR ALTER PROCEDURE TEST_CHK_VALID_JERSEY.SETUP
AS
BEGIN
    EXEC TSQLT.FAKETABLE 'dbo.PLAYER'

    EXEC TSQLT.APPLYCONSTRAINT
        @TableName = 'dbo.PLAYER', @ConstraintName = 'CHK_VALID_JERSEY'
END
GO
CREATE OR ALTER PROCEDURE TEST_CHK_VALID_JERSEY.[test check jersey 1]
AS
BEGIN
    EXEC TSQLT.EXPECTNOEXCEPTION
    
    INSERT INTO PLAYER (JERSEY)
    VALUES (1)
END
GO
EXEC TSQLT.RUN 'test_CHK_VALID_JERSEY.[test check jersey 1]'
GO
CREATE OR ALTER PROCEDURE TEST_CHK_VALID_JERSEY.[test check jersey 0]
AS
BEGIN
    EXEC TSQLT.EXPECTEXCEPTION

    INSERT INTO PLAYER (JERSEY)
    VALUES (0)
END
GO
EXEC TSQLT.RUN 'test_CHK_VALID_JERSEY.[test check jersey 0]'
GO
CREATE OR ALTER PROCEDURE TEST_CHK_VALID_JERSEY.[test check jersey 100]
AS
BEGIN
    EXEC TSQLT.EXPECTEXCEPTION

    INSERT INTO PLAYER (JERSEY)
    VALUES (100)
END
GO
EXEC TSQLT.RUN 'test_CHK_VALID_JERSEY.[test check jersey 100]'
GO
CREATE OR ALTER PROCEDURE TEST_CHK_VALID_JERSEY.[test check jersey 99]
AS
BEGIN
    EXEC TSQLT.EXPECTNOEXCEPTION

    INSERT INTO PLAYER (JERSEY)
    VALUES (99)
END
GO
EXEC TSQLT.RUN 'test_CHK_VALID_JERSEY.[test check jersey 99]'
